### ISSUE TITLE
[BUG] 校验[失效]书源导致程序崩溃

### ISSUE THREAD

**Issue by ShaoLi0ly** [gedoor/legado#1103]
### 机型（如Redmi K30 Pro）
>华为 mate30 pro 4g

### 安卓版本（如Android 7.1.1）
>鸿蒙2.0.0.127

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.062211

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带

### 问题描述（简要描述发生的问题）
>校验书源导致软件崩溃

### 使用书源（填写URL或者JSON）
>
http://shuyuan.miaogongzi.net/shuyuan/1622509629.json
http://no-mystery.gitee.io/shuyuan/%E5%85%A8%E7%BD%91%E9%80%9A%E7%94%A8.json
还有之前公众号更新的所有书源我都导入了
```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>书源管理 - 搜索[失效]书源 - 全选 - 校验。
应该是校验到可用书源，对应的搜索结果更新了，然后软件就崩溃了

### 日志提交（问题截图或者日志）
>
BOARD=LIO
CPU_ABI2=
HOST=cn-central-hcd-2a-f84d5cbef1623325691463-75c79d79cc-v2dwv
versionName=3.21.062211
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@26fed10
CPU_ABI=arm64-v8a
PERMISSIONS_REVIEW_REQUIRED=true
DISPLAY=LIO-AL00 2.0.0.127(C00E120R5P5)
SUPPORTED_ABIS=[Ljava.lang.String;@e430009
FINGERPRINTEX=HUAWEI/LIO-AL00/HWLIO:10/HUAWEILIO-AL00/102.0.0.127C00:user/release-keys
FINGERPRINT=HUAWEI/LIO-AL00/HWLIO:10/HUAWEILIO-AL00/102.0.0.127C00:user/release-keys
PRODUCT=LIO-AL00
ID=HUAWEILIO-AL00
HWFINGERPRINT=///LIO-LGRP1-CHN 2.0.0.127/LIO-AL00-CUST 2.0.0.120(C00)/LIO-AL00-PRELOAD 2.0.0.5(C00R5)//
TYPE=user
SERIAL=unknown
DEVICE=HWLIO
TIME=1623326293000
MODEL=LIO-AL00
MANUFACTURER=HUAWEI
USER=test
versionCode=7918
BRAND=HUAWEI
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@1cdddd3
HARDWARE=kirin990
IS_DEBUGGABLE=false
BOOTLOADER=unknown
RADIO=unknown
UNKNOWN=unknown
IS_EMULATOR=false
TAGS=release-keys
java.lang.RuntimeException: Exception while computing database live data.
 at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:92)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:929)
Caused by: java.lang.IllegalStateException: Couldn't read row 241, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
 at android.database.CursorWindow.nativeGetLong(Native Method)
 at android.database.CursorWindow.getLong(CursorWindow.java:542)
 at android.database.CursorWindow.getInt(CursorWindow.java:609)
 at android.database.AbstractWindowedCursor.getInt(AbstractWindowedCursor.java:71)
 at io.legado.app.data.dao.BookSourceDao_Impl$6.call(BookSourceDao_Impl.java:563)
 at io.legado.app.data.dao.BookSourceDao_Impl$6.call(BookSourceDao_Impl.java:516)
 at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:90)
 ... 3 more
java.lang.IllegalStateException: Couldn't read row 241, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
 at android.database.CursorWindow.nativeGetLong(Native Method)
 at android.database.CursorWindow.getLong(CursorWindow.java:542)
 at android.database.CursorWindow.getInt(CursorWindow.java:609)
 at android.database.AbstractWindowedCursor.getInt(AbstractWindowedCursor.java:71)
 at io.legado.app.data.dao.BookSourceDao_Impl$6.call(BookSourceDao_Impl.java:563)
 at io.legado.app.data.dao.BookSourceDao_Impl$6.call(BookSourceDao_Impl.java:516)
 at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:90)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:929)

**Comment by gedoor** [comment]
ok

**Comment by zzt722** [comment]
这个问题怎么解决

**Comment by gedoor** [comment]
看报错是校验书源时搜索书源引起的,具体原因我还没找到

**Comment by zzt722** [comment]
好的

**Comment by zzt722** [comment]
这个bug解决了吗？

**Comment by zzt722** [comment]
破溃日志：
BOARD=PCT
CPU_ABI2=
HOST=cn-central-1b-bc1fbaa521596190469445-3126494596-4td7b
versionName=3.21.071520
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@b820af3
CPU_ABI=arm64-v8a
PERMISSIONS_REVIEW_REQUIRED=true
DISPLAY=PCT-AL10 10.1.0.162(C00E160R4P11)
SUPPORTED_ABIS=[Ljava.lang.String;@a6e3b0
FINGERPRINTEX=HONOR/PCT-AL10/HWPCT:10/HUAWEIPCT-AL10/102.0.0.135C00:user/release-keys
FINGERPRINT=HONOR/PCT-AL10/HWPCT:10/HUAWEIPCT-AL10/10.1.0.162C00:user/release-keys
PRODUCT=PCT-AL10
ID=HUAWEIPCT-AL10
HWFINGERPRINT=///PCT-LGRP1-CHN 2.0.0.135/PCT-AL10-CUST 2.0.0.135(C00)/PCT-AL10-PRELOAD 2.0.0.4(C00R2)//
TYPE=user
SERIAL=unknown
DEVICE=HWPCT
TIME=1596194419000
MODEL=PCT-AL10
MANUFACTURER=HUAWEI
USER=test
versionCode=8076
BRAND=HONOR
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@a6e0962
HARDWARE=kirin980
IS_DEBUGGABLE=false
BOOTLOADER=unknown
RADIO=unknown
UNKNOWN=unknown
IS_EMULATOR=false
TAGS=release-keys
java.lang.RuntimeException: Exception while computing database live data.
	at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:92)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
Caused by: java.lang.IllegalStateException: Couldn't read row 262, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:542)
	at android.database.CursorWindow.getInt(CursorWindow.java:609)
	at android.database.AbstractWindowedCursor.getInt(AbstractWindowedCursor.java:71)
	at io.legado.app.data.dao.BookSourceDao_Impl$6.call(BookSourceDao_Impl.java:570)
	at io.legado.app.data.dao.BookSourceDao_Impl$6.call(BookSourceDao_Impl.java:523)
	at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:90)
	... 3 more
java.lang.IllegalStateException: Couldn't read row 262, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:542)
	at android.database.CursorWindow.getInt(CursorWindow.java:609)
	at android.database.AbstractWindowedCursor.getInt(AbstractWindowedCursor.java:71)
	at io.legado.app.data.dao.BookSourceDao_Impl$6.call(BookSourceDao_Impl.java:570)
	at io.legado.app.data.dao.BookSourceDao_Impl$6.call(BookSourceDao_Impl.java:523)
	at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
