### ISSUE TITLE
[BUG] 无法打开web服务

### ISSUE THREAD

**Issue by htname** [gedoor/legado#1197]
### 机型
>vivo x20

### 版本
>3.21.073123(Github Actions)
### 网络环境
>联通

### 问题描述（简要描述发生的问题）
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

https://user-images.githubusercontent.com/59814884/127757703-25795f8f-9baa-4ba0-92fc-00b9cb29a3e4.mp4

### 日志提交（问题截图或者日志）
>
```
BOARD=sdm660
CPU_ABI2=
HOST=compiler030
versionName=3.21.073123
IS_TREBLE_ENABLED=false
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@bb0b994
CPU_ABI=arm64-v8a
PERMISSIONS_REVIEW_REQUIRED=false
IS_USERDEBUG=false
DISPLAY=OPM1.171019.011 release-keys
SUPPORTED_ABIS=[Ljava.lang.String;@f424c3d
FINGERPRINT=vivo/PD1709/PD1709:8.1.0/OPM1.171019.011/compil04142112:user/release-keys
PRODUCT=PD1709
ID=OPM1.171019.011
TYPE=user
SERIAL=b49651b
IS_CONTAINER=false
IS_ENG=false
DEVICE=PD1709
TIME=1618405960000
IS_USER=true
MODEL=vivo X20
MANUFACTURER=vivo
USER=compiler
versionCode=1
BRAND=vivo
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@77fb9e7
HARDWARE=qcom
IS_DEBUGGABLE=false
BOOTLOADER=unknown
RADIO=unknown
TAG=Build
UNKNOWN=unknown
IS_EMULATOR=false
TAGS=release-keys
java.lang.RuntimeException: Unable to start service io.legado.app.service.WebTileService@2ad16e8 with Intent { act=start cmp=io.legado.app.releaseA/io.legado.app.service.WebTileService }: java.lang.NullPointerException: Attempt to invoke a virtual method on a null object reference
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3620)
	at android.app.ActivityThread.-wrap20(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1781)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:192)
	at android.app.ActivityThread.main(ActivityThread.java:6744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:525)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)
Caused by: java.lang.NullPointerException: Attempt to invoke a virtual method on a null object reference
	at io.legado.app.service.WebTileService.onStartCommand(WebTileService.kt:16)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3603)
	... 8 more
java.lang.NullPointerException: Attempt to invoke a virtual method on a null object reference
	at io.legado.app.service.WebTileService.onStartCommand(WebTileService.kt:16)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3603)
	at android.app.ActivityThread.-wrap20(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1781)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:192)
	at android.app.ActivityThread.main(ActivityThread.java:6744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:525)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)
```

**Comment by gedoor** [comment]
这个是因为最近添加的快捷开关导致的,低版本安卓不支持这个,忘了加判断,下版本解决
