### ISSUE TITLE
[BUG] 在发现和订阅页面多点触控时可能出现 pointerIndex out of range 错误，导致程序崩溃

### ISSUE THREAD

**Issue by Glavor** [gedoor/legado#1235]
### 机型（如Redmi K30 Pro）
>
小米11 Pro

### 安卓版本（如Android 7.1.1）
>
Android 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
3.21.081308

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>
在发现和订阅页面多点触控时程序崩溃，报错 java.lang.IllegalArgumentException: pointerIndex out of range

https://user-images.githubusercontent.com/32591808/129299271-3ee31b38-380b-4343-bb40-4da36dde4c0f.mp4

换了小米8也会出现相同问题

https://user-images.githubusercontent.com/32591808/129299398-3c3b60d8-10d0-4886-b36a-72666c9a851e.mp4

### 使用书源（填写URL或者JSON）
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
多次尝试后发现如果在多点触控过程中抬起了一根手指，剩下的手指继续滑动，就大概率会报错。
比如三跟手指快速扫过屏幕，然后依次抬起，基本可以稳定触发

### 日志提交（问题截图或者日志）
>
```
BOARD=mars
CPU_ABI2=
HOST=c4-xm-ota-bd070.bj
versionName=3.21.081308
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@a5525a1
CPU_ABI=arm64-v8a
PERMISSIONS_REVIEW_REQUIRED=true
DISPLAY=RKQ1.201112.002 test-keys
SUPPORTED_ABIS=[Ljava.lang.String;@33e43c6
FINGERPRINT=Xiaomi/mars/mars:11/RKQ1.201112.002/V12.5.12.0.RKACNXM:user/release-keys
PRODUCT=mars
ID=RKQ1.201112.002
TYPE=user
SERIAL=unknown
DEVICE=mars
TIME=1628101363000
MODEL=M2102K1AC
MANUFACTURER=Xiaomi
USER=builder
versionCode=8566
BRAND=Xiaomi
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@8f34a08
HARDWARE=qcom
IS_DEBUGGABLE=false
BOOTLOADER=unknown
RADIO=unknown
UNKNOWN=unknown
IS_EMULATOR=false
TAGS=release-keys
java.lang.IllegalArgumentException: pointerIndex out of range
	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
	at android.view.MotionEvent.getX(MotionEvent.java:2413)
	at androidx.viewpager.widget.ViewPager.onInterceptTouchEvent(ViewPager.java:2072)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2693)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3151)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2830)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:508)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1875)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4242)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:466)
	at android.view.View.dispatchPointerEvent(View.java:14722)
	at com.xiaomi.mirror.MirrorManagerUtils.dispatchPointerEvent(MirrorManagerUtils.java:43)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6291)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6066)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5521)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5578)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5544)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5696)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5552)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5753)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5525)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5578)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5544)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5552)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5525)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8421)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8372)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8315)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8557)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:241)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:190)
	at android.app.ActivityThread.main(ActivityThread.java:8052)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

**Comment by haxc** [comment]
是小米的系统垃圾吧？！我测试oppo的没问题
