### ISSUE TITLE
[BUG] 规则订阅更新书源Crash

### ISSUE THREAD

**Issue by GitHubWebb** [gedoor/legado#1281]
### 机型（如Redmi K30 Pro）
>
华为meta30pro

### 安卓版本（如Android 7.1.1）
>
鸿蒙2.0

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> versionName=3.21.08281151

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

移动wifi
### 问题描述（简要描述发生的问题）
>
订阅-->规则订阅-->点击书源规则（更新）-->Crash

### 使用书源（填写URL或者JSON）
>
https://gitee.com/namofree/yuedu3/raw/legado3booksource/legado3_booksource_by_Namo.json

### 日志提交（问题截图或者日志）
>

BOARD=LIO
CPU_ABI2=
HOST=cn-central-hcd-2a-5bde916b91627544650223-5b6949c957-fkdfm
versionName=3.21.08281151
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@346d8c1
CPU_ABI=arm64-v8a
PERMISSIONS_REVIEW_REQUIRED=true
DISPLAY=LIO-AN00 2.0.0.166(C00E160R5P6)
SUPPORTED_ABIS=[Ljava.lang.String;@17b4866
FINGERPRINTEX=HUAWEI/LIO-AN00/HWLIO:10/HUAWEILIO-AN00/102.0.0.166C00:user/release-keys
FINGERPRINT=HUAWEI/LIO-AN00/HWLIO:10/HUAWEILIO-AN00/102.0.0.166C00:user/release-keys
PRODUCT=LIO-AN00
ID=HUAWEILIO-AN00
HWFINGERPRINT=///LIO-LGRP3-CHN 2.0.0.166/LIO-AN00-CUST 2.0.0.160(C00)/LIO-AN00-PRELOAD 2.0.0.6(C00R5)//
TYPE=user
SERIAL=unknown
DEVICE=HWLIO
TIME=1627545048000
MODEL=LIO-AN00
MANUFACTURER=HUAWEI
USER=test
versionCode=8758
BRAND=HUAWEI
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@1dd55a8
HARDWARE=kirin990
IS_DEBUGGABLE=false
BOOTLOADER=unknown
RADIO=unknown
UNKNOWN=unknown
IS_EMULATOR=false
TAGS=release-keys
java.lang.IllegalStateException: Couldn't read row 182, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:542)
	at android.database.CursorWindow.getInt(CursorWindow.java:609)
	at android.database.AbstractWindowedCursor.getInt(AbstractWindowedCursor.java:71)
	at io.legado.app.data.dao.BookSourceDao_Impl$10.call(BookSourceDao_Impl.java:1362)
	at io.legado.app.data.dao.BookSourceDao_Impl$10.call(BookSourceDao_Impl.java:1312)
	at androidx.room.CoroutinesRoom$Companion$createFlow$1$1.invokeSuspend(CoroutinesRoom.kt:122)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

**Comment by h11128** [comment]
你那个都不是订阅源，而是书源

**Comment by GitHubWebb** [comment]
> 你那个都不是订阅源，而是书源

我没有说是订阅源吧,只是在描述流程😁
