### ISSUE TITLE
java.ajax函数不能在搜索标签中的分类规则运行，在最新章节规则运行正常[BUG] 

### ISSUE THREAD

**Issue by wpyok500** [gedoor/legado#1292]
### 机型（如Redmi K30 Pro）
>荣耀 20 pro

### 安卓版本（如Android 7.1.1）
>鸿蒙OS 2.0

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.082719

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>全网

### 问题描述（简要描述发生的问题）
>java.ajax函数不能在搜索标签中的分类规则运行，在最新章节规则运行正常

### 使用书源（填写URL或者JSON）
>

```json
[
  {
    "bookSourceComment": "",
    "bookSourceName": "笔趣阁3",
    "bookSourceType": 0,
    "bookSourceUrl": "www.zhhtxt.com",
    "customOrder": 0,
    "enabled": true,
    "enabledExplore": true,
    "header": "{\n    \"User-Agent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36\",\n    \"Content-Type\":\"application/x-www-form-urlencoded\"\n}",
    "lastUpdateTime": 1630628087083,
    "ruleBookInfo": {
      "author": "[property$=author]@content",
      "coverUrl": "[property$=image]@content",
      "intro": "[property$=description]@content",
      "kind": "[property$=category]@content",
      "lastChapter": "[property$=latest_chapter_name]@content&&[property$=update_time]@content",
      "name": "[property$=book_name]@content",
      "tocUrl": ".listmain@dd!0:1:2:3:4:5:6:7:8:9:10:11"
    },
    "ruleContent": {
      "content": "#content@textNodes"
    },
    "ruleExplore": {},
    "ruleSearch": {
      "author": ".s4@text",
      "bookList": ".search-list>ul>li!0",
      "bookUrl": ".s2>a@href",
      "coverUrl": "<js>java.get('html')</js>[property$=image]@content",
      "intro": "<js>java.get('html')</js>[property$=description]@content",
      "kind": "",#此代码.s2>a@href<js>var ht =java.ajax(result);\njava.put('html',ht);\n</js>[property$=category]@content 在分类无法正常运行，放在最新章节规则正常运行
      "lastChapter": ".s2>a@href<js>var ht =java.ajax(result);\njava.put('html',ht);\n</js>[property$=category]@content",#放在此处正常运行，有返回结果
      "name": ".s2@text"
    },
    "ruleToc": {
      "chapterList": ".listmain@dd!0:1:2:3:4:5:6:7:8:9:10:11",
      "chapterName": "a@text",
      "chapterUrl": "a@href"
    },
    "searchUrl": "https://so.biqusoso.com/s.php?ie=utf-8&siteid=zanghaihuatxt.com&q={{key}}",
    "weight": 0
  }
]





```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
# java.ajax在最新章节正常运行，返回结果
![}2A 8B(CXWR9{ TRCQV1AW8](https://user-images.githubusercontent.com/14154547/131932410-fa733fdf-4296-4c78-8e47-645134885776.jpg)

### 日志提交（问题截图或者日志）
># java.ajax在分类规则无返回结果
![)3ANA}PR ${)0 XER03SLIY](https://user-images.githubusercontent.com/14154547/131932770-848bf982-234a-4a92-8906-c89889eaa669.jpg)

**Comment by gedoor** [comment]
我看下

**Comment by gedoor** [comment]
这个result是list, 取值时取result.get(0)

**Comment by wpyok500** [comment]
java.ajax请求书籍详情页的result不是HTML源代码吗？

**Comment by gedoor** [comment]
分类返回的是List,这规则可以拆分为3个规则,除了js其它的都会返回List,因为分类就是这样的

**Comment by gedoor** [comment]
js里面的result变量是一个list

**Comment by wpyok500** [comment]
@gedoor 好像不是result返回问题，是java.ajax在分类规则执行会报错，我使用java.log(java.ajax(result))可以看到报错，而在最新章节规则中执行不会，正常返回HTML内容
# 在分类规则执行，报错日志截图
![Screenshot_20210904_064230_io legado app release](https://user-images.githubusercontent.com/14154547/132072409-f861cf37-df1b-4ba4-b645-d367662cd31e.jpg)

#在最新规则执行，正常返回html内容截图
![Screenshot_20210904_064435_io legado app release](https://user-images.githubusercontent.com/14154547/132072422-47e1ccb9-70d1-4b35-a14e-7e03a36b8871.jpg)

**Comment by wpyok500** [comment]
[00:01.051] java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
	at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1260)
	at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1633)
	at io.legado.app.help.http.OkHttpUtilsKt.get(OkHttpUtils.kt:98)
	at io.legado.app.model.analyzeRule.AnalyzeUrl$getStrResponse$2.invoke(AnalyzeUrl.kt:294)
	at io.legado.app.model.analyzeRule.AnalyzeUrl$getStrResponse$2.invoke(AnalyzeUrl.kt:283)
	at io.legado.app.help.http.OkHttpUtilsKt.newCallStrResponse(OkHttpUtils.kt:40)
	at io.legado.app.model.analyzeRule.AnalyzeUrl.getStrResponse(AnalyzeUrl.kt:283)
	at io.legado.app.model.analyzeRule.AnalyzeUrl.getStrResponse$default(AnalyzeUrl.kt:264)
	at io.legado.app.model.analyzeRule.AnalyzeRule$ajax$1.invokeSuspend(AnalyzeRule.kt:650)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at io.legado.app.model.analyzeRule.AnalyzeRule.ajax(AnalyzeRule.kt:647)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at com.sun.script.javascript.RhinoScriptEngine$1.superDoTopCall(RhinoScriptEngine.java:146)
	at com.sun.script.javascript.RhinoScriptEngine$1.doTopCall(RhinoScriptEngine.java:139)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:121)
	at org.mozilla.javascript.Context.evaluateReader(Context.java:1264)
	at com.sun.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:244)
	at com.sun.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:270)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:216)
	at io.legado.app.model.analyzeRule.AnalyzeRule.evalJS(AnalyzeRule.kt:640)
	at io.legado.app.model.analyzeRule.AnalyzeRule.getStringList(AnalyzeRule.kt:150)
	at io.legado.app.model.analyzeRule.AnalyzeRule.getStringList$default(AnalyzeRule.kt:136)
	at io.legado.app.model.webBook.BookList.getSearchItem(BookList.kt:188)
	at io.legado.app.model.webBook.BookList.analyzeBookList(BookList.kt:93)
	at io.legado.app.model.webBook.WebBook.searchBookAwait(WebBook.kt:84)
	at io.legado.app.model.webBook.WebBook$searchBookAwait$1.invokeSuspend(Unknown Source:18)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by gedoor** [comment]
.s2>a@href<js>var ht =java.ajax(result.get(0));
java.log(ht);
</js>

**Comment by wpyok500** [comment]
测试OK，多谢大佬，指导技巧。
