### ISSUE TITLE
[BUG] 备份恢复失败

### ISSUE THREAD

**Issue by inkwells** [gedoor/legado#1305]
### 机型
> 小米 MIX 2S

### 安卓版本
> Android 10

### 阅读Legdao版本
> 3.21.090617

### 网络环境
> 移动

### 问题描述
> 备份恢复失败

### 使用书源
> 无

### 复现步骤
> 点击备份路径，打开系统文件夹选择器，选择文件夹
> 点击备份
> 点击恢复，确认。然后就崩溃了...

### 日志提交（问题截图或者日志）
> 以下是 崩溃日志

```
BOARD=sdm845
CPU_ABI2=
HOST=c4-miui-ota-bd076.bj
versionName=3.21.090117
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@6841cb2
CPU_ABI=arm64-v8a
PERMISSIONS_REVIEW_REQUIRED=true
DISPLAY=QKQ1.190828.002 test-keys
SUPPORTED_ABIS=[Ljava.lang.String;@aaaa403
FINGERPRINT=Xiaomi/polaris/polaris:10/QKQ1.190828.002/20.9.4:user/release-keys
PRODUCT=polaris
ID=QKQ1.190828.002
TYPE=user
SERIAL=unknown
DEVICE=polaris
TIME=1599147578000
MODEL=MIX 2S
MANUFACTURER=Xiaomi
USER=builder
versionCode=8794
BRAND=Xiaomi
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@d905ebd
HARDWARE=qcom
IS_DEBUGGABLE=false
BOOTLOADER=unknown
RADIO=unknown
UNKNOWN=unknown
IS_EMULATOR=false
TAGS=release-keys
java.lang.IllegalArgumentException: json string can not be null or empty
	at com.jayway.jsonpath.internal.Utils.notEmpty(Utils.java:383)
	at com.jayway.jsonpath.internal.ParseContextImpl.parse(ParseContextImpl.java:36)
	at io.legado.app.help.storage.ImportOldData.importOldSource(ImportOldData.kt:97)
	at io.legado.app.help.storage.Restore$restoreDatabase$2.invokeSuspend(Restore.kt:131)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by gedoor** [comment]
这个应该解决了
