### ISSUE TITLE
[BUG] 朗读崩溃

### ISSUE THREAD

**Issue by lols** [gedoor/legado#1381]
### 机型（如Redmi K30 Pro）
>KS660KL

### 安卓版本（如Android 7.1.1）
>10

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>legado_app_3.21.101610

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>wifi

### 问题描述（简要描述发生的问题）
>朗读一半突然崩溃，前个版本不会legado_app_3.21.101221

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>FATAL EXCEPTION: main
Process: io.legado.app.release, PID: 25170
java.lang.ArithmeticException: divide by zero
	at io.legado.app.service.HttpReadAloudService$upPlayPos$1.invokeSuspend(HttpReadAloudService.kt:284)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:239)
	at android.app.ActivityThread.main(ActivityThread.java:7500)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by gedoor** [comment]
ok,我修复一下
