### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by 13120533506** [gedoor/legado#1438]
### 机型（如Redmi K30 Pro）
>Xiaomi 11 Ultra

### 安卓版本（如Android 7.1.1）
>Android 12

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.112121

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>ALL

### 问题描述（简要描述发生的问题）
>打开Web服务开关；打开语音朗读开关；点击理线缓存按钮这几个操作时，软件crash,，提示Java.lang.runtimeexcption

### 使用书源（填写URL或者JSON）
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>打开Web服务开关；打开语音朗读开关；点击理线缓存按钮这

### 日志提交（问题截图或者日志）
>MANUFACTURER=Xiaomi
versionName=3.21.112121
versionCode=9558
BRAND=Xiaomi
java.lang.RuntimeException: Unable to create service io.legado.app.service.WebService: java.lang.IllegalArgumentException: io.legado.app.release: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
 at android.app.ActivityThread.handleCreateService(ActivityThread.java:4634)
 at android.app.ActivityThread.access$1800(ActivityThread.java:273)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2146)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:210)
 at android.os.Looper.loop(Looper.java:299)
 at android.app.ActivityThread.main(ActivityThread.java:8254)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: java.lang.IllegalArgumentException: io.legado.app.release: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
 at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
 at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
 at android.app.PendingIntent.getActivity(PendingIntent.java:444)
 at android.app.PendingIntent.getActivity(PendingIntent.java:408)
 at io.legado.app.service.WebService.upNotification(WebService.kt:154)
 at io.legado.app.service.WebService.onCreate(WebService.kt:44)
 at android.app.ActivityThread.handleCreateService(ActivityThread.java:4621)
 ... 9 more
java.lang.IllegalArgumentException: io.legado.app.release: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
 at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
 at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
 at android.app.PendingIntent.getActivity(PendingIntent.java:444)
 at android.app.PendingIntent.getActivity(PendingIntent.java:408)
 at io.legado.app.service.WebService.upNotification(WebService.kt:154)
 at io.legado.app.service.WebService.onCreate(WebService.kt:44)
 at android.app.ActivityThread.handleCreateService(ActivityThread.java:4621)
 at android.app.ActivityThread.access$1800(ActivityThread.java:273)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2146)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:210)
 at android.os.Looper.loop(Looper.java:299)
 at android.app.ActivityThread.main(ActivityThread.java:8254)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by gedoor** [comment]
收到

**Comment by gedoor** [comment]
加我qq77148227帮测试下,我的手机还没升级到android12,模拟器又有问题

**Comment by 13120533506** [comment]
好的，我的QQ是2230993795，验证已发送，烦请通过。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gedoor/legado"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月27日(星期六) 晚上6:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gedoor/legado] [BUG]  (Issue #1438)





 
加我qq77148227帮测试下,我的手机还没升级到android12,模拟器又有问题
