### ISSUE TITLE
提交一个发生了几次的崩溃

### ISSUE THREAD

**Issue by Richard1Chen** [gedoor/legado#1485]
MANUFACTURER=HUAWEI
versionName=3.21.121021
versionCode=9604
BRAND=HONOR
java.lang.IllegalStateException: interceptor io.legado.app.help.http.cronet.CronetInterceptor@965db30 returned a response with no body
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:118)
	at io.legado.app.help.http.HttpHelperKt$okHttpClient$2.invoke$lambda-0(HttpHelper.kt:44)
	at io.legado.app.help.http.HttpHelperKt$okHttpClient$2.$r8$lambda$kRqrSLhiLxBxGt0THgD0pg4Jiig(Unknown Source:0)
	at io.legado.app.help.http.HttpHelperKt$okHttpClient$2$$ExternalSyntheticLambda0.intercept(Unknown Source:0)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
![Screenshot_20211231_220656_io legado app release](https://user-images.githubusercontent.com/38020996/147827541-61806f2e-4222-42ab-b804-ac383bfdd78b.jpg)

**Comment by yjvv1** [comment]
有没有发现3.21.122920版本txt目录识别不全，跳章，并且章节内容也不全

**Comment by gedoor** [comment]
新版本以修复
