### ISSUE TITLE
[BUG] 打开Web服务，切出app后很快崩溃

### ISSUE THREAD

**Issue by jhy1234** [gedoor/legado#1489]
### 机型
>Samsung Galaxy Tab A 8.0 With S Pen (SM P200)

### 安卓版本（如Android 7.1.1）
>Android 11, One UI 3.1

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.010310

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带

### 问题描述（简要描述发生的问题）
>打开web服务后，如果切出阅读app界面（退到桌面或者打开别的app）则阅读app一两分钟后崩溃，
留在阅读app则没问题，如果赶在崩溃前切回阅读app也没问题

### 日志提交（问题截图或者日志）
>崩溃时会闪过这个报错信息
![photo_2022-01-02_21-27-01](https://user-images.githubusercontent.com/38813998/147898001-36e3c6f3-c7d6-4d35-a17f-db94b67c6083.jpg)

在crash文件夹里能找到log：

MANUFACTURER=samsung
versionName=3.22.010310
versionCode=9697
BRAND=samsung
java.lang.RuntimeException: Unable to stop service io.legado.app.service.WebService@ba263ff: java.lang.IllegalStateException: Not allowed to start service Intent { act=stop cmp=io.legado.app.release/io.legado.app.service.WebTileService }: app is in background uid UidRecord{75bd747 u0a267 SVC  bg:+1m0s49ms idle change:idle procs:1 seq(0,0,0)}
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4833)
	at android.app.ActivityThread.access$2000(ActivityThread.java:301)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2209)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { act=stop cmp=io.legado.app.release/io.legado.app.service.WebTileService }: app is in background uid UidRecord{75bd747 u0a267 SVC  bg:+1m0s49ms idle change:idle procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1795)
	at android.app.ContextImpl.startService(ContextImpl.java:1740)
	at android.content.ContextWrapper.startService(ContextWrapper.java:738)
	at io.legado.app.service.WebService.upTile(WebService.kt:174)
	at io.legado.app.service.WebService.onDestroy(WebService.kt:58)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4813)
	... 8 more
java.lang.IllegalStateException: Not allowed to start service Intent { act=stop cmp=io.legado.app.release/io.legado.app.service.WebTileService }: app is in background uid UidRecord{75bd747 u0a267 SVC  bg:+1m0s49ms idle change:idle procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1795)
	at android.app.ContextImpl.startService(ContextImpl.java:1740)
	at android.content.ContextWrapper.startService(ContextWrapper.java:738)
	at io.legado.app.service.WebService.upTile(WebService.kt:174)
	at io.legado.app.service.WebService.onDestroy(WebService.kt:58)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4813)
	at android.app.ActivityThread.access$2000(ActivityThread.java:301)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2209)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

### 使用书源（填写URL或者JSON）
>任意

**Comment by gedoor** [comment]
我看下

**Comment by gedoor** [comment]
下版本修复

**Comment by jhy1234** [comment]
3.22.010615版，确实app本身不会崩溃了，但是打开web服务，切出app一会儿后web服务会关闭。
而且没有crash log，就是web服务没了

**Comment by gedoor** [comment]
这个应该是后台被结束了,手机问题

**Comment by jhy1234** [comment]
好吧。多谢大佬了~辛苦啦！
