### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by QAQQIAOY** [gedoor/legado#1656]
### 机型（如Redmi K30 Pro）
>iqoo neo5

### 安卓版本（如Android 7.1.1）
>安卓12
vivo6.8.12

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.021714

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动宽带，移动数据，电信数据

### 问题描述（简要描述发生的问题）
>，用的微软封装的xiaoxiao语音，版本是0209那个。开启朗读后锁屏，只能朗读读到本章结尾，然后翻页的话从一章开头翻页是正常的，等他读完了一章，阅读的界面还在一章的中间的样子。不需要锁屏，后台也这样。新版本3.22.022623阅读也一样

### 使用书源（填写URL或者JSON）
>{
  "bookSourceComment": "登录搜索一下",
  "bookSourceGroup": "💦 精品 💦",
  "bookSourceName": "💦书海阁②",
  "bookSourceType": 0,
  "bookSourceUrl": "https://m.xinshuhaige.net/",
  "bookUrlPattern": "https?://m\\.xinshuhaige\\.net(/html)?/\\d+/?",
  "customOrder": -31726,
  "enabled": true,
  "enabledExplore": true,
  "exploreUrl": "[\n{\"title\": \"小说排行\",\"url\": \"\",\"style\": {\"layout_flexGrow\": 0,\n\"layout_flexBasisPercent\": 1\n}},\n{\"title\": \"总点击榜\",\"url\": \"/allvisit/{{page}}.html\",\n\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"月点击榜\",\"url\": \"/monthvisit/{{page}}.html\",\n\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"周点击榜\",\"url\": \"/weekvisit/{{page}}.html\",\n\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"日点击榜\",\"url\": \"/dayvisit/{{page}}.html\",\n\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"总推荐榜\",\"url\": \"/allvote/{{page}}.html\",\n\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"月推荐榜\",\"url\": \"/monthvote/{{page}}.html\",\n\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"周推荐榜\",\"url\": \"/weekvote/{{page}}.html\",\n\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"日推荐榜\",\"url\": \"/dayvote/{{page}}.html\",\n\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"总收藏榜\",\"url\": \"/goodnum/{{page}}.html\",\n\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"总字数榜\",\"url\": \"/size/{{page}}.html\",\n\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"强推榜单\",\"url\": \"/toptime/{{page}}.html\",\n\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"新书榜单\",\"url\": \"/goodnew/{{page}}.html\",\n\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"书库全部\",\"url\": \"/shuku/0_0_0_{{page}}.html\",\"style\": {\"layout_flexGrow\": 0,\n\"layout_flexBasisPercent\": 1\n}},\n{\"title\": \"都市生活\",\"url\": \"/shuku/0_1_0_{{page}}.html\",\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"现代言情\",\"url\": \"/shuku/0_2_0_{{page}}.html\",\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"古代言情\",\"url\": \"/shuku/0_3_0_{{page}}.html\",\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"青春校园\",\"url\": \"/shuku/0_4_0_{{page}}.html\",\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"玄幻奇幻\",\"url\": \"/shuku/0_5_0_{{page}}.html\",\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"武侠仙侠\",\"url\": \"/shuku/0_6_0_{{page}}.html\",\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"悬疑灵异\",\"url\": \"/shuku/0_7_0_{{page}}.html\",\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"历史军事\",\"url\": \"/shuku/0_8_0_{{page}}.html\",\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"游戏竞技\",\"url\": \"/shuku/0_9_0_{{page}}.html\",\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"科幻未来\",\"url\": \"/shuku/0_10_0_{{page}}.html\",\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"二次元い\",\"url\": \"/shuku/0_11_0_{{page}}.html\",\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"新书入库\",\"url\": \"/shuku/0_12_0_{{page}}.html\",\"style\": {\"layout_flexGrow\": 0,\n\"layout_flexBasisPercent\": 0.29\n}},\n{\"title\": \"连载更新\",\"url\": \"/shuku/0_0_1_{{page}}.html\",\"style\": {\"layout_flexGrow\": 0,\n\"layout_flexBasisPercent\": 1\n}},\n{\"title\": \"都市生活\",\"url\": \"/shuku/0_1_1_{{page}}.html\",\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"现代言情\",\"url\": \"/shuku/0_2_1_{{page}}.html\",\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"古代言情\",\"url\": \"/shuku/0_3_1_{{page}}.html\",\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"青春校园\",\"url\": \"/shuku/0_4_1_{{page}}.html\",\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"玄幻奇幻\",\"url\": \"/shuku/0_5_1_{{page}}.html\",\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"武侠仙侠\",\"url\": \"/shuku/0_6_1_{{page}}.html\",\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},\n{\"title\": \"悬疑灵异\",\"url\": \"/shuku/0_7_1_{{page}}.html\",\"style\": {\"layout_flexGrow\": 0.25,\n\"layout_flexBasisPercent\": -1\n}},

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>打开阅读，书籍，朗读，返回桌面，后台朗读
![Screenshot_20220227_174120](https://user-images.githubusercontent.com/33592341/155877213-fd46e006-630f-468e-892d-c88ac3725108.jpg)
，
![Screenshot_20220227_174115](https://user-images.githubusercontent.com/33592341/155877212-83909539-4a55-48fa-b0c2-cdee0b9755b2.jpg)
，
![Screenshot_20220227_174105](https://user-images.githubusercontent.com/33592341/155877221-68dcf637-aefe-427f-9de5-a6219c555fbe.jpg)
。读完一章就会停止朗读，书籍页面只能翻到本章一半左右，有时候会出现网络出现波动，掉线了，现在又没有。。然后就不知道在读什么，好像是重复朗读。奇怪的是k40的miui13使用没啥问题，

### 日志提交（问题截图或者日志）
>MANUFACTURER=vivo
versionName=3.22.021714
versionCode=10447
BRAND=vivo
java.lang.RuntimeException: Unable to start service io.legado.app.service.TTSReadAloudService@1f732ea with Intent { act=pause cmp=io.legado.app.release/io.legado.app.service.TTSReadAloudService }: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean s0.g.b(int, java.lang.String)' on a null object reference
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4971)
	at android.app.ActivityThread.access$2300(ActivityThread.java:284)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2304)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8333)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean s0.g.b(int, java.lang.String)' on a null object reference
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2445)
	at android.os.Parcel.createException(Parcel.java:2423)
	at android.os.Parcel.readException(Parcel.java:2406)
	at android.os.Parcel.readException(Parcel.java:2348)
	at android.speech.tts.ITextToSpeechService$Stub$Proxy.stop(ITextToSpeechService.java:824)
	at android.speech.tts.TextToSpeech.lambda$stop$7$TextToSpeech(TextToSpeech.java:1418)
	at android.speech.tts.TextToSpeech$$ExternalSyntheticLambda3.run(Unknown Source:2)
	at android.speech.tts.TextToSpeech$Connection.runAction(TextToSpeech.java:2361)
	at android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:813)
	at android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:803)
	at android.speech.tts.TextToSpeech.stop(TextToSpeech.java:1417)
	at io.legado.app.service.TTSReadAloudService.pauseReadAloud(TTSReadAloudService.kt:124)
	at io.legado.app.service.BaseReadAloudService.onStartCommand(BaseReadAloudService.kt:101)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4953)
	... 9 more
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean s0.g.b(int, java.lang.String)' on a null object reference
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2445)
	at android.os.Parcel.createException(Parcel.java:2423)
	at android.os.Parcel.readException(Parcel.java:2406)
	at android.os.Parcel.readException(Parcel.java:2348)
	at android.speech.tts.ITextToSpeechService$Stub$Proxy.stop(ITextToSpeechService.java:824)
	at android.speech.tts.TextToSpeech.lambda$stop$7$TextToSpeech(TextToSpeech.java:1418)
	at android.speech.tts.TextToSpeech$$ExternalSyntheticLambda3.run(Unknown Source:2)
	at android.speech.tts.TextToSpeech$Connection.runAction(TextToSpeech.java:2361)
	at android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:813)
	at android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:803)
	at android.speech.tts.TextToSpeech.stop(TextToSpeech.java:1417)
	at io.legado.app.service.TTSReadAloudService.pauseReadAloud(TTSReadAloudService.kt:124)
	at io.legado.app.service.BaseReadAloudService.onStartCommand(BaseReadAloudService.kt:101)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4953)
	at android.app.ActivityThread.access$2300(ActivityThread.java:284)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2304)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8333)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)

**Comment by gedoor** [comment]
看是不是什么软件杀进程了

**Comment by QAQQIAOY** [comment]
我现在两个软件自启动关联启动，后台锁定电池优化，后台允许高耗电都给了，也删除了黑域类软件，电量充足，后台清理掉只剩这俩软件，移动WiFi和电信数据移动数据又各自试了一遍，还是没用，我看只能是这手机iqooneo5机制有问题

---Original---
From: ***@***.***&gt;
Date: Mon, Feb 28, 2022 23:11 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gedoor/legado] [BUG]  (Issue #1656)




 
看是不是什么软件杀进程了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by QAQQIAOY** [comment]
单章放在后台阅读，再次打开书籍会翻页远落后于朗读内容。



---Original---
From: ***@***.***&gt;
Date: Mon, Feb 28, 2022 23:11 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gedoor/legado] [BUG]  (Issue #1656)




 
看是不是什么软件杀进程了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hujiao80** [comment]
一模一样的问题，一样的手机，阅读和TTS换了几个版本也没用，之前正常，现在最多能正常读个1、2章就停止了，手动翻个页又能往下读。
印象是在升级了ocean os之后出现的，难道真是手机的问题 ？

**Comment by QAQQIAOY** [comment]
> 一模一样的问题，一样的手机，阅读和TTS换了几个版本也没用，之前正常，现在最多能正常读个1、2章就停止了，手动翻个页又能往下读。 印象是在升级了ocean os之后出现的，难道真是手机的问题 ？

我k40 miui13也一样不能读了， 以前读个几十章都没问题

**Comment by gedoor** [comment]
奇怪,我手机上一直正常朗读

**Comment by QAQQIAOY** [comment]
> 

不知道啊为什么 也没用黑阈啥的
