### ISSUE TITLE
[BUG] 外部txt使用app关联打开时null

### ISSUE THREAD

**Issue by yiran9937** [gedoor/legado#1720]
### 机型（如Redmi K30 Pro）
>Honor V9

### 安卓版本（如Android 7.1.1）
>Android  7.0

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>最新源码安装  fa110289

### 问题描述（简要描述发生的问题）
>打开文件管理器->本地存储->选择本地txt文件->使用"阅读"打开,   "阅读" toast: null
原因：FileAssociationActivity.importBook 109L:` val name = bookDoc?.name!! ` name为空.

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>在文件管理器->选择本地ttxt文件->使用"阅读"打开, "阅读" toast: null

### 日志提交（问题截图或者日志）
>2022-03-18 16:03:36.943 21098-21098/io.legado.app.debug E/io.legado.app.ui.association.FileAssociationActivity$importBook$1: 导入书籍失败
    java.lang.NullPointerException
        at io.legado.app.ui.association.FileAssociationActivity$importBook$1$1$2.invokeSuspend(FileAssociationActivity.kt:129)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by gedoor** [comment]
试试最新测试版本
