### ISSUE TITLE
[BUG] must call this method on a background thread #1772

### ISSUE THREAD

**Issue by Xwite** [gedoor/legado#1774]
### 描述
> #1772 好像不能用error来显示加载失败的图片
### 日志提交（问题截图或者日志）
>java.lang.IllegalArgumentException: You must call this method on a background thread
	at com.bumptech.glide.util.Util.assertBackgroundThread(Util.java:179)
	at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:192)
	at com.bumptech.glide.request.RequestFutureTarget.get(RequestFutureTarget.java:130)
	at io.legado.app.ui.book.read.page.provider.ImageProvider.getImage(ImageProvider.kt:50)
	at io.legado.app.ui.book.read.page.ContentTextView.drawImage(ContentTextView.kt:170)
	at io.legado.app.ui.book.read.page.ContentTextView.drawChars(ContentTextView.kt:145)
	at io.legado.app.ui.book.read.page.ContentTextView.draw(ContentTextView.kt:112)
	at io.legado.app.ui.book.read.page.ContentTextView.drawPage(ContentTextView.kt:93)
	at io.legado.app.ui.book.read.page.ContentTextView.onDraw(ContentTextView.kt:76)
	at android.view.View.draw(View.java:22653)
	at android.view.View.updateDisplayListIfDirty(View.java:21490)
	at android.view.View.draw(View.java:22353)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4573)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
	at android.view.View.draw(View.java:22656)
	at android.view.View.updateDisplayListIfDirty(View.java:21490)
	at android.view.View.draw(View.java:22353)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4573)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
	at android.view.View.draw(View.java:22656)
	at android.view.View.updateDisplayListIfDirty(View.java:21490)
	at android.view.View.draw(View.java:22353)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4573)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
	at io.legado.app.ui.book.read.page.ReadView.dispatchDraw(ReadView.kt:128)
	at android.view.View.draw(View.java:22656)
	at android.view.View.updateDisplayListIfDirty(View.java:21490)
	at android.view.View.draw(View.java:22353)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4573)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
	at android.view.View.updateDisplayListIfDirty(View.java:21481)
	at android.view.View.draw(View.java:22353)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4573)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
	at android.view.View.updateDisplayListIfDirty(View.java:21481)
	at android.view.View.draw(View.java:22353)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4573)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
	at android.view.View.updateDisplayListIfDirty(View.java:21481)
	at android.view.View.draw(View.java:22353)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4573)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
	at android.view.View.updateDisplayListIfDirty(View.java:21481)
	at android.view.View.draw(View.java:22353)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4573)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
	at android.view.View.updateDisplayListIfDirty(View.java:21481)
	at android.view.View.draw(View.java:22353)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4573)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
	at android.view.View.draw(View.java:22656)
	at com.android.internal.policy.DecorView.draw(DecorView.java:926)
	at android.view.View.updateDisplayListIfDirty(View.java:21490)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:581)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:587)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:687)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4450)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4173)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3424)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2193)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8665)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:849)
	at android.view.Choreographer.doFrame(Choreographer.java:779)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8215)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

**Comment by Xwite** [comment]
see #1780
