### ISSUE TITLE
[BUG] java.lang.IllegalArgumentException: You must call this method on a background thread

### ISSUE THREAD

**Issue by Xwite** [gedoor/legado#1780]
## 问题描述
最新版本阅读
打开漫画源，打开调试，图片下载成功，但是解码失败，调试显示`must call this method on a background thread`

https://github.com/gedoor/legado/commit/cca075230598f91d2eb4319b57918f0c3871e496 fix
https://github.com/gedoor/legado/commit/a6e975ee572404b8e2d46f403c1724d0730606a9 drop glide 
<details>
  <summary><h2>日志</h2></summary>
 <pre><code>java.lang.IllegalArgumentException: You must call this method on a background thread
	at com.bumptech.glide.util.Util.assertBackgroundThread(Util.java:179)
	at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:192)
	at com.bumptech.glide.request.RequestFutureTarget.get(RequestFutureTarget.java:130)
	at io.legado.app.ui.book.read.page.provider.ImageProvider.getImage(ImageProvider.kt:82)
	at io.legado.app.ui.book.read.page.ContentTextView.drawImage(ContentTextView.kt:170)
	at io.legado.app.ui.book.read.page.ContentTextView.drawChars(ContentTextView.kt:145)
	at io.legado.app.ui.book.read.page.ContentTextView.draw(ContentTextView.kt:112)
	at io.legado.app.ui.book.read.page.ContentTextView.drawPage(ContentTextView.kt:93)
	at io.legado.app.ui.book.read.page.ContentTextView.onDraw(ContentTextView.kt:76)
	at android.view.View.draw(View.java:22653)
	at android.view.View.updateDisplayListIfDirty(View.java:21490)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4552)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4525)
	at android.view.View.updateDisplayListIfDirty(View.java:21445)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4552)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4525)
	at android.view.View.updateDisplayListIfDirty(View.java:21445)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4552)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4525)
	at android.view.View.updateDisplayListIfDirty(View.java:21445)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4552)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4525)
	at android.view.View.updateDisplayListIfDirty(View.java:21445)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4552)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4525)
	at android.view.View.updateDisplayListIfDirty(View.java:21445)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4552)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4525)
	at android.view.View.updateDisplayListIfDirty(View.java:21445)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4552)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4525)
	at android.view.View.updateDisplayListIfDirty(View.java:21445)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4552)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4525)
	at android.view.View.updateDisplayListIfDirty(View.java:21445)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4552)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4525)
	at android.view.View.updateDisplayListIfDirty(View.java:21445)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:581)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:587)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:687)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4450)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4173)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3424)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2193)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8665)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:849)
	at android.view.Choreographer.doFrame(Choreographer.java:779)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8215)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)</code></pre>
</details>

**Comment by gedoor** [comment]
好的,我测试一下

**Comment by gedoor** [comment]
明白了

**Comment by Xwite** [comment]
还是这样

**Comment by gedoor** [comment]
我再看下
