### ISSUE TITLE
[BUG] java.util.concurrent.ExecutionException

### ISSUE THREAD

**Issue by Xwite** [gedoor/legado#1784]
### 安卓版本（如Android 7.1.1）
>11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.22.041408

### 问题描述（简要描述发生的问题）
>#1780

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

<h3>日志提交（问题截图或者日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>
java.util.concurrent.ExecutionException: com.bumptech.glide.load.engine.GlideException: Failed to load resource
There were 2 root causes:
java.lang.RuntimeException(setDataSourceCallback failed: status = 0x80000000)
java.lang.RuntimeException(setDataSource failed: status = 0x80000000)
 call GlideException#logRootCauses(String) for more detail
	at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:217)
	at com.bumptech.glide.request.RequestFutureTarget.get(RequestFutureTarget.java:130)
	at io.legado.app.ui.book.read.page.provider.ImageProvider$getImage$2.invokeSuspend(ImageProvider.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:216)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:106)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: com.bumptech.glide.load.engine.GlideException: Failed to load resource
There were 2 root causes:
java.lang.RuntimeException(setDataSourceCallback failed: status = 0x80000000)
java.lang.RuntimeException(setDataSource failed: status = 0x80000000)
 call GlideException#logRootCauses(String) for more detail

<pre></code>
</details>

**Comment by Xwite** [comment]
use lrucache #1786
