### ISSUE TITLE
[BUG] 一些源码问题

### ISSUE THREAD

**Issue by jiyewushen** [gedoor/legado#1796]
```
 java.lang.NumberFormatException: For input string: ""
     at java.lang.Integer.parseInt(Integer.java:620)
     at java.lang.Integer.parseInt(Integer.java:643)
     at io.legado.app.model.analyzeRule.AnalyzeByJSoup$ElementsSingle.findIndexSet(AnalyzeByJSoup.kt:460)
     at io.legado.app.model.analyzeRule.AnalyzeByJSoup$ElementsSingle.getElementsSingle(AnalyzeByJSoup.kt:281)
     at io.legado.app.model.analyzeRule.AnalyzeByJSoup.getElements(AnalyzeByJSoup.kt:151)
     at io.legado.app.model.analyzeRule.AnalyzeByJSoup.getElements$app_appDebug(AnalyzeByJSoup.kt:34)
     at io.legado.app.model.analyzeRule.AnalyzeRule.getElements(AnalyzeRule.kt:313)
     at io.legado.app.model.webBook.BookList.analyzeBookList(BookList.kt:83)
     at io.legado.app.model.webBook.WebBook.searchBookAwait(WebBook.kt:60)
```
`l==""`
![image](https://user-images.githubusercontent.com/16441451/163680401-0305eb8f-03da-440e-a313-21a185efe28b.png)

```
 javax.script.ScriptException: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "1" from null (<Unknown source>#1) in <Unknown source> at line number 1
     at com.sun.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:254)
     at com.sun.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:270)
     at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:216)
     at io.legado.app.model.analyzeRule.AnalyzeRule.evalJS(AnalyzeRule.kt:651)
     at io.legado.app.model.analyzeRule.AnalyzeRule.getString(AnalyzeRule.kt:223)
     at io.legado.app.model.analyzeRule.AnalyzeRule.getString(AnalyzeRule.kt:201)
     at io.legado.app.model.analyzeRule.AnalyzeRule.getString$default(AnalyzeRule.kt:198)
     at io.legado.app.model.webBook.BookInfo.analyzeBookInfo(BookInfo.kt:142)
     at io.legado.app.model.webBook.BookList.getInfoItem(BookList.kt:146)
     at io.legado.app.model.webBook.BookList.analyzeBookList(BookList.kt:87)
     at io.legado.app.model.webBook.WebBook.searchBookAwait(WebBook.kt:60)
     at io.legado.app.model.webBook.WebBook$searchBookAwait$1.invokeSuspend(Unknown Source:18)
```

**Comment by gedoor** [comment]
这个是执行js报错啊,这个没办法,换一种写法试试

**Comment by jiyewushen** [comment]
> 这个是执行js报错啊,这个没办法,换一种写法试试

🆗
