### ISSUE TITLE
[BUG] java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by Xwite** [gedoor/legado#1865]
### 机型（如Redmi K30 Pro）
>

### 安卓版本（如Android 7.1.1）
>

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>从文件管理器中使用阅读打开不被支持的文件

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（问题截图或者日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:852)
	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:815)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:703)
	at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
	at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
	at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:452)
	at android.app.Dialog.show(Dialog.java:346)
	at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
	at io.legado.app.lib.dialogs.AndroidAlertBuilder.show(AndroidAlertBuilder.kt:144)
	at io.legado.app.lib.dialogs.AndroidDialogsKt.alert(AndroidDialogs.kt:24)
	at io.legado.app.ui.association.FileAssociationActivity.onActivityCreated$lambda-11(FileAssociationActivity.kt:92)
	at io.legado.app.ui.association.FileAssociationActivity.$r8$lambda$_55GcH3QL2AfPRXSHn3vVD2ld-k(Unknown Source:0)
	at io.legado.app.ui.association.FileAssociationActivity$$ExternalSyntheticLambda5.onChanged(Unknown Source:4)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8215)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

<pre></code>
</details>

**Comment by gedoor** [comment]
解决了
