### ISSUE TITLE
[BUG] Map.clear报错java.lang.NoClassDefFoundError: Failed resolution of: 

### ISSUE THREAD

**Issue by Xwite** [gedoor/legado#1924]
### 安卓版本
> 11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
> 3.22.0530008

### 问题描述（简要描述发生的问题）
> js Map.clear()报错 ，正式版3.22.052723没问题

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 添加下面的书源 ,然后调试

### 使用书源（填写URL或者JSON）

```json
{
  "bookSourceComment": "",
  "bookSourceName": "Map复现",
  "bookSourceType": 0,
  "bookSourceUrl": "http://baidu.cn",
  "customOrder": 0,
  "enabled": true,
  "enabledCookieJar": true,
  "enabledExplore": true,
  "lastUpdateTime": 1653881774793,
  "respondTime": 180000,
  "ruleBookInfo": {
    "init": ""
  },
  "ruleContent": {},
  "ruleExplore": {
    "bookList": ""
  },
  "ruleSearch": {
    "bookList": ""
  },
  "ruleToc": {
    "chapterList": ""
  },
  "searchUrl": "<js>\nlet a = new Map();\na.clear()\n</js>",
  "weight": 0
}
```

<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

java.lang.NoClassDefFoundError: Failed resolution of: Lj$/util/Iterator$-EL;
	at org.mozilla.javascript.Hashtable.clear(Hashtable.java:201)
	at org.mozilla.javascript.NativeMap.js_clear(NativeMap.java:139)
	at org.mozilla.javascript.NativeMap.execIdCall(NativeMap.java:72)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:100)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at com.script.javascript.RhinoScriptEngine$1.superDoTopCall(RhinoScriptEngine.java:92)
	at com.script.javascript.RhinoScriptEngine$1.doTopCall(RhinoScriptEngine.java:85)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3651)
	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:121)
	at org.mozilla.javascript.Context.evaluateReader(Context.java:1265)
	at com.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:161)
	at com.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:187)
	at com.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:79)
	at io.legado.app.model.analyzeRule.AnalyzeUrl.evalJS(AnalyzeUrl.kt:252)
	at io.legado.app.model.analyzeRule.AnalyzeUrl.analyzeJs(AnalyzeUrl.kt:117)
	at io.legado.app.model.analyzeRule.AnalyzeUrl.initUrl(AnalyzeUrl.kt:95)
	at io.legado.app.model.analyzeRule.AnalyzeUrl.<init>(AnalyzeUrl.kt:85)
	at io.legado.app.model.analyzeRule.AnalyzeUrl.<init>(AnalyzeUrl.kt:36)
	at io.legado.app.model.webBook.WebBook.searchBookAwait(WebBook.kt:44)
	at io.legado.app.model.webBook.WebBook$searchBook$1.invokeSuspend(WebBook.kt:32)
	at io.legado.app.model.webBook.WebBook$searchBook$1.invoke(Unknown Source:8)
	at io.legado.app.model.webBook.WebBook$searchBook$1.invoke(Unknown Source:4)
	at io.legado.app.help.coroutine.Coroutine$executeBlock$2.invokeSuspend(Coroutine.kt:200)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.ClassNotFoundException: j$.util.Iterator$-EL
	... 34 more

<pre></code>
</details>

**Comment by Xwite** [comment]
refs https://github.com/gedoor/legado/commit/c5b8603a7357f75536909a7a704be33087e80cd9

**Comment by Xwite** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月1日(星期三) 晚上8:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gedoor/legado] [BUG] Map.clear报错java.lang.NoClassDefFoundError: Failed resolution of:  (Issue #1924)




 
应该不是Map问题,可能是这个库的一些API改了,其它的语句出错了

**Comment by Xwite** [comment]
关键是我们只用了加密模块，js引擎部分应该没影响才对



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月1日(星期三) 晚上8:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gedoor/legado] [BUG] Map.clear报错java.lang.NoClassDefFoundError: Failed resolution of:  (Issue #1924)




 
应该不是Map问题,可能是这个库的一些API改了,其它的语句出错了

**Comment by gedoor** [comment]
那就先不更新这个库了

**Comment by Xwite** [comment]
#2115 测试通过
