### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by JackiePenghe** [gedoor/legado#2265]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>redmi9

### 安卓版本（如Android 7.1.1）
>
11

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>

3.22.083120
### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>
 加载某个章节的时候出现了崩溃

### 相关截图
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

MANUFACTURER=Xiaomi
versionName=3.22.083120
versionCode=12105
BRAND=Redmi
java.lang.OutOfMemoryError: Failed to allocate a 144 byte allocation with 0 free bytes and 0B until OOM, target footprint 268435456, growth limit 268435456
	at android.widget.TextView.<init>(TextView.java:1011)
	at android.widget.TextView.<init>(TextView.java:990)
	at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:108)
	at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:103)
	at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:201)
	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:121)
	at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1569)
	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1620)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1069)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:999)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:963)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1142)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1103)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:684)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
	at io.legado.app.databinding.ItemBookSourceBinding.inflate(ItemBookSourceBinding.java:77)
	at io.legado.app.ui.book.source.manage.BookSourceAdapter.getViewBinding(BookSourceAdapter.kt:82)
	at io.legado.app.ui.book.source.manage.BookSourceAdapter.getViewBinding(BookSourceAdapter.kt:30)
	at io.legado.app.base.adapter.RecyclerAdapter.onCreateViewHolder(RecyclerAdapter.kt:346)
	at io.legado.app.base.adapter.RecyclerAdapter.onCreateViewHolder(RecyclerAdapter.kt:20)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4085)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3849)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
	at android.view.View.layout(View.java:23361)
	at android.view.ViewGroup.layout(ViewGroup.java:6534)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23361)
	at android.view.ViewGroup.layout(ViewGroup.java:6534)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23361)
	at android.view.ViewGroup.layout(ViewGroup.java:6534)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23361)
	at android.view.ViewGroup.layout(ViewGroup.java:6534)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23361)
	at android.view.ViewGroup.layout(ViewGroup.java:6534)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23361)
	at android.view.ViewGroup.layout(ViewGroup.java:6534)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23361)
	at android.view.ViewGroup.layout(ViewGroup.java:6534)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:804)
	at android.view.View.layout(View.java:23361)
	at android.view.ViewGroup.layout(ViewGroup.java:6534)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3702)
	at android.view.ViewRootI
<pre></code>
</details>

**Comment by 821938089** [comment]
单章字数过多，加载不了
