### ISSUE TITLE
[BUG] 最新版更新完闪退

### ISSUE THREAD

**Issue by iyhkhtrk** [gedoor/legado#2357]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>vivo Y3

### 安卓版本（如Android 7.1.1）
>
Android 9

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>
最新

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>

### 相关截图
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>
MANUFACTURER=vivo
versionName=3.22.100118
versionCode=12445
BRAND=vivo
java.lang.RuntimeException: Unable to find any Cronet provider. Have you included all necessary jars?
	at org.chromium.net.CronetEngine$Builder.getEnabledCronetProviders(CronetEngine.java:60)
	at org.chromium.net.CronetEngine$Builder.createBuilderDelegate(CronetEngine.java:10)
	at org.chromium.net.CronetEngine$Builder.<init>(CronetEngine.java:1)
	at org.chromium.net.ExperimentalCronetEngine$Builder.<init>(ExperimentalCronetEngine.java:1)
	at a6.b$a.invoke(CronetHelper.kt:4)
	at a6.b$a.invoke(CronetHelper.kt:18)
	at u9.l.getValue(LazyJVM.kt:21)
	at a6.c.intercept(CronetInterceptor.kt:30)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:155)
	at z5.c$c$a.intercept(HttpHelper.kt:52)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:155)
	at i6.c$o$a.intercept(WebDav.kt:52)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:155)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:114)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:34)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

<pre></code>
</details>

**Comment by iyhkhtrk** [comment]
@Xwite 
![Screenshot_2022_1001_202745](https://user-images.githubusercontent.com/104120418/193409689-48ed616e-b1e9-4ffc-a85d-6fa987ced9c4.png)
![Screenshot_2022_1001_202812](https://user-images.githubusercontent.com/104120418/193409695-46e02d1b-aa5c-4fae-ae0b-0934b51b70ed.jpg)
