### ISSUE TITLE
[BUG] cronet

### ISSUE THREAD

**Issue by iyhkhtrk** [gedoor/legado#2358]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>

### 安卓版本（如Android 7.1.1）
>

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>最新

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>

### 相关截图
>
![Screenshot_2022_1001_211335](https://user-images.githubusercontent.com/104120418/193411336-80343d0d-fa6e-4894-8630-c087e1cb5c31.png)
![Screenshot_2022_1001_211402](https://user-images.githubusercontent.com/104120418/193411341-c26c956d-b890-40ca-9eab-ec6c1a78441b.jpg)

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>

**Comment by Xwite** [comment]
覆盖安装的吗?我全新安装没报错

**Comment by iyhkhtrk** [comment]
打开croent后，杀掉后台重新进才会出现，全新的也是

**Comment by Xwite** [comment]
加个这个?
-keep class org.chromium.** {
    native <methods>;
}

**Comment by Xwite** [comment]
#2362

**Comment by iyhkhtrk** [comment]
最新版cronetEngine初始化失败
`java.lang.RuntimeException: Field userAgent_ for org.chromium.net.p not found. Known fields are [public static final org.chromium.net.p org.chromium.net.p.e, public static volatile com.google.protobuf.s$b org.chromium.net.p.g]
	at com.google.protobuf.p0.x(MessageSchema.java:63)
	at com.google.protobuf.p0.u(MessageSchema.java:52)
	at com.google.protobuf.p0.t(MessageSchema.java:13)
	at com.google.protobuf.x0.a(Protobuf.java:136)
	at com.google.protobuf.s$a.d(GeneratedMessageLite.java:26)
	at org.chromium.net.impl.CronetUrlRequestContext.d(CronetUrlRequestContext.java:190)
	at org.chromium.net.impl.CronetUrlRequestContext.<init>(CronetUrlRequestContext.java:128)
	at org.chromium.net.impl.k0.a(NativeCronetEngineBuilderImpl.java:15)
	at org.chromium.net.g$a.a(ExperimentalCronetEngine.java:69)
	at io.legado.app.lib.cronet.CronetHelperKt$a.invoke(CronetHelper.kt:19)
	at io.legado.app.lib.cronet.CronetHelperKt$a.invoke(CronetHelper.kt:22)
	at k6.m.getValue(LazyJVM.kt:21)
	at io.legado.app.lib.cronet.CronetHelperKt.getCronetEngine(CronetHelper.kt:3)
	at io.legado.app.lib.cronet.CronetInterceptor.intercept(CronetInterceptor.kt:28)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
	at io.legado.app.help.http.f.intercept(R8$$SyntheticClass:66)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:113)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:34)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
`
