### ISSUE TITLE
[BUG] 最新版本正则报错

### ISSUE THREAD

**Issue by iyhkhtrk** [gedoor/legado#2450]
### 浏览器版本（web端反馈，先勾选浏览器，然后填版本号）
* [ ] Chrome/Edge/Firefox PC
* [ ] Chrome/Edge/Firefox/WebView Android
* [ ] 其他浏览器，请补充
>

### 机型（如Redmi K30 Pro）
>

### 安卓版本（如Android 7.1.1）
>

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>

### 相关截图
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 使用书源（填写URL或者JSON）
<details>
 <summary>点击展开</summary>
 <pre><code>

<pre></code>
</details>
<h3>日志提交（我的-关于-崩溃日志，书架-右上角-日志）</h3>
<details>
 <summary>点击展开</summary>
 <pre><code>
j4.k: error parsing regexp: invalid or unsupported Perl syntax: `(?!`
	at j4.j.a(Pattern.java:60)
	at j4.j.compile(Pattern.java:21)
	at fd.t0.x(StateFlow.kt:35)
	at io.legado.app.data.entities.BookChapter.getDisplayTitle(BookChapter.kt:115)
	at io.legado.app.data.entities.BookChapter.getDisplayTitle$default(BookChapter.kt:17)
	at io.legado.app.ui.book.toc.ChapterListAdapter$b$b.invokeSuspend(ChapterListAdapter.kt:110)
	at fa.a.resumeWith(ContinuationImpl.kt:9)
	at cd.r0.run(DispatchedTask.kt:119)
	at hd.g.run(LimitedDispatcher.kt:13)
	at id.j.run(Tasks.kt:3)
	at id.a$b.run(CoroutineScheduler.kt:82)

<pre></code>
</details>

**Comment by iyhkhtrk** [comment]
好像不支持断言

**Comment by gedoor** [comment]
改回原来的了
