### ISSUE TITLE
[求助] 越来越多网站给 搜索页 添加人机验证 (Cloudflare CDN 的 hCaptcha)，这种该怎么写书源规则？

### ISSUE THREAD

**Issue by XIU2** [gedoor/legado#2507]
最近发现我自己写的书源里几乎有一半小说网站都专门给 **搜索页** 加了个**人机验证**（都是 Cloudflare CDN 的 hCaptcha）。

这种情况下，后台访问显然无法通过 CDN 的人机验证，即使用 webView 也不行。

> 这些网站都是最近陆陆续续开始加**人机验证**的，越来越多了，都是只针对 **搜索页**，其他页面都没有，显然是针对《阅读》的。
> 这些网站应该都有同行交流群？估计很快，其他同类网站有样学样都会开始这么干，普及开来后，到时候岂不是只能用用 API 书源了，这制作门槛/限制就高多了。。。

### 随便举几个例子：

- https://www.wcxsw.org
- https://www.siluke.com
- https://www.sbooktxt.com
- https://www.ddxs.com
- https://m.ddxs.com

****

有没有大佬知道怎么解决的？
目前见到过一个解决方法，但是每次搜索都要手动通过一次验证码（通过后短时间内不用再次验证，但即使这样也代表每天都会遇到），感觉也太麻烦了，似乎还只能用于手机版网页，而且搜索时间太慢，还有概率失败。。。

有没有更好的方案？

`searchUrl` 内容是：
``` JavaScript
@js:
url='搜索地址';
option={"body":"keyword="+key,"method":"POST","webView":true};
option.headers={"User-Agent":"Mozilla/5.0 (Linux; Android 12; Nexus 5X Build/NRD90M); wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Mobile Safari/537.36"};
java.put('url',String(url+','+JSON.stringify(option)))
```

`bookList` 内容是：
``` JavaScript
@js:
path='搜索结果列表选择器';
u=java.get('url');
c=java.getElement(path);
s=()=>{java.setContent(java.ajax(u));
c=java.getElement(path)};
!c.length||s();!src.includes('no-js')||eval("cookie.removeCookie(source.getKey());java.startBrowserAwait(u,'ver');s()");
c
```

**Comment by 821938089** [comment]
这种人机验证阅读没办法自动通过，只能手动来。
这些加了人机验证的应该都是同一家的站点，资源是一样的，给他写一个规则就够了。
还有这个规则应该是可以不用写使用webView的，这样就会快很多。
startBrowserAwait会保存cookie并返回网页内容，不需要再请求一次，又可以快一些。
按道理这个人机通过之后一段时间内cookie都是有效的，不需要反复验证，可能是过期时间太短了。

我看着改了一下，你可以试试：

`searchUrl `内容是：
```js
@js:
url='搜索地址';
option={"body":"keyword="+key,"method":"POST"};
option.headers={"User-Agent":"Mozilla/5.0 (Linux; Android 12; Nexus 5X Build/NRD90M); wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Mobile Safari/537.36"};
java.put('url',String(url+','+JSON.stringify(option)))
```

`bookList `内容是：
```js
@js:
path='搜索结果列表选择器';
u=java.get('url');
c=java.getElement(path);
if (!c.length && result.includes('no-js')) {
  cookie.removeCookie(source.getKey());
  res = java.startBrowserAwait(u,'ver')
  java.setContent(res.body)
  c=java.getElement(path);
}
```

**Comment by XIU2** [comment]
我测试，获取不到搜索结果列表。。。
不是手机弹出验证码网页，通过后（已显示 搜索结果网页），点右上角的 ` √ ` 对号就行了么？我点完之后自动返回了调试界面，有时候是还在转圈，有时候则是直接输出 获取书籍列表为空... 

另外，我连续多次测试后，发现人机验证过不去了。。。似乎**陷入死循环**了，网页一直在验证、重定向、验证、重定向。。。
另外，`enabledCookieJar` 要不要开？

``` json
{
    "bookSourceComment": "",
    "bookSourceGroup": "",
    "bookSourceName": "顶点小说 ddxs - 手机版",
    "bookSourceType": 0,
    "bookSourceUrl": "https://m.ddxs.com",
    "bookUrlPattern": "",
    "concurrentRate": "",
    "customOrder": 17,
    "enabled": true,
    "enabledCookieJar": true,
    "enabledExplore": true,
    "enabledReview": false,
    "exploreUrl": "玄幻小说::/xuanhuan/\n武侠小说::/wuxia/\n军事小说::/junshi/\n都市小说::/dushi/\n游戏小说::/youxi/\n科幻小说::/kehuan/\n言情小说::/yanqin/\n次元小说::/ciyuan/\n完本小说::/quanben/",
    "header": "",
    "lastUpdateTime": 1667193051280,
    "loginCheckJs": "",
    "loginUi": "",
    "loginUrl": "",
    "respondTime": 180000,
    "ruleBookInfo": {
        "author": "class.book_info@class.book_box@class.xx@dl@dd.0@text##作者：",
        "coverUrl": "class.book_info@class.book_box@class.fm@img@src",
        "intro": "class.book_info@class.book_box.1@text",
        "name": "class.book_info@class.book_box@class.xx@dl@dt@text",
        "tocUrl": "class.book_more@a@href"
    },
    "ruleContent": {
        "content": "id.nr@html",
        "replaceRegex": "##@@.*@@@|正在手打中.*更新！|点击下载本站APP.*免费畅读！|\\+ 加入书签 \\+"
    },
    "ruleExplore": {
        "author": "class.author@text",
        "bookList": "class.hot_sale",
        "bookUrl": "tag.a@href",
        "coverUrl": "tag.img@src",
        "intro": "class.longview@text",
        "name": "class.title@text"
    },
    "ruleReview": {},
    "ruleSearch": {
        "author": "textNodes##/ ",
        "bookList": "@js:\npath = 'class.cover@p';\nu=java.get('url');\nc=java.getElement(path);\nif (!c.length && result.includes('no-js')) {\n  cookie.removeCookie(source.getKey());\n  res = java.startBrowserAwait(u,'ver')\n  java.setContent(res.body)\n  c=java.getElement(path);\n}",
        "bookUrl": "a@href",
        "kind": "span@text##\\[|\\]",
        "name": "a@text"
    },
    "ruleToc": {
        "chapterList": "class.list-striped@dd",
        "chapterName": "text",
        "chapterUrl": "a@href"
    },
    "searchUrl": "@js:\nurl = 'https://m.ddxs.com/search.php';\noption={\"body\":\"keyword=\"+key,\"method\":\"POST\"};\noption.headers={\"User-Agent\":\"Mozilla/5.0 (Linux; Android 12; Nexus 5X Build/NRD90M); wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Mobile Safari/537.36\"};\njava.put('url',String(url+','+JSON.stringify(option)))",
    "weight": 0
}
```

基于这个修改的： https://github.com/XIU2/Yuedu/issues/59#issuecomment-1278962681

**Comment by 821938089** [comment]
startBrowserAwait有点bug，刚刚修了
还有java.setContent(res.body()) ，这里的body是个函数，要调用一下，这里改一下
刚刚加了个cloudflare人机验证页面通过后自动关闭的功能
测试版等会就会构建出来，你一会可以试试

**Comment by XIU2** [comment]
我安装最新测试版，改为了 `java.setContent(res.body())`，调试试了下，人机验证页面通过后确实自动关闭了，不过还是获取不到搜索结果列表。。。

我看人机验证页面通过后跳转到搜索结果页并自动关闭时的那一瞬间，似乎小说网站的 搜索结果页 还没加载完成的样子（即只显示了网页头部内容，下面都是空白），不过也有几次可以明显看到网页内容完整显示出来了，但依然获取不到列表。

我用的选择器 `class.cover@p` 好像没啥毛病呀。。。

另外，我在阅读搜索栏里搜索试了几次，发现每次都需要过人机验证（这就有点蛋疼了），而我电脑浏览器模拟手机去访问则通过一次后短时间内都不会再提示验证了。。。

搞不懂，不知道该如何排查问题。

**Comment by 821938089** [comment]
你把书源发出来我试一下

**Comment by 821938089** [comment]
我这里是可以用的啊
你java.log(res.body())看一下是什么

**Comment by XIU2** [comment]
是加在 bookList 里面吗？我加到了这里：

```
@js:
path = 'class.cover.0@tag.p';
u=java.get('url');
c=java.getElement(path);
if (!c.length && result.includes('no-js')) {
  cookie.removeCookie(source.getKey());
  res = java.startBrowserAwait(u,'ver')
  java.setContent(res.body())
java.log(res.body())
  c=java.getElement(path);
}
```

调试结果，看起来是 Cloudflare CDN 的人机验证网页源码，而非 搜索结果页的。

```
[00:00.001] ⇒开始搜索关键字:黑科技
[00:00.001] ︾开始解析搜索页
[00:00.824] ≡获取成功:https://m.ddxs.com/search.php,{"body":"keyword=黑科技","method":"POST","headers":{"User-Agent":"Mozilla/5.0 (Linux; Android 12; Nexus 5X Build/NRD90M); wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Mobile Safari/537.36"}}
[00:00.826] ┌获取书籍列表
[00:16.496] <!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">
    

</head>
<body class="no-js">
    <div class="main-wrapper" role="main">
    <div class="main-content">
        <h1 class="zone-name-title h1">
            <img class="heading-favicon" src="/favicon.ico"
                 onerror="this.onerror=null;this.parentNode.removeChild(this)">
            m.ddxs.com
        </h1>
        <h2 class="h2" id="challenge-running">
            Checking if the site connection is secure
        </h2>
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
        </noscript>
        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/managed/nojs/transparent.gif?ray=762b5ed05b5a7bbc')"></div>
        <div id="challenge-body-text" class="core-msg spacer">
            m.ddxs.com needs to review the security of your connection before proceeding.
        </div>
        <form id="challenge-form" action="/search.php?__cf_chl_f_tk=mrLYN8HY3YoG_Ffj0RyQUQ2laCCQpxK3p4a6ocBYSTk-1667208609-0-gaNycGzNBlE" method="POST" enctype="application/x-www-form-urlencoded">
            <input type="hidden" name="md" value="6lKjaw.YDPMqdDPLCFcYXlEjchdcbZEQ4XKB1cimtLs-1667208609-0-AXwqDS3p1T83i377meYQBu-iKKBClwNoEW8bFkhOtj4638cSJPzgnBT9Y4I0Y51EkmfQpZmL0Xv9drRIbHSQ_cQNvsz3lQFmabhi7mAcaUFLOQXIx6pvf77n2Mm1nrUXOg1uTFN-hVEfm8S-wcu9Q2-huYcWdr7T01zp9eZlFowI4qdrCvWkQTk_Hhm3yqMsab8yNDlcoAlpw54V4xAaPiZT-lAaxmCB8Q1-GeDKMDJkPk4PCUSdTVqXDS4oMRpJX2ntnhmPQrgrPUTwVQNmSb3ax0oQlvAyLYZlTgXk76ZVWBafg6fwilsx3gs2nxFee_uNLGuwNYUyNLeuVOYYhg582WiiGI-b8IhaCutarnYrfAIRI48A_VbqtC17z1gfSKp_zLSE394QGSVtdWuk2vngG5tQEFQTsZPFSl3qanKc4McGoEgqo2ZOYl2csbYDZkKc1bBnB2VlqqJjjODp7VYRyO0io0wT935cbQfsqOv-VbCk3Eb694Us4wPxRl1ItiYaHXw-OR21CqAtYlJZijeHBKIjN2lLOL824DKiayGGSoc0QAxCy7Qu9vmZQMMROQ_NrvkRE5Do00Qg3OXrljMcwQe-fj9y_KtwZfmnvSRnSG56ou1L46uG-S8Xu4blVAnCXBztRkgV73J3e0r_lMgEV2f4w3tvbsxXBEAlUTF8">
            <input type="hidden" name="r" value="9nIVJwZEKtEETDmIWa00xN_SeCBSjWMRTPEyJvo8aaE-1667208609-0-AVso4gVe9OnA1J9z1mrmQL9cDwWRP8SIqa+LKS8ie6tAXCRNxQKdErSkDZKreyZdUMqua4c7nkTXNYN6EJWyITbxHf2qZjPS8gkAFS2VvMg0tMoJgw5LSa53SEPQ21/rvAZafSUEZxVo2HcqXHymybiO6svmKyoKM1+UYFUzl3DlZC04xga9iTbask/KQaM37Y5nb19MISUFtfyxszhqiJgUDRlHt8KhOVGLb1lXmgHBjORjocY60x64jx7xqdj5iHqrRVVbgUPN/JWoSbc/03BYAOx2IWXsq9LsFyZWf35B2KmiwMNOEGHKXq8/H0gSEdEk5mGzirrckooz5njPf4oFOr+x8sgSBy4WvjDKWkBv6Wgl/fPiF6JimJz2hrTL6KaVAheD19fBBchruK1VpoHvSXLRwtZVCmvgrj6JuzdIR7B3nVqreZLRa7L3Nwe8VVWXiswUYmIuhHFG+fdHyJgHG31FP2MY5/ZqWhvuJh34hqensUXFi83lgVN0g31ZxMqJund1pmjI3oz8uczDOSxCA0EyrOg1Js+lJT7GCG7Ol/AjvwE9+vQOnfYFIUHqMpvjn6YtanA3GP38psYpehmLTVrNjyNlflGMsfqyNh98aKXeWs+jyDIQCAULi8ShzIBOLG1NgiQOHJrbz9T+bun1vCF2vpcy8xWYLlP7TM6+1zODXYjBMcue9HuzcbqYnoU69mQcQeIg8M2xvdZd1is37RGL93THBsDK0zp7hNiy7bu0uX0Nv3sG6YNHO/gIL0n2rhlXUWimuykCvWJqhBuHtK5S+oJ2R2bk4PUyQXln4fReismeQfoTQeVliP0hqitD1lBCCDHvyeGXLk9n7EYYCTr7OPEiHLxsNw3SNZIzVuVJ/HWmc9kqm8OpSEorQ98upcVHb6BQ1Me2yzPTGrC08u2exN52lGhwBRNYm/EvGXpNSNFaXpVVUyhlxTkokKw5tiHVT71EK8ErhmSlkZOO2litQCuGUT5adrdDfK7QnMio6YJn0/VHkAaLtXx16HFK7N7wWU7C5jj08d/aVEoVtzHQtYEdyJslf5AAyIO9twvEw7BFocWcSL19757a4HYXh+kMA8ZnyubBnPY2hFF21eWRmoPwIxTHlgLusw7zX8pwsPQkk0QfKgrcIVwco1aIsnb1lqiovw8vRsPzhs5C93kviuuNSyBLw56JNdSi09BSvQpWDnEq7pXfjbhh5R1mmS7K5nXtnmAu1e5dZzyNuXZbqKEYYvX2kKsILJGZVuQO025m8rciflIEQrt6nLytD6hEoCjzExbPCNYuqxXuREl1TKcWWW/qLkSMMnBrs14KIu38ObqiPLnni94jrlHhUy2NlXPHsMk8bcBgaDoDQZbjq6LwzxrnlDDtwHT/AqPSWud4nFgV8uBGKIqgzoL8v6t4+uLL1gTgo8RgYELlcSOSfMV0dr5BDLc6ZlqkXrd9oSlDeDGI+59SWju4J1YiWTJRbJndAjUD3zbcZ/TnawGifEx9eJvCjd24Zl7hvqCI7wZxU+mNBB52FEMJRDvMjjTuYssjxhoQfLlje78=">
        </form>
    </div>
</div>
<script>
    (function(){
        window._cf_chl_opt={
            cvId: '2',
            cType: 'managed',
            cNounce: '47211',
            cRay: '762b5ed05b5a7bbc',
            cHash: 'face71ae92e146a',
            cUPMDTk: "\/search.php?__cf_chl_tk=mrLYN8HY3YoG_Ffj0RyQUQ2laCCQpxK3p4a6ocBYSTk-1667208609-0-gaNycGzNBlE",
            cFPWv: 'b',
            cTTimeMs: '1000',
            cTplV: 4,
            cTplB: 'cf',
            cRq: {
                ru: 'aHR0cHM6Ly9tLmRkeHMuY29tL3NlYXJjaC5waHA=',
                ra: 'TW96aWxsYS81LjAgKExpbnV4OyBBbmRyb2lkIDEyOyBOZXh1cyA1WCBCdWlsZC9OUkQ5ME0pOyB3dikgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgVmVyc2lvbi80LjAgQ2hyb21lLzk2LjAuNDY2NC4xMDQgTW9iaWxlIFNhZmFyaS81MzcuMzY=',
                rm: 'UE9TVA==',
                d: 'DdytyvXM1JdtxCdZeC7Q0u+EQWaWybPBVAUfh03wyNlkw9MUeCn4HrswA1bHPYKb5oP5OGFvv5hH85XF8ewRYK6pMYiLjMJNjXETjPRWcnFjUoWxmcAdG4/fRjJkFdBe062lneGw0/FWAxCdeLdfaRO+CkqdqrReZ2PwAod/I6LXrDUKD6/X7Bcyx2vXa8mX7qQgI7/F2ikYxQpCvOdt5DWELtC8SLZaqyHiuPU2Bv8MPEmbgfzpSaK0VlNf6YMZhXda3/NLsulLmrVp2xdpYwq168pFexAvCVDca+whsI21UBaMZmMx8GDqq6zy0Tl6PvKODtb8hYWD7GcbjBfm8PfAPpwGsziqOhQXJV/mvuV4/bKQTX6ywZb3u7SajZhMeNeB6jmghzrOk1izCIjqo/Ha78KDny73GhbfVVehWSnV5m8xoaaDRsDfmDE0Pf4lNdfer1j2wfAeOY8ngrZbeiyhG92+0bcCIpiPkdsN4Uh09xMmWjc/l5Pp7G6C44VUD/wVXO9MQaVB1fx8iunyhUlutI5mwJJ6GUZsklY0kE4367rv5zzjS485CLuZwVLqRr2cv/+fQIpOKoE2KSYWam90O5xVLbEX9T9OaI7jSgHWd9PXIMNDysiBJ85og8p5TixMhjc0aUU7MsSGtrpPqoC4Ao/2OQu8dGv4/kaORso=',
                t: 'MTY2NzIwODYwOS4zMzUwMDA=',
                m: '6/Rs9Cz3Cqu2bgXEIR172PiRD5/3pWF/cNMqYmRNYYA=',
                i1: 'Nw3pUr3/YsglCC7835nJOA==',
                i2: '4bFtyoaDM7T/zroPwx9JJA==',
                zh: 'lswr5PSHlJbwUYS1DBhe5jdhYEv5AaxiTTypX2+3dMk=',
                uh: '7i0VDf0l4cCp0qk9bX4RX5jY33aWlb38kxFYsvsOUSw=',
                hh: '4cVcR0Up12HWPkc8mrXIWn6xKSHKqqarzO4Mh/1O2sw=',
            }
        };
        var trkjs = document.createElement('img');
        trkjs.setAttribute('src', '/cdn-cgi/images/trace/managed/js/transparent.gif?ray=762b5ed05b5a7bbc');
        trkjs.setAttribute('style', 'display: none');
        document.body.appendChild(trkjs);
        var cpo = document.createElement('script');
        cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/managed/v1?ray=762b5ed05b5a7bbc';
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, -window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;
        if (window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/search.php?__cf_chl_rt_tk=mrLYN8HY3YoG_Ffj0RyQUQ2laCCQpxK3p4a6ocBYSTk-1667208609-0-gaNycGzNBlE" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
                history.replaceState(null, null, ogU);
            };
        }
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
</script>


    <div class="footer" role="contentinfo">
        <div class="footer-inner">
            <div class="clearfix diagnostic-wrapper">
                <div class="ray-id">Ray ID: <code>762b5ed05b5a7bbc</code></div>
            </div>
            <div class="text-center">Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com?utm_source=challenge&utm_campaign=m" target="_blank">Cloudflare</a></div>
        </div>
    </div>
</body>
</html>

[00:16.502] └列表为空,按详情页解析
[00:16.503] ┌获取书名
[00:16.504] └
[00:16.504] ┌获取作者
[00:16.506] └
[00:16.506] ┌获取分类
[00:16.506] └
[00:16.506] ┌获取字数
[00:16.506] └
[00:16.506] ┌获取最新章节
[00:16.507] └
[00:16.507] ┌获取简介
[00:16.508] └
[00:16.508] ┌获取封面链接
[00:16.510] └
[00:16.510] ┌获取目录链接
[00:16.511] └https://m.ddxs.com/search.php
[00:16.518] ︽未获取到书籍
调试已关闭！

```

**Comment by 821938089** [comment]
java.log("cookies: " + java.getCookie(source.getKey()))
加一句这个，看看有没有cookies获取到

**Comment by XIU2** [comment]
```
@js:
path = 'class.cover.0@tag.p';
u=java.get('url');
c=java.getElement(path);
if (!c.length && result.includes('no-js')) {
  cookie.removeCookie(source.getKey());
  res = java.startBrowserAwait(u,'ver')
  java.setContent(res.body())
  c=java.getElement(path);
java.log(res.body())
java.log("cookies: " + java.getCookie(source.getKey()))
}
```

好像报错了。。。

```
...(和前面一样)
 [00:55.923] cookies:
 [00:55.935] java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at io.legado.app.model.analyzeRule.AnalyzeRule.getElements(AnalyzeRule.kt:172)
	at w6.h.a(BookList.kt:463)
	at w6.m.n(WebBook.kt:270)
	at w6.m$g.invokeSuspend(WebBook.kt)
	at ka.a.resumeWith(ContinuationImpl.kt:9)
	at hd.m2.i0(CoroutineContext.kt:54)
	at hd.a.resumeWith(AbstractCoroutine.kt:23)
	at ka.a.resumeWith(ContinuationImpl.kt:41)
	at hd.r0.run(DispatchedTask.kt:119)
	at md.g.run(LimitedDispatcher.kt:13)
	at nd.j.run(Tasks.kt:3)
	at nd.a$b.run(CoroutineScheduler.kt:82)
```

**Comment by 821938089** [comment]
你这个看起来cookies没有获取到

c=java.getElement(path)要写到最后面，这个是执行的结果
![image](https://user-images.githubusercontent.com/8674809/198979083-af44966f-b460-4798-acb7-f753de58805b.png)

**Comment by 821938089** [comment]
你手机的webview版本是多少？
试一下升级到最新版

**Comment by XIU2** [comment]
我给改成这样了 ，确实不报错了，虽然依然获取不到。。。

```
...
  java.setContent(res.body())
java.log(res.body())
java.log("cookies: " + java.getCookie(source.getKey()))
java.getElement(path);
}
```

我查查我的 webview 版本号是多少，我手机系统好些年没升级过了（还是安卓 7.1.2）。。。
我研究下怎么更新 webview  版本。

**Comment by XIU2** [comment]
似乎还是不行，我装了个 107.0.5304.91 版本的，我看调试结果还是一样，也不知道到底走没走这个最新版本的 WebView。。。

> 我装的是适用于 Android 7.0+ 的 armeabi-v7a 版本，apkpure 网页版下载会强制变成了 apkpure 安装包，我去酷安评论区找的该安装包。。。折腾了半天

**Comment by 821938089** [comment]
你重启一下手机再试试

**Comment by XIU2** [comment]
吐血，我这台老魅族手机似乎是没办法更新 WebView 了，魔改太厉害了，网上查了 flyme 更新 WebView 教程要么不考虑要么不适用于我，直接进系统改包名什么的又容易变砖，我还是不折腾了。

既然你测试可用，排查到问题是出在我手机 WebView 上，那就算该问题解决了吧~

做个总结，研究半天得到的目前可用方案为，其他也在找该问题解决方法的人可以参考下：
- `searchUrl` 内容是：

```
@js:
url = '搜索地址 完整 URL';
option={"body":"keyword="+key,"method":"POST"};
option.headers={"User-Agent":"Mozilla/5.0 (Linux; Android 12; Nexus 5X Build/NRD90M); wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Mobile Safari/537.36"};
java.put('url',String(url+','+JSON.stringify(option)))
```
- `bookList` 内容是：
```
@js:
path = '搜索结果 列表 选择器';
u=java.get('url');
c=java.getElement(path);
if (!c.length && result.includes('no-js')) {
  cookie.removeCookie(source.getKey());
  res = java.startBrowserAwait(u,'ver')
  java.setContent(res.body())
  java.getElement(path);
}
```

**Comment by XIU2** [comment]
对了，上面这个方案似乎只能用于手机版网页的。

如果可以的话，你顺便帮我测试一下电脑版网页是否可行：

``` json
{
    "bookSourceComment": "",
    "bookSourceGroup": "",
    "bookSourceName": "顶点小说 ddxs",
    "bookSourceType": 0,
    "bookSourceUrl": "https://www.ddxs.com",
    "bookUrlPattern": "",
    "concurrentRate": "",
    "customOrder": 16,
    "enabled": false,
    "enabledCookieJar": false,
    "enabledExplore": false,
    "enabledReview": false,
    "exploreUrl": "玄幻小说:https://www.ddxs.com/xuanhuan/\n武侠小说:https://www.ddxs.com/wuxia/\n军事小说:https://www.ddxs.com/junshi/\n都市小说:https://www.ddxs.com/dushi/\n游戏小说:https://www.ddxs.com/youxi/\n科幻小说:https://www.ddxs.com/kehuan/\n言情小说:https://www.ddxs.com/yanqin/\n次元小说:https://www.ddxs.com/ciyuan/\n排行榜:https://www.ddxs.com/top/\n完本小说:https://www.ddxs.com/quanben/",
    "header": "",
    "lastUpdateTime": 1667212779278,
    "loginCheckJs": "",
    "loginUi": "",
    "loginUrl": "",
    "respondTime": 180000,
    "ruleBookInfo": {
        "author": "//meta[@name='og:novel:author']/@content",
        "coverUrl": "//meta[@property='og:image']/@content",
        "intro": "//meta[@property='og:description']/@content",
        "kind": "//meta[@name='og:novel:category']/@content",
        "lastChapter": "//meta[@name='og:novel:latest_chapter_name']/@content",
        "name": "//meta[@name='og:novel:book_name']/@content"
    },
    "ruleContent": {
        "content": "@css:#contents>p:not([style])@text"
    },
    "ruleExplore": {
        "author": "class.author@text##｜.*",
        "bookList": "class.g-plate@ul@li",
        "bookUrl": "class.img@href",
        "coverUrl": "class.img@img@data-src",
        "intro": "class.desc@text",
        "kind": "class.author@text##.*｜",
        "name": "h2@text"
    },
    "ruleSearch": {
        "author": "tag.td.3@text",
        "bookList": "@js:\npath = 'tag.tbody.0@tag.tr.!0';\nu=java.get('url');\nc=java.getElement(path);\nif (!c.length && result.includes('no-js')) {\n  cookie.removeCookie(source.getKey());\n  res = java.startBrowserAwait(u,'ver')\n  java.setContent(res.body())\njava.log(res.body())\njava.log(\"cookies: \" + java.getCookie(source.getKey()))\njava.getElement(path);\n}",
        "bookUrl": "tag.td.1@tag.a.0@href",
        "kind": "tag.td.0@text",
        "lastChapter": "tag.td.2@text",
        "name": "tag.td.1@text"
    },
    "ruleToc": {
        "chapterList": "id.at.-1@tag.tbody@tag.td@a",
        "chapterName": "text",
        "chapterUrl": "href"
    },
    "searchUrl": "@js:\nurl = 'https://www.ddxs.com/search.php';\noption={\"body\":\"keyword=\"+key,\"charset\":\"UTF-8\",\"method\":\"POST\"};\noption.headers={\"User-Agent\":\"Mozilla/5.0 (Linux; Android 12; Nexus 5X Build/NRD90M); wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Mobile Safari/537.36\"};\njava.put('url',String(url+','+JSON.stringify(option)))",
    "weight": 85
}
```

因为上面规则用的还是手机浏览器 UA，所以可能会跳转手机版？
不行的话，换成电脑浏览器 UA 试试：

```
    "searchUrl": "@js:\nurl = 'https://www.ddxs.com/search.php';\noption={\"body\":\"keyword=\"+key,\"charset\":\"UTF-8\",\"method\":\"POST\"};\noption.headers={\"User-Agent\":\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.24\"};\njava.put('url',String(url+','+JSON.stringify(option)))",
```

如果还不行就算啦，我可以在详情地址规则中替换 URL 中的域名为电脑版网页。

**Comment by 821938089** [comment]
那个cookies获取不到的问题我查了一下是旧版webview的bug，有些有特殊属性的cookies会无法获取，这个问题在webview 72版本之后就修复了。

https://stackoverflow.com/questions/65812748/cookiemanager-getcookie-always-returns-null-version-api-28-pie
https://stackoverflow.com/questions/40798777/android-extrac-samesite-strict-cookie-from-webview-or-url
https://bugs.chromium.org/p/chromium/issues/detail?id=780491

**Comment by daiaji** [comment]
```
@js:
url = "http://www.shencou.com/modules/article/search.php?searchtype=articlename+selected&searchkey="+key+"&page="+page;
option={"charset": "gbk"};
option.headers={"User-Agent":"Mozilla/5.0 (Linux; Android 12; Nexus 5X Build/NRD90M); wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Mobile Safari/537.36"};
java.get('url',String(url+','+JSON.stringify(option)))
```

```
[00:00.000] ⇒开始搜索关键字:我的
[00:00.001] ︾开始解析搜索页
[00:00.008] com.script.ScriptException: org.mozilla.javascript.EvaluatorException: Can't find method io.legado.app.model.analyzeRule.AnalyzeUrl.get(string,string). (<Unknown source>#5) in <Unknown source> at line number 5
	at com.script.rhino.RhinoScriptEngine.eval(RhinoScriptEngine.kt:98)
	at com.script.AbstractScriptEngine.eval(AbstractScriptEngine.kt:2)
	at com.script.AbstractScriptEngine.eval(AbstractScriptEngine.kt:7)
	at com.script.AbstractScriptEngine.eval(AbstractScriptEngine.kt:4)
	at io.legado.app.model.analyzeRule.AnalyzeUrl.evalJS(AnalyzeUrl.kt:97)
	at io.legado.app.model.analyzeRule.AnalyzeUrl.analyzeJs(AnalyzeUrl.kt:82)
	at io.legado.app.model.analyzeRule.AnalyzeUrl.initUrl(AnalyzeUrl.kt:5)
	at io.legado.app.model.analyzeRule.AnalyzeUrl.<init>(AnalyzeUrl.kt:25)
	at io.legado.app.model.analyzeRule.AnalyzeUrl.<init>(AnalyzeUrl.kt:27)
	at io.legado.app.model.webBook.l.n(WebBook.kt:162)
	at io.legado.app.model.webBook.l$f.invokeSuspend(WebBook.kt:35)
	at io.legado.app.model.webBook.l$f.invoke(WebBook.kt:2)
	at io.legado.app.model.webBook.l$f.invoke(WebBook.kt:1)
	at io.legado.app.help.coroutine.e.invokeSuspend(Coroutine.kt:61)
	at o6.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.j0.run(DispatchedTask.kt:119)
	at kotlinx.coroutines.internal.f.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.j.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.a$b.run(CoroutineScheduler.kt:82)
Caused by: org.mozilla.javascript.EvaluatorException: Can't find method io.legado.app.model.analyzeRule.AnalyzeUrl.get(string,string). (<Unknown source>#5)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:23)
	at org.mozilla.javascript.Context.reportRuntimeError(Context.java:3)
	at org.mozilla.javascript.Context.reportRuntimeError(Context.java:6)
	at org.mozilla.javascript.Context.reportRuntimeErrorById(Context.java:5)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:315)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:365)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:57)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:21)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:1)
	at com.script.rhino.RhinoScriptEngine$Companion$1.superDoTopCall(RhinoScriptEngine.kt:1)
	at com.script.rhino.RhinoScriptEngine$Companion$1.doTopCall(RhinoScriptEngine.kt:65)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:8)
	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:23)
	at org.mozilla.javascript.Context.evaluateReader(Context.java:7)
	at com.script.rhino.RhinoScriptEngine.eval(RhinoScriptEngine.kt:38)
	... 18 more
```
java.get怎么弄？
报错。
