### ISSUE TITLE
书源校验内存溢出

### ISSUE THREAD

**Issue by TanxiangCode** [gedoor/legado#2659]
SDK_INT=33
MODEL=2201122C
RELEASE=13
MANUFACTURER=Xiaomi
versionName=3.22.122419
versionCode=13015
BRAND=Xiaomi
java.lang.OutOfMemoryError: Failed to allocate a 336 byte allocation with 290504 free bytes and 283KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at android.icu.impl.coll.CollationIterator$CEBuffer.<init>(CollationIterator.java:81)
	at android.icu.impl.coll.CollationIterator.reset(CollationIterator.java:390)
	at android.icu.impl.coll.UTF16CollationIterator.setText(UTF16CollationIterator.java:65)
	at android.icu.text.RuleBasedCollator.doCompare(RuleBasedCollator.java:1651)
	at android.icu.text.RuleBasedCollator.compare(RuleBasedCollator.java:1447)
	at d9.e0.a(StringExtensions.kt:23)
	at io.legado.app.data.dao.BookSourceDao$dealGroups$2.invoke(BookSourceDao.kt:2)
	at io.legado.app.data.dao.BookSourceDao$dealGroups$2.invoke(BookSourceDao.kt:1)
	at io.legado.app.data.dao.BookSourceDao$DefaultImpls.dealGroups$lambda$2(BookSourceDao.kt:6)
	at io.legado.app.data.dao.BookSourceDao$DefaultImpls.a(Unknown Source:0)
	at io.legado.app.data.dao.a.compare(Unknown Source:2)
	at java.util.TimSort.mergeHi(TimSort.java:841)
	at java.util.TimSort.mergeAt(TimSort.java:520)
	at java.util.TimSort.mergeForceCollapse(TimSort.java:461)
	at java.util.TimSort.sort(TimSort.java:254)
	at java.util.Arrays.sort(Arrays.java:1427)
	at v9.t.c0(_Collections.kt:40)
	at io.legado.app.data.dao.BookSourceDao$DefaultImpls.dealGroups(BookSourceDao.kt:47)
	at io.legado.app.data.dao.BookSourceDao$DefaultImpls.access$dealGroups(BookSourceDao.kt:1)
	at io.legado.app.data.dao.BookSourceDao$DefaultImpls$flowGroups$$inlined$map$1$2.emit(Emitters.kt:57)
	at ad.o$a.invoke(SafeCollector.kt:2)
	at ad.o$a.invoke(SafeCollector.kt:1)
	at ad.n.a(SafeCollector.kt:131)
	at ad.n.emit(SafeCollector.kt:1)
	at a5.a.e(Detector.java:150)
	at zc.g.invokeSuspend(Channels.kt:12)
	at aa.a.resumeWith(ContinuationImpl.kt:9)
	at wc.m0.run(DispatchedTask.kt:119)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8116)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
	Suppressed: wc.k0: [x1{Cancelling}@7ad2110, Dispatchers.Main]

**Comment by gedoor** [comment]
线程数调小点试试

**Comment by gedoor** [comment]
校验的线程数和下载的线程数是一样的

**Comment by TanxiangCode** [comment]
嗯，调到10以下还是会有这个问题的

**Comment by 821938089** [comment]
你用二分法校验看一下是哪个源有问题，或者把全部书源发出来看看
