### ISSUE TITLE
Broken covers

### ISSUE THREAD

**Issue by unOmni** [gedoor/legado#2666]
`java.io.FileNotFoundException: /storage/emulated/0/Android/data/io.legado.app.release/files/covers/809088ae7d323b9b.jpg: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
	at l6.a.<init>(EpubFile.kt:228)
	at l6.a$a.a(EpubFile.kt:45)
	at v5.c.g(BookHelp.kt:71)
	at k6.a0.invokeSuspend(ReadBook.kt:54)
	at k6.a0.invoke(Unknown Source:8)
	at k6.a0.invoke(Unknown Source:4)
	at x5.f.invokeSuspend(Coroutine.kt:61)
	at aa.a.resumeWith(ContinuationImpl.kt:9)
	at wc.m0.run(DispatchedTask.kt:119)
	at bd.f.run(LimitedDispatcher.kt:13)
	at cd.j.run(Tasks.kt:3)
	at cd.a$b.run(CoroutineScheduler.kt:82)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8611)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 14 more`

**Comment by 821938089** [comment]
try clean cache.
or delete covers folder.

**Comment by unOmni** [comment]
Cover folder doesn't exist to begin with.

**Comment by 821938089** [comment]
Did you restore the backup from the regular version of the app?

**Comment by unOmni** [comment]
Yes i did. I'll assume I'm not supposed to do that.
