### ISSUE TITLE
校验时未知闪退

### ISSUE THREAD

**Issue by liantn** [gedoor/legado#2679]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关

### 问题描述

详见视频

### 复现步骤

https://user-images.githubusercontent.com/81289991/210639720-7f3dd730-3da8-4ebc-9159-7e775288759f.mp4

### 日志提交

SDK_INT=33
MODEL=MI 8
RELEASE=13
MANUFACTURER=Xiaomi
versionName=3.22.122419
versionCode=13015
BRAND=Xiaomi
java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 572512 free bytes and 559KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at java.lang.StringFactory.newStringFromUtf8Bytes(Native Method)
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:80)
	at okio.Buffer.readString(Buffer.kt:6)
	at okio.Buffer.readUtf8(Buffer.kt:2)
	at okio.internal._BufferKt.readUtf8Line(-Buffer.kt:25)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:4)
	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:5)
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:17)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:3)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:146)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:155)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:33)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:155)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:195)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:155)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:168)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:155)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:33)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:155)
	at a6.e.intercept(R8$$SyntheticClass:66)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:155)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:114)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:34)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

### 阅读版本

3.22.122419

### Android版本

13

### 机型

MI 8

### 其他信息

如果需要源就@我

**Comment by gedoor** [comment]
内存不够,减小线程试试
