### ISSUE TITLE
最新版不能访问链接了

### ISSUE THREAD

**Issue by iyhkhtrk** [gedoor/legado#2756]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

如题
![Screenshot_20230204_002327](https://user-images.githubusercontent.com/104120418/216654758-cec4ef46-f0d4-413e-80c4-caf14ba0de74.jpg)

### 复现步骤 / How to reproduce

无

### 日志提交 / Relevant log output

java.lang.NoClassDefFoundError: j$.util.concurrent.ConcurrentLinkedQueue
	at okhttp3.internal.connection.RealConnectionPool.<init>(RealConnectionPool.kt:43)
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:5)
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:6)
	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:3)
	at io.legado.app.help.http.e$b.invoke(HttpHelper.kt:6)
	at io.legado.app.help.http.e$b.invoke(HttpHelper.kt:1)
	at m6.m.getValue(LazyJVM.kt:21)
	at io.legado.app.help.http.e.a(HttpHelper.kt:3)
	at io.legado.app.help.http.e.b(HttpHelper.kt:19)
	at io.legado.app.model.analyzeRule.AnalyzeUrl.getStrResponseAwait(AnalyzeUrl.kt:367)
	at io.legado.app.model.analyzeRule.AnalyzeUrl.getStrResponseAwait$default(AnalyzeUrl.kt:17)
	at io.legado.app.model.webBook.l.g(WebBook.kt:272)
	at io.legado.app.ui.main.n.invokeSuspend(MainViewModel.kt:214)
	at io.legado.app.ui.main.n.invoke(MainViewModel.kt:2)
	at io.legado.app.ui.main.n.invoke(MainViewModel.kt:1)
	at io.legado.app.base.e.invokeSuspend(BaseViewModel.kt:33)
	at io.legado.app.base.e.invoke(BaseViewModel.kt:2)
	at io.legado.app.base.e.invoke(BaseViewModel.kt:1)
	at io.legado.app.help.coroutine.g.invokeSuspend(Coroutine.kt:61)
	at p6.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.m0.run(DispatchedTask.kt:119)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NoSuchMethodError: No virtual method findVarHandle(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/invoke/VarHandle; in class Ljava/lang/invoke/MethodHandles$Lookup; or its super classes (declaration of 'java.lang.invoke.MethodHandles$Lookup' appears in /system/framework/core-oj.jar)
	at j$.util.concurrent.ConcurrentLinkedQueue.<clinit>(Unknown Source:10)
	at okhttp3.internal.connection.RealConnectionPool.<init>(RealConnectionPool.kt:43)
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:5)
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:6)
	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:3)
	at io.legado.app.help.http.e$b.invoke(HttpHelper.kt:6)
	at io.legado.app.help.http.e$b.invoke(HttpHelper.kt:1)
	at m6.m.getValue(LazyJVM.kt:21)
	at io.legado.app.help.http.e.a(HttpHelper.kt:3)
	at io.legado.app.lib.webdav.d$r.invoke(WebDav.kt:3)
	at io.legado.app.lib.webdav.d$r.invoke(WebDav.kt:1)
	at m6.m.getValue(LazyJVM.kt:21)
	at io.legado.app.lib.webdav.d.g(WebDav.kt:3)
	at io.legado.app.lib.webdav.d.e(WebDav.kt:60)
	at io.legado.app.lib.webdav.d.j(WebDav.kt:85)
	at io.legado.app.help.b.l(AppWebDav.kt:151)
	at io.legado.app.help.b$a.invokeSuspend(AppWebDav.kt:29)
	at p6.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.m0.run(DispatchedTask.kt:119)
	at kotlinx.coroutines.v0.k(EventLoop.common.kt:154)
	at kotlinx.coroutines.e0.x(DebugStrings.kt:108)
	at io.legado.app.help.b.<clinit>(AppWebDav.kt:36)
	at io.legado.app.App$a.invokeSuspend(App.kt:217)
	at io.legado.app.App$a.invoke(App.kt:2)
	at io.legado.app.App$a.invoke(App.kt:1)
	at io.legado.app.help.coroutine.g.invokeSuspend(Coroutine.kt:61)
	at p6.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.m0.run(DispatchedTask.kt:119)
	at kotlinx.coroutines.internal.f.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.j.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.a$b.run(CoroutineScheduler.kt:82)

### 阅读版本 / Legado version

3.23.020320

### Android版本 / Android version

Android 9

### 机型 / Model

vivo Y3

**Comment by Xwite** [comment]
closed #2757
