### ISSUE TITLE
书源登录后，删除点击删除登录头闪退

### ISSUE THREAD

**Issue by iyhkhtrk** [gedoor/legado#2853]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

如题

### 复现步骤 / How to reproduce

如题

### 日志提交 / Relevant log output

SDK_INT=28
MODEL=V1901A
RELEASE=9
MANUFACTURER=vivo
versionName=3.23.030818
versionCode=10001
BRAND=vivo
java.lang.NullPointerException: cookieGlob must not be null
	at io.legado.app.help.http.CookieStore.removeCookie(CookieStore.kt:93)
	at io.legado.app.data.entities.BaseSource$DefaultImpls.removeLoginHeader(BaseSource.kt:30)
	at io.legado.app.data.entities.BookSource.removeLoginHeader(BookSource.kt:1)
	at io.legado.app.ui.login.b.onMenuItemClick(R8$$SyntheticClass:86)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:19)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:7)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:5)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:15)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:4)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:28)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1260)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3290)
	at android.widget.AbsListView$3.run(AbsListView.java:4263)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7087)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)

### 阅读版本 / Legado version

3.23.030818

### Android版本 / Android version

Android 9

### 机型 / Model

vivo Y3

**Comment by gedoor** [comment]
我看看

**Comment by gedoor** [comment]
已解决
