### ISSUE TITLE
使用webview加载网页闪退

### ISSUE THREAD

**Issue by iyhkhtrk** [gedoor/legado#2863]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

如题

### 复现步骤 / How to reproduce

如题

### 日志提交 / Relevant log output

SDK_INT=28
WebViewUserAgent=Mozilla/5.0 (Linux; Android 9; V1901A Build/P00610; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/111.0.5563.58 Mobile Safari/537.36
MODEL=V1901A
RELEASE=9
MANUFACTURER=vivo
versionName=3.23.031103
versionCode=13497
BRAND=vivo
java.lang.ExceptionInInitializerError
	at a9.a.<clinit>(StringEscapeUtils.java:39)
	at a9.a.a(StringEscapeUtils.java:1)
	at io.legado.app.help.http.b.onReceiveValue(R8$$SyntheticClass:45)
	at dh.a(chromium-SystemWebViewGoogle.aab-stable-556305803:3)
	at ch.run(chromium-SystemWebViewGoogle.aab-stable-556305803:5)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7087)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)
Caused by: java.lang.ClassCastException: r.a cannot be cast to java.util.function.Function
	at j$.util.stream.m.accept(SourceFile:0)
	at j$.util.stream.M1.accept(Unknown Source:4)
	at j$.util.Iterator$-CC.$default$forEachRemaining(Unknown Source:13)
	at j$.util.e0.forEachRemaining(SourceFile:0)
	at j$.util.stream.c.c0(SourceFile:0)
	at j$.util.stream.c.A0(Unknown Source:10)
	at j$.util.stream.A0.v(Unknown Source:4)
	at j$.util.stream.c.D0(SourceFile:0)
	at j$.util.stream.j2.collect(SourceFile:0)
	at c9.f.a(EntityArrays.java:25)
	at c9.f.<clinit>(EntityArrays.java:99)
	... 12 more
java.lang.ClassCastException: r.a cannot be cast to java.util.function.Function
	at j$.util.stream.m.accept(SourceFile:0)
	at j$.util.stream.M1.accept(Unknown Source:4)
	at j$.util.Iterator$-CC.$default$forEachRemaining(Unknown Source:13)
	at j$.util.e0.forEachRemaining(SourceFile:0)
	at j$.util.stream.c.c0(SourceFile:0)
	at j$.util.stream.c.A0(Unknown Source:10)
	at j$.util.stream.A0.v(Unknown Source:4)
	at j$.util.stream.c.D0(SourceFile:0)
	at j$.util.stream.j2.collect(SourceFile:0)
	at c9.f.a(EntityArrays.java:25)
	at c9.f.<clinit>(EntityArrays.java:99)
	at a9.a.<clinit>(StringEscapeUtils.java:39)
	at a9.a.a(StringEscapeUtils.java:1)
	at io.legado.app.help.http.b.onReceiveValue(R8$$SyntheticClass:45)
	at dh.a(chromium-SystemWebViewGoogle.aab-stable-556305803:3)
	at ch.run(chromium-SystemWebViewGoogle.aab-stable-556305803:5)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7087)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)

### 阅读版本 / Legado version

3.23.031103

### Android版本 / Android version

Android 9

### 机型 / Model

vivo Y3

**Comment by gedoor** [comment]
我看下

**Comment by iyhkhtrk** [comment]
> 我看下

最新版好了

**Comment by iyhkhtrk** [comment]
Rhino更新后又会了
<pre><code>
SDK_INT=28
WebViewUserAgent=Mozilla/5.0 (Linux; Android 9; V1901A Build/P00610; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/111.0.5563.116 Mobile Safari/537.36
MODEL=V1901A
RELEASE=9
MANUFACTURER=vivo
versionName=3.23.032322
versionCode=13822
BRAND=vivo
java.lang.IncompatibleClassChangeError: Class 'cn.hutool.core.annotation.c0' does not implement interface 'java.util.function.Function' in call to 'java.lang.Object java.util.function.Function.apply(java.lang.Object)' (declaration of 'java.util.stream.Collectors' appears in /system/framework/core-oj.jar)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
	at java.util.stream.-$$Lambda$Collectors$nKlT6uFghrTzWO44dlFAJFeRr34.accept(Unknown Source:8)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0(Collections.java:1617)
	at java.util.-$$Lambda$Collections$UnmodifiableMap$UnmodifiableEntrySet$W5VhpDb0JlKqrRuOSf_2RiCnSgo.accept(Unknown Source:4)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1695)
	at java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.forEachRemaining(Collections.java:1642)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:235)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:501)
	at androidx.camera.camera2.internal.c.j(R8$$SyntheticClass:1)
	at s9.f.a(EntityArrays.java:26)
	at s9.f.<clinit>(EntityArrays.java:99)
	at q9.a.<clinit>(StringEscapeUtils.java:39)
	at io.legado.app.help.http.b.onReceiveValue(R8$$SyntheticClass:45)
	at dh.a(chromium-SystemWebViewGoogle.aab-stable-556311603:3)
	at ch.run(chromium-SystemWebViewGoogle.aab-stable-556311603:5)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7087)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)

</code></pre>

**Comment by gedoor** [comment]
收到，明天看看

iyhkhtrk ***@***.***> 于 2023年3月23日周四 23:35写道：

**Comment by gedoor** [comment]
好了
