### ISSUE TITLE
求助：写的书源每次在书架页面刷新的时候，目录加载时间巨长

### ISSUE THREAD

**Issue by marujun** [gedoor/legado#2890]
### 确认

- [X] 搜索现有issues，不存在相似或相关的issue

### 功能描述

写了一个书源，在使用过程中发现，每次在书架页面刷新时后台都会从第一页开始加载目录；看的书有1000多章但是这个站点一页只显示20条目录，这样就需要加载50多次才能刷新完所以时间太长了。有没有办法在App首页刷新的时候从上一次加载的最后一页目录开始加载？这样只加载新的章节目录，而不用全部重新加载一遍。

复现过程，使用这个书源去搜索：深空彼岸
```
{
    "bookSourceComment": "",
    "bookSourceGroup": "",
    "bookSourceName": "笔趣VIP",
    "bookSourceType": 0,
    "bookSourceUrl": "https://m.biqu.vip/",
    "bookUrlPattern": "",
    "concurrentRate": "",
    "customOrder": -2085978140,
    "enabled": true,
    "enabledCookieJar": false,
    "enabledExplore": false,
    "enabledReview": false,
    "exploreUrl": "",
    "header": "",
    "lastUpdateTime": 1679324967882,
    "loginCheckJs": "",
    "loginUi": "",
    "loginUrl": "",
    "respondTime": 180000,
    "ruleBookInfo": {
        "author": ".infotype a.0@text",
        "coverUrl": ".pic img@src",
        "intro": ".intro p.0@text",
        "kind": ".infotype p.1@text##类型：",
        "lastChapter": ".infotype a.1@text",
        "name": ".cataloginfo h3@text",
        "tocUrl": ".intro p.1@text##.*"
    },
    "ruleContent": {
        "content": "#novelcontent #nr@html",
        "nextContentUrl": "text.下一页@href",
        "replaceRegex": "##一秒记住【笔趣阁vip.*精彩小说无弹窗免费阅读！|（本章未完，请点击下一页继续阅读）|\\(第\\d/\\d页\\),|\\(第\\d/\\d页\\)|{{title}}"
    },
    "ruleExplore": {},
    "ruleReview": {},
    "ruleSearch": {
        "author": "a.1@text",
        "bookList": ".searchresult p",
        "bookUrl": "@css:.sone>a@href",
        "name": "a.0@text"
    },
    "ruleToc": {
        "chapterList": ".info_menu1.1@.list_xm li a",
        "chapterName": "text",
        "chapterUrl": "href",
        "nextTocUrl": "text.下一页@href"
    },
    "searchUrl": "https://m.biqu.vip/s.php,{\n    \"charset\": \"gbk\",\n    \"method\": \"POST\",\n    \"body\": \"s={{key}}&type=articlename\"\n}",
    "weight": 0
}
```

### 期望实现方式

在书架页刷新的时候能否从上一次加载的目录最后一页开始刷新？这样只加载新的章节目录，而不用全部重新加载一遍

**Comment by marujun** [comment]
@821938089 大佬，我按照你的方案取目录的时候改为使用桌面版的网站。正常刷新速度都没有问题了，但是在刚启动App和切换网络的时候刷新书架经常会报错。所以有3点疑问麻烦帮忙看下：

1. 刷新书架的时候会不会走搜索的逻辑，是直接请求详情页还是目录页？
2. 我想要在App首页的日志中打印出请求的URL和参数应该怎么做，方便排查报错的原因。
3. 如果在请求目录页和详情页的时候如果想要使用webview应该怎么做呢？(搜索页是用的移动端网站不会触发网站的防机器人策略)
```json
{
    "bookSourceComment": "",
    "bookSourceGroup": "",
    "bookSourceName": "笔趣VIP",
    "bookSourceType": 0,
    "bookSourceUrl": "https://www.biqu.vip",
    "bookUrlPattern": "",
    "concurrentRate": "",
    "customOrder": -2085978142,
    "enabled": true,
    "enabledCookieJar": false,
    "enabledExplore": false,
    "enabledReview": false,
    "exploreUrl": "",
    "header": "",
    "lastUpdateTime": 1679455720007,
    "loginCheckJs": "",
    "loginUi": "",
    "loginUrl": "",
    "respondTime": 180000,
    "ruleBookInfo": {
        "author": "#maininfo #info p.0@text##作&nbsp;&nbsp;&nbsp;&nbsp;者：",
        "coverUrl": "#sidebar img.0@src",
        "intro": "#maininfo #intro p.0@text",
        "kind": "",
        "lastChapter": ".box_con #list dd a.0@text",
        "name": "#maininfo #info h1@text",
        "tocUrl": ""
    },
    "ruleContent": {
        "content": ".box_con #content@html",
        "nextContentUrl": "",
        "replaceRegex": "##一秒记住【笔趣阁vip.*精彩小说无弹窗免费阅读！|请记住最新网址：www.biqu.vip|『章节错误,点此举报\\(需注册会员\\)』,举报后维护人员稍后会校正章节内容。"
    },
    "ruleExplore": {},
    "ruleReview": {},
    "ruleSearch": {
        "author": "a.1@text",
        "bookList": "<js>java.log(result)</js>.searchresult .sone",
        "bookUrl": "a.0@href##^/##https://www\\.biqu\\.vip/",
        "checkKeyWord": "",
        "kind": "",
        "lastChapter": "",
        "name": "a.0@text",
        "wordCount": ""
    },
    "ruleToc": {
        "chapterList": "<js>java.log(result)</js>.box_con #list dd a",
        "chapterName": "text",
        "chapterUrl": "href",
        "nextTocUrl": "",
        "preUpdateJs": ""
    },
    "searchUrl": "@js:\nurl='https://m.biqu.vip/s.php';\noption={\"charset\":\"gbk\",\"method\":\"POST\",\"body\":\"s={{key}}&type=articlename\"};\noption.headers={\"User-Agent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36\"};\njava.put('url',String(url+','+JSON.stringify(option)))",
    "weight": 0
}
```
![Screenshot_2023-03-22-11-04-52-218_io legado app release-edit](https://user-images.githubusercontent.com/1955015/226794358-ad33daac-5692-45c0-9b24-bffc58e9696b.jpg)
因？

**Comment by 821938089** [comment]
1. 不走搜索逻辑，直接请求目录页
2. 用`java.log()`打印，如果要具体请求去抓包看看
3. 在地址最后加上`,{"webView": true}`

**Comment by marujun** [comment]
@821938089 第2个，我在列表规则里使用<js>java.log(url)</js>的时候会报错，log(result)打印出来的是HTML页面内容，应该打印哪个字段呢？在某个阶段可打印的字段有没有文档可以查？
```
com.script.ScriptException: org.mozilla.javascript.EcmaError: ReferenceError: "url" is not defined. (<Unknown source>#1) in <Unknown source> at line number 1
	at e5.a.d(AbstractScriptEngine.java:156)
	at io.legado.app.model.analyzeRule.AnalyzeRule.evalJS(AnalyzeRule.kt:98)
	at io.legado.app.model.analyzeRule.AnalyzeRule.getElements(AnalyzeRule.kt:142)
	at io.legado.app.model.webBook.c.b(BookChapterList.kt:7)
	at io.legado.app.model.webBook.c.a(BookChapterList.kt:18)
	at io.legado.app.model.webBook.l.g(WebBook.kt:187)
	at io.legado.app.model.webBook.n.invokeSuspend(WebBook.kt:41)
	at io.legado.app.model.webBook.n.invoke(WebBook.kt:2)
	at io.legado.app.model.webBook.n.invoke(WebBook.kt:1)
	at io.legado.app.help.coroutine.e.invokeSuspend(Coroutine.kt:61)
	at p6.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.j0.run(DispatchedTask.kt:119)
	at kotlinx.coroutines.internal.f.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.i.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.a$b.run(CoroutineScheduler.kt:82)
```

**Comment by 821938089** [comment]
去对应的url规则那里打印

**Comment by marujun** [comment]
@821938089 我在目录页加上webview之后正常的刷新和调试都不会再报错了，但是我把App杀死放了一段时间之后再打开还是报错如下图，再次刷新就好了，所以webview的参数在打开App之后书架的首次刷新时是不是没有被记住啊？正常来说使用webview之后就不会出现这个错误了，这是网站防止机器人的措施
```json
{
    "bookSourceComment": "",
    "bookSourceGroup": "",
    "bookSourceName": "笔趣VIP",
    "bookSourceType": 0,
    "bookSourceUrl": "https://www.biqu.vip",
    "bookUrlPattern": "",
    "concurrentRate": "",
    "customOrder": -2085978143,
    "enabled": true,
    "enabledCookieJar": false,
    "enabledExplore": false,
    "enabledReview": false,
    "exploreUrl": "",
    "header": "",
    "lastUpdateTime": 1679473068836,
    "loginCheckJs": "",
    "loginUi": "",
    "loginUrl": "",
    "respondTime": 180000,
    "ruleBookInfo": {
        "author": "#maininfo #info p.0@text##作&nbsp;&nbsp;&nbsp;&nbsp;者：",
        "coverUrl": "#sidebar img.0@src",
        "intro": "#maininfo #intro p.0@text",
        "kind": "",
        "lastChapter": ".box_con #list dd a.0@text",
        "name": "#maininfo #info h1@text",
        "tocUrl": ""
    },
    "ruleContent": {
        "content": ".box_con #content@html",
        "nextContentUrl": "",
        "replaceRegex": "##一秒记住【笔趣阁vip.*精彩小说无弹窗免费阅读！|请记住最新网址：www.biqu.vip|『章节错误,点此举报\\(需注册会员\\)』,举报后维护人员稍后会校正章节内容。"
    },
    "ruleExplore": {},
    "ruleReview": {},
    "ruleSearch": {
        "author": ".odd@text",
        "bookList": "<js>java.log(result)</js>#nr",
        "bookUrl": ".odd.0@a@href@js:java.log(result+',{\"webView\": true}');",
        "checkKeyWord": "",
        "kind": "",
        "lastChapter": ".even.0@a@text",
        "name": ".odd.0@a@text",
        "wordCount": ".even.1@text"
    },
    "ruleToc": {
        "chapterList": "<js>java.log(result)</js>.box_con #list dd a",
        "chapterName": "text",
        "chapterUrl": "href@js:result+',{\"webView\": true}'",
        "nextTocUrl": "",
        "preUpdateJs": ""
    },
    "searchUrl": "@js:\nurl='https://www.biqu.vip/modules/article/biqugeso.php';\noption={\"charset\":\"gbk\",\"method\":\"POST\",\"body\":\"searchkey={{key}}&searchtype=articlename\",\"webView\": true};\noption.headers={\"User-Agent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36\"};\njava.put('url',String(url+','+JSON.stringify(option)))",
    "weight": 0
}
```
![Screenshot_2023-03-22-15-10-24-436_io legado app release](https://user-images.githubusercontent.com/1955015/226842184-4f690e58-d39c-4417-89b9-0ce510faf014.jpg)

**Comment by 821938089** [comment]
webView有时可能加载不出来，你多试几次就好了

**Comment by marujun** [comment]
@821938089 针对这种webview加载不出来的情况，有办法可以自动重试几次吗？每次都手动刷新感觉不够智能

**Comment by 821938089** [comment]
你可以写规则自动重试
`java.ajax(baseUrl)`

**Comment by marujun** [comment]
@821938089 大佬，我在获取详情地址那里这么写：.odd.0@a@href@js:url=result+',{"webView": true}';html=java.ajax(url);last=html.includes('doctype')?'retry sucess':html;java.log(last)   一直打印不出来retry sucess；能帮忙改一改吗？脑细胞不够用了

**Comment by 821938089** [comment]
html里面没有doctype，所以打印不出来retry sucess，你看一下html的内容就知道了

重试代码写在详情预处理规则那里

**Comment by marujun** [comment]
@821938089 有点痛苦，详情预处理那里实在不知道该咋写了；能帮忙写个例子不

**Comment by marujun** [comment]
@821938089 首先感谢大佬的耐心解答，（捂脸哭）又遇到了2个问题：
1、把重试的逻辑写在详情预处理那里，书架页刷新书架的时候并不会执行预处理的逻辑（没有输出我打的日志）
2、如果书源详情页存在重定向的时候，详情预处理的时候，在书源debug那里打印出的baseUrl和在书架页的书籍详情页里点击刷新打印出的baseUrl不一样（前者打印出的是重定向之后的url，后者打印出的是重定向之前的url）两个地方表现不一致应该统一一下？我觉得debug那里的逻辑更合理一点
```
@js:
java.log('详情预处理baseUrl:' + baseUrl);
url=baseUrl + (baseUrl.indexOf('webView')!=-1?'':',{"webView": true}');
java.put('tocUrl', url);
if (book.name !== '') {
    java.log('详情页表现正常，不用预处理' + url);
    result
} else {
   java.log('详情页表现异常，即将重试！' + url);
   java.ajax(url)
}
```
![IMG_20230323_102451](https://user-images.githubusercontent.com/1955015/227085636-87dfbd77-fa34-452d-b045-15794aa75ec5.jpg)
![IMG_20230323_102658](https://user-images.githubusercontent.com/1955015/227085652-a7d7448d-30aa-404a-afe9-c3d9477c14c6.jpg)

**Comment by 821938089** [comment]
1. 那就把重试逻辑复制到目录列表规则那里
2. 试试把baseUrl换成java.url

**Comment by marujun** [comment]
@821938089 使用这个书源调试 择日飞升
```json
{
    "bookSourceComment": "",
    "bookSourceGroup": "",
    "bookSourceName": "笔趣VIP",
    "bookSourceType": 0,
    "bookSourceUrl": "https://www.biqu.vip",
    "bookUrlPattern": "",
    "concurrentRate": "",
    "customOrder": -2085978146,
    "enabled": true,
    "enabledCookieJar": false,
    "enabledExplore": false,
    "enabledReview": false,
    "exploreUrl": "",
    "header": "",
    "lastUpdateTime": 1679542052844,
    "loginCheckJs": "",
    "loginUi": "",
    "loginUrl": "",
    "respondTime": 180000,
    "ruleBookInfo": {
        "author": "#maininfo #info p.0@text##.*：",
        "coverUrl": "#sidebar img.0@src",
        "init": "@js:\njava.log('详情预处理baseUrl:' + baseUrl);\nurl=baseUrl + (baseUrl.indexOf('webView')!=-1?'':',{\"webView\": true}');\njava.put('tocUrl', url);\nif (book.name !== '') {\n    java.log('详情页表现正常，不用预处理' + url);\n    result\n} else {\n   java.log('详情页表现异常，即将重试！' + url);\n   java.ajax(url)\n}",
        "intro": "#maininfo #intro p.0@text",
        "kind": "",
        "lastChapter": ".box_con #list dd a.0@text",
        "name": "#maininfo #info h1@text",
        "tocUrl": "@js:java.get('tocUrl')"
    },
    "ruleContent": {
        "content": ".box_con #content@html",
        "nextContentUrl": "",
        "replaceRegex": "##一秒记住【笔趣阁vip.*精彩小说无弹窗免费阅读！|请记住最新网址：www.biqu.vip|『章节错误,点此举报\\(需注册会员\\)』,举报后维护人员稍后会校正章节内容。"
    },
    "ruleExplore": {},
    "ruleReview": {},
    "ruleSearch": {
        "author": ".odd.1@text",
        "bookList": "#nr",
        "bookUrl": ".odd.0@a@href@js:result+',{\"webView\": true}'",
        "checkKeyWord": "",
        "kind": "",
        "lastChapter": ".even.0@a@text",
        "name": ".odd.0@a@text",
        "wordCount": ".even.1@text"
    },
    "ruleToc": {
        "chapterList": "<js>html=result;java.log(book.name+book.tocUrl+'\\n');html</js>.box_con #list dd a",
        "chapterName": "text",
        "chapterUrl": "href@js:result+',{\"webView\": true}'",
        "nextTocUrl": "",
        "preUpdateJs": ""
    },
    "searchUrl": "@js:\nurl='https://www.biqu.vip/modules/article/biqugeso.php';\noption={\"charset\":\"gbk\",\"method\":\"POST\",\"body\":\"searchkey={{key}}&searchtype=articlename\",\"webView\": true};\noption.headers={\"User-Agent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36\"};\njava.put('url',String(url+','+JSON.stringify(option)))",
    "weight": 0
}
```

**Comment by 821938089** [comment]
就用baseUrl啊，不过要判断一下只存正确的

**Comment by marujun** [comment]
@821938089 额， 可是在详情页的刷新那里baseUrl就是错的，拿不到正确的

**Comment by 821938089** [comment]
搜索的时候是正确的，一旦拿到正确的就可以一直用

**Comment by marujun** [comment]
> 搜索的时候是正确的，一旦拿到正确的就可以一直用

的确是这样的，感谢
