### ISSUE TITLE
恢复不了在系统文件里的备份

### ISSUE THREAD

**Issue by Yoseimiu** [gedoor/legado#2892]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

我用恢复功能，选择了系统文件里的备份文件。有跳出来显示“恢复成功“，可是日记显示“读取排版配置文件出错”。"恢复复制文件出错 Invalid URl: content://com.android.externalstorage.documents/document/primary%3ANovel%2Fbackup2023-03-20-2109119DC.zip"
就算我重新备份在选择恢复也还是有问题。

### 复现步骤 / How to reproduce

我的 -> 备份与恢复 -> 恢复 （长按）选择恢复文件

### 日志提交 / Relevant log output

java.lang.NullPointerException: null cannot be cast to non-null type kotlin.collections.List<T of io.legado.app.utils.GsonExtensionsKt.fromJsonArray$lambda$1>
	at io.legado.app.help.config.ReadBookConfig.initConfigs(ReadBookConfig.kt:35)
	at io.legado.app.help.storage.e$c.invokeSuspend(Restore.kt:243)
	at io.legado.app.help.storage.e$c.invoke(Restore.kt:2)
	at io.legado.app.help.storage.e$c.invoke(Restore.kt:1)
	at com.google.common.collect.q0.s(Iterables.java:5)
	at z4.d.t0(RhinoClassShutter.java:72)
	at io.legado.app.help.storage.e.b(Restore.kt:68)
	at io.legado.app.help.storage.e.a(Restore.kt:227)
	at io.legado.app.ui.config.BackupConfigFragment$h.invokeSuspend(BackupConfigFragment.kt:35)
	at io.legado.app.ui.config.BackupConfigFragment$h.invoke(BackupConfigFragment.kt:2)
	at io.legado.app.ui.config.BackupConfigFragment$h.invoke(BackupConfigFragment.kt:1)
	at io.legado.app.help.coroutine.f.invokeSuspend(Coroutine.kt:61)
	at i6.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.j0.run(DispatchedTask.kt:119)
	at kotlinx.coroutines.internal.f.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.j.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.a$b.run(CoroutineScheduler.kt:82)

### 阅读版本 / Legado version

3.23.031210

### Android版本 / Android version

Android 12/13

### 机型 / Model

Xiaomi mi11 / oppo find n2 flip

**Comment by gedoor** [comment]
没法复现这个错误
