### ISSUE TITLE
[RhinoJS] 返回值不能为空

### ISSUE THREAD

**Issue by Xwite** [gedoor/legado#2895]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

js必须有返回值，否则报错java.lang.NullPointerException

### 复现步骤 / How to reproduce

1. 导入下面书源
2. 点击调试

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

```json
{
  "bookSourceName": "js非空返回值",
  "bookSourceType": 0,
  "bookSourceUrl": "https://baidu.cn",
  "customOrder": 0,
  "enabled": true,
  "enabledCookieJar": true,
  "enabledExplore": true,
  "enabledReview": false,
  "lastUpdateTime": 1679370393370,
  "respondTime": 180000,
  "ruleBookInfo": {},
  "ruleContent": {},
  "ruleExplore": {},
  "ruleReview": {},
  "ruleSearch": {},
  "ruleToc": {},
  "searchUrl": "<js>\nnull\n</js>",
  "weight": 0
}
```
```json
{
  "bookSourceName": "js非空返回值",
  "bookSourceType": 0,
  "bookSourceUrl": "https://baidu.cn/",
  "customOrder": 0,
  "enabled": true,
  "enabledCookieJar": true,
  "enabledExplore": true,
  "enabledReview": false,
  "lastUpdateTime": 1679370473686,
  "respondTime": 180000,
  "ruleBookInfo": {},
  "ruleContent": {},
  "ruleExplore": {},
  "ruleReview": {},
  "ruleSearch": {},
  "ruleToc": {},
  "searchUrl": "<js>\n\n</js>",
  "weight": 0
}
```

### 日志提交 / Relevant log output

```
java.lang.NullPointerException: super.doTopCall(callable…cx, scope, thisObj, args) must not be null
	at f5.f$b.a(RhinoScriptEngine.kt:7)
	at f5.f$b.doTopCall(RhinoScriptEngine.kt:70)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:8)
	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:23)
	at org.mozilla.javascript.Context.evaluateReader(Context.java:7)
	at e5.a.d(AbstractScriptEngine.java:75)
```

```
java.lang.NullPointerException
	at e5.a.d(AbstractScriptEngine.java:103)
	at io.legado.app.model.analyzeRule.AnalyzeUrl.evalJS(AnalyzeUrl.kt:96)
```

### 阅读版本 / Legado version

3.23.0321

### Android版本 / Android version

12

### 机型 / Model

none

**Comment by gedoor** [comment]
OK

Xwite ***@***.***> 于 2023年3月21日周二 11:49写道：

**Comment by gedoor** [comment]
修复了
