### ISSUE TITLE
无法正常导入txt文件！当文件名以 # 开头

### ISSUE THREAD

**Issue by jamesfu1978** [gedoor/legado#2966]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

由于某种原因，可能是我的设置有所更改，导致只要文件名以 # 开头的txt文件都无法正常导入，它会将该文件识别为包含该文件的文件夹 ，比如 download/#都市《隐杀》.txt 就无法导入，因为APP会将将该路径识别为 download文件夹并提示你这是个文件夹。
报错提示：LoadTocError:/...../0/Download (Is a direcory)
PS：之前在默认设置下是可以正常导入以 # 开头的TXT文件的。但由于后来进行了一些设置，具体就是导入了一些规则，导致该BUG的出现

### 复现步骤 / How to reproduce

PS：之前在默认设置下是可以正常导入以 # 开头的TXT文件的。但由于后来进行了一些设置，具体就是导入了一些规则，导致该BUG的出现
1.使用 阅读 无法正常导入以 # 开头的txt文件
报错提示：LoadTocError:/...../0/Download (Is a direcory)
2.这种txt文件也无法用 阅读 正常打开
报错提示：LoadTocError:/...../0/Download (Is a direcory)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.22.050215

### Android版本 / Android version

Android8.0.0

### 机型 / Model

MI6

**Comment by 821938089** [comment]
书架右上角三点日志，点一下LoadTocError那条

**Comment by jamesfu1978** [comment]
java.io.FileNotFoundException: /storage/emulated/0/Download/txt (Is a directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:200)
	at java.io.FileInputStream.<init>(FileInputStream.java:150)
	at i

**Comment by jamesfu1978** [comment]
java.io.FileNotFoundException: /storage/emulated/0/Download/txt (Is a directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:200)
	at java.io.FileInputStream.<init>(FileInputStream.java:150)
	at io.legado.app.model.localBook.LocalBook.getBookInputStream(LocalBook.kt:39)
	at io.legado.app.model.localBook.TextFile.getChapterList(TextFile.kt:61)
	at io.legado.app.model.localBook.TextFile$Companion.getChapterList(TextFile.kt:24)
	at io.legado.app.model.localBook.LocalBook.getChapterList(LocalBook.kt:54)
	at io.legado.app.ui.book.read.ReadBookViewModel$loadChapterList$1.invokeSuspend(ReadBookViewModel.kt:130)
	at io.legado.app.ui.book.read.ReadBookViewModel$loadChapterList$1.invoke(Unknown Source:8)
	at io.legado.app.ui.book.read.ReadBookViewModel$loadChapterList$1.invoke(Unknown Source:4)
	at io.legado.app.base.BaseViewModel$execute$1.invokeSuspend(BaseViewModel.kt:24)
	at io.legado.app.base.BaseViewModel$execute$1.invoke(Unknown Source:8)
	at io.legado.app.base.BaseViewModel$execute$1.invoke(Unknown Source:4)
	at io.legado.app.help.coroutine.Coroutine$executeBlock$2.invokeSuspend(Coroutine.kt:200)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by 821938089** [comment]
你这阅读不是最新版啊

**Comment by jamesfu1978** [comment]
ok，已经升级了，问题不见了，早知道就不恢复之前备份了。。。
