### ISSUE TITLE
使用蓝牙耳机朗读时会跳张或者跳段

### ISSUE THREAD

**Issue by plwd2022** [gedoor/legado#3195]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

使用所有我现有的语音库，在连接蓝牙耳机，音响设备读书时，在翻页或者换张时有概率漏读或者卡顿

### 复现步骤 / How to reproduce

参考手机，红米n10p，n12t，miui13，14全版本都可。连蓝牙耳机，找本书，可参考使用讯飞语记，调整到按页朗读，然后盯着屏幕对照朗读内容是否一致，尤其在翻页的时候是否跳页是否停顿，建议测试五分钟就可以富县。

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

SDK_INT=33
WebViewUserAgent=Mozilla/5.0 (Linux; Android 13; 23049RAD8C Build/TKQ1.221114.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.13 Mobile Safari/537.36
MODEL=23049RAD8C
RELEASE=13
MANUFACTURER=Xiaomi
versionName=3.23.051919
versionCode=14336
BRAND=Redmi
java.lang.RuntimeException: Unable to start receiver io.legado.app.receiver.MediaButtonReceiver: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { act=play cmp=io.legado.app.release/io.legado.app.service.TTSReadAloudService (has extras) }: app is in background uid UidRecord{366ee69 u0a343 CEM  bg:+24m5s602ms idle change:procadj procs:0 seq(9287305,9094174)}
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4593)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8395)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { act=play cmp=io.legado.app.release/io.legado.app.service.TTSReadAloudService (has extras) }: app is in background uid UidRecord{366ee69 u0a343 CEM  bg:+24m5s602ms idle change:procadj procs:0 seq(9287305,9094174)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1918)
	at android.app.ContextImpl.startService(ContextImpl.java:1874)
	at android.content.ContextWrapper.startService(ContextWrapper.java:827)
	at io.legado.app.model.n0.e(SourceFile:52)
	at io.legado.app.model.g1.n(SourceFile:14)
	at com.google.android.material.navigation.d.r(SourceFile:150)
	at com.google.android.material.navigation.d.o(SourceFile:56)
	at io.legado.app.receiver.MediaButtonReceiver.onReceive(SourceFile:11)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4581)
	... 9 more
android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { act=play cmp=io.legado.app.release/io.legado.app.service.TTSReadAloudService (has extras) }: app is in background uid UidRecord{366ee69 u0a343 CEM  bg:+24m5s602ms idle change:procadj procs:0 seq(9287305,9094174)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1918)
	at android.app.ContextImpl.startService(ContextImpl.java:1874)
	at android.content.ContextWrapper.startService(ContextWrapper.java:827)
	at io.legado.app.model.n0.e(SourceFile:52)
	at io.legado.app.model.g1.n(SourceFile:14)
	at com.google.android.material.navigation.d.r(SourceFile:150)
	at com.google.android.material.navigation.d.o(SourceFile:56)
	at io.legado.app.receiver.MediaButtonReceiver.onReceive(SourceFile:11)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4581)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8395)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

### 阅读版本 / Legado version

3.23.060622

### Android版本 / Android version

13

### 机型 / Model

手机型号 Redmi Note 12 Turbo

**Comment by a2841905265** [comment]
在最新版本上测试，问题仍然浮现。

**Comment by 821938089** [comment]
你确定用的是最新版吗，目前最新版是`3.23.062623`

**Comment by a2841905265** [comment]
是最新的，用最新的已经测试过了。

**Comment by a2841905265** [comment]
已经不是一两个小版的问题了，我记得这个21年就有。

**Comment by 821938089** [comment]
那新版有没有日志

**Comment by 821938089** [comment]
可不可以录个视频看看

**Comment by a2841905265** [comment]
我试着录过视频了，但是可能录屏的时候音频协议和不录屏时候的音频协议不太一样，只是我的个人猜想。录屏的时候问题倒不会出现。另外日志只是崩溃日志，应该没有跳章的记录。并且我的阅读最近也没有崩溃过了。

**Comment by a2841905265** [comment]
另外不止是翻页时会遇到这样的问题，有的时候朗读个别句子的时候，也会偶尔漏掉几句。

**Comment by a2841905265** [comment]
关闭AAC之后的确好了。不会跳章节也不会跳句子。也不会有长时间停顿。不知道是否可以解决这问题呢？如果无法的话也希望可以在软件文档和帮助备注一下，避免他人踩坑。
