### ISSUE TITLE
最新版开启朗读失败,提示创建朗读通知失败

### ISSUE THREAD

**Issue by logique233** [gedoor/legado#3211]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

最新版开启朗读失败,提示创建朗读通知失败

### 复现步骤 / How to reproduce

正常使用朗读功能,提示创建朗读通知失败,多次点击有概率成功播放.回退版本3.23.062623朗读功能一切正常

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

java.lang.IllegalStateException: Can't copy a recycled bitmap
	at android.graphics.Bitmap.checkRecycled(Bitmap.java:420)
	at android.graphics.Bitmap.copy(Bitmap.java:707)
	at android.graphics.drawable.Icon.setBitmap(Icon.java:181)
	at android.graphics.drawable.Icon.createWithBitmap(Icon.java:670)
	at android.app.Notification$Builder.setLargeIcon(Notification.java:4516)
	at androidx.core.app.NotificationCompatBuilder.<init>(SourceFile:190)
	at androidx.core.app.NotificationCompat$Builder.build(Unknown Source:2)
	at io.legado.app.service.z.invokeSuspend(SourceFile:17)
	at io.legado.app.service.z.invoke(SourceFile:2)
	at io.legado.app.service.z.invoke(SourceFile:1)
	at io.legado.app.help.coroutine.i.invokeSuspend(SourceFile:214)
	at o4.a.resumeWith(SourceFile:9)
	at kotlinx.coroutines.i0.run(SourceFile:128)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8136)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

### 阅读版本 / Legado version

3.23.070809

### Android版本 / Android version

Android 13

### 机型 / Model

redmi note 11T pro+ miui14

**Comment by gedoor** [comment]
收到,晚上修复

**Comment by zousizhe** [comment]
> 收到,晚上修复

通知栏朗读暂停与继续控制有问题，只能暂停一次，第二次无法再暂停

**Comment by gedoor** [comment]
修复了
