### ISSUE TITLE
进入阅读小说的界面闪退

### ISSUE THREAD

**Issue by KJZH001** [gedoor/legado#3233]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

进入阅读小说的界面闪退（比如说从书架直接打开阅读界面，或从目录中选择章节进入），搜索在线书籍的列表中会闪退回到搜索记录的界面中

### 复现步骤 / How to reproduce

直接打开书籍就会闪退

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

```
在刷机root前，该设备能够正常工作，运行环境为VisualXposed

现在换回之前能够正常工作的版本也会闪退，面具启用遵守排除列表后排除软件问题不变

尝试在play中更新到最新的浏览器内核，没有解决
```

### 日志提交 / Relevant log output

此处提交的是在此设备原先能够正常工作的版本的日志，最新的测试版有同样的问题

```
MANUFACTURER=HUAWEI
versionName=3.22.041421
versionCode=11134
BRAND=HONOR
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.legado.app.release/io.legado.app.ui.book.read.ReadBookActivity}: android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class io.legado.app.ui.book.read.page.ReadView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3194)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
	at android.app.ActivityThread.-wrap12(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
Caused by: android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class io.legado.app.ui.book.read.page.ReadView
Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class io.legado.app.ui.book.read.page.ReadView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
	at android.view.LayoutInflater.createView(LayoutInflater.java:658)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at io.legado.app.databinding.ActivityBookReadBinding.inflate(ActivityBookReadBinding.java:73)
	at io.legado.app.databinding.ActivityBookReadBinding.inflate(ActivityBookReadBinding.java:67)
	at io.legado.app.ui.book.read.BaseReadBookActivity$special$$inlined$viewBindingActivity$default$1.invoke(ActivityViewBindings.kt:24)
	at io.legado.app.ui.book.read.BaseReadBookActivity$special$$inlined$viewBindingActivity$default$1.invoke(ActivityViewBindings.kt:16)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.legado.app.ui.book.read.BaseReadBookActivity.getBinding(BaseReadBookActivity.kt:45)
	at io.legado.app.ui.book.read.BaseReadBookActivity.upNavigationBar(BaseReadBookActivity.kt:166)
	at io.legado.app.ui.book.read.BaseReadBookActivity.upNavigationBarColor(BaseReadBookActivity.kt:155)
	at io.legado.app.base.BaseActivity.setupSystemBar(BaseActivity.kt:173)
	at io.legado.app.base.BaseActivity.onCreate(BaseActivity.kt:70)
	at io.legado.app.ui.book.read.BaseReadBookActivity.onCreate(BaseReadBookActivity.kt:60)
	at android.app.Activity.performCreate(Activity.java:7372)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
	at android.app.ActivityThread.-wrap12(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
Caused by: java.lang.ExceptionInInitializerError
	at io.legado.app.ui.book.read.page.provider.ChapterProvider.getTypeface(ChapterProvider.kt:85)
	at io.legado.app.ui.book.read.page.PageView.upTipStyle(PageView.kt:130)
	at io.legado.app.ui.book.read.page.PageView.upStyle(PageView.kt:63)
	at io.legado.app.ui.book.read.page.PageView.<init>(PageView.kt:55)
	at io.legado.app.ui.book.read.page.ReadView$nextPage$2.invoke(ReadView.kt:50)
	at io.legado.app.ui.book.read.page.ReadView$nextPage$2.invoke(ReadView.kt:50)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.legado.app.ui.book.read.page.ReadView.getNextPage(ReadView.kt:50)
	at io.legado.app.ui.book.read.page.ReadView.<init>(ReadView.kt:98)
	... 32 more
Caused by: java.lang.NullPointerException: DEFAULT must not be null
	at io.legado.app.ui.book.read.page.provider.ChapterProvider.<clinit>(ChapterProvider.kt:85)
	... 41 more
android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class io.legado.app.ui.book.read.page.ReadView
Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class io.legado.app.ui.book.read.page.ReadView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
	at android.view.LayoutInflater.createView(LayoutInflater.java:658)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at io.legado.app.databinding.ActivityBookReadBinding.inflate(ActivityBookReadBinding.java:73)
	at io.legado.app.databinding.ActivityBookReadBinding.inflate(ActivityBookReadBinding.java:67)
	at io.legado.app.ui.book.read.BaseReadBookActivity$special$$inlined$viewBindingActivity$default$1.invoke(ActivityViewBindings.kt:24)
	at io.legado.app.ui.book.read.BaseReadBookActivity$special$$inlined$viewBindingActivity$default$1.invoke(ActivityViewBindings.kt:16)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.legado.app.ui.book.read.BaseReadBookActivity.getBinding(BaseReadBookActivity.kt:45)
	at io.legado.app.ui.book.read.BaseReadBookActivity.upNavigationBar(BaseReadBookActivity.kt:166)
	at io.legado.app.ui.book.read.BaseReadBookActivity.upNavigationBarColor(BaseReadBookActivity.kt:155)
	at io.legado.app.base.BaseActivity.setupSystemBar(BaseActivity.kt:173)
	at io.legado.app.base.BaseActivity.onCreate(BaseActivity.kt:70)
	at io.legado.app.ui.book.read.BaseReadBookActivity.onCreate(BaseReadBookActivity.kt:60)
	at android.app.Activity.performCreate(Activity.java:7372)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
	at android.app.ActivityThread.-wrap12(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
Caused by: java.lang.ExceptionInInitializerError
	at io.legado.app.ui.book.read.page.provider.ChapterProvider.getTypeface(ChapterProvider.kt:85)
	at io.legado.app.ui.book.read.page.PageView.upTipStyle(PageView.kt:130)
	at io.legado.app.ui.book.read.page.PageView.upStyle(PageView.kt:63)
	at io.legado.app.ui.book.read.page.PageView.<init>(PageView.kt:55)
	at io.legado.app.ui.book.read.page.ReadView$nextPage$2.invoke(ReadView.kt:50)
	at io.legado.app.ui.book.read.page.ReadView$nextPage$2.invoke(ReadView.kt:50)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.legado.app.ui.book.read.page.ReadView.getNextPage(ReadView.kt:50)
	at io.legado.app.ui.book.read.page.ReadView.<init>(ReadView.kt:98)
	... 32 more
Caused by: java.lang.NullPointerException: DEFAULT must not be null
	at io.legado.app.ui.book.read.page.provider.ChapterProvider.<clinit>(ChapterProvider.kt:85)
	... 41 more
android.view.InflateException: Binary XML file line #7: Error inflating class io.legado.app.ui.book.read.page.ReadView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
	at android.view.LayoutInflater.createView(LayoutInflater.java:658)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at io.legado.app.databinding.ActivityBookReadBinding.inflate(ActivityBookReadBinding.java:73)
	at io.legado.app.databinding.ActivityBookReadBinding.inflate(ActivityBookReadBinding.java:67)
	at io.legado.app.ui.book.read.BaseReadBookActivity$special$$inlined$viewBindingActivity$default$1.invoke(ActivityViewBindings.kt:24)
	at io.legado.app.ui.book.read.BaseReadBookActivity$special$$inlined$viewBindingActivity$default$1.invoke(ActivityViewBindings.kt:16)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.legado.app.ui.book.read.BaseReadBookActivity.getBinding(BaseReadBookActivity.kt:45)
	at io.legado.app.ui.book.read.BaseReadBookActivity.upNavigationBar(BaseReadBookActivity.kt:166)
	at io.legado.app.ui.book.read.BaseReadBookActivity.upNavigationBarColor(BaseReadBookActivity.kt:155)
	at io.legado.app.base.BaseActivity.setupSystemBar(BaseActivity.kt:173)
	at io.legado.app.base.BaseActivity.onCreate(BaseActivity.kt:70)
	at io.legado.app.ui.book.read.BaseReadBookActivity.onCreate(BaseReadBookActivity.kt:60)
	at android.app.Activity.performCreate(Activity.java:7372)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
	at android.app.ActivityThread.-wrap12(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
Caused by: java.lang.ExceptionInInitializerError
	at io.legado.app.ui.book.read.page.provider.ChapterProvider.getTypeface(ChapterProvider.kt:85)
	at io.legado.app.ui.book.read.page.PageView.upTipStyle(PageView.kt:130)
	at io.legado.app.ui.book.read.page.PageView.upStyle(PageView.kt:63)
	at io.legado.app.ui.book.read.page.PageView.<init>(PageView.kt:55)
	at io.legado.app.ui.book.read.page.ReadView$nextPage$2.invoke(ReadView.kt:50)
	at io.legado.app.ui.book.read.page.ReadView$nextPage$2.invoke(ReadView.kt:50)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.legado.app.ui.book.read.page.ReadView.getNextPage(ReadView.kt:50)
	at io.legado.app.ui.book.read.page.ReadView.<init>(ReadView.kt:98)
	... 32 more
Caused by: java.lang.NullPointerException: DEFAULT must not be null
	at io.legado.app.ui.book.read.page.provider.ChapterProvider.<clinit>(ChapterProvider.kt:85)
	... 41 more
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
	at android.view.LayoutInflater.createView(LayoutInflater.java:658)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at io.legado.app.databinding.ActivityBookReadBinding.inflate(ActivityBookReadBinding.java:73)
	at io.legado.app.databinding.ActivityBookReadBinding.inflate(ActivityBookReadBinding.java:67)
	at io.legado.app.ui.book.read.BaseReadBookActivity$special$$inlined$viewBindingActivity$default$1.invoke(ActivityViewBindings.kt:24)
	at io.legado.app.ui.book.read.BaseReadBookActivity$special$$inlined$viewBindingActivity$default$1.invoke(ActivityViewBindings.kt:16)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.legado.app.ui.book.read.BaseReadBookActivity.getBinding(BaseReadBookActivity.kt:45)
	at io.legado.app.ui.book.read.BaseReadBookActivity.upNavigationBar(BaseReadBookActivity.kt:166)
	at io.legado.app.ui.book.read.BaseReadBookActivity.upNavigationBarColor(BaseReadBookActivity.kt:155)
	at io.legado.app.base.BaseActivity.setupSystemBar(BaseActivity.kt:173)
	at io.legado.app.base.BaseActivity.onCreate(BaseActivity.kt:70)
	at io.legado.app.ui.book.read.BaseReadBookActivity.onCreate(BaseReadBookActivity.kt:60)
	at android.app.Activity.performCreate(Activity.java:7372)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
	at android.app.ActivityThread.-wrap12(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
Caused by: java.lang.ExceptionInInitializerError
	at io.legado.app.ui.book.read.page.provider.ChapterProvider.getTypeface(ChapterProvider.kt:85)
	at io.legado.app.ui.book.read.page.PageView.upTipStyle(PageView.kt:130)
	at io.legado.app.ui.book.read.page.PageView.upStyle(PageView.kt:63)
	at io.legado.app.ui.book.read.page.PageView.<init>(PageView.kt:55)
	at io.legado.app.ui.book.read.page.ReadView$nextPage$2.invoke(ReadView.kt:50)
	at io.legado.app.ui.book.read.page.ReadView$nextPage$2.invoke(ReadView.kt:50)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.legado.app.ui.book.read.page.ReadView.getNextPage(ReadView.kt:50)
	at io.legado.app.ui.book.read.page.ReadView.<init>(ReadView.kt:98)
	... 32 more
Caused by: java.lang.NullPointerException: DEFAULT must not be null
	at io.legado.app.ui.book.read.page.provider.ChapterProvider.<clinit>(ChapterProvider.kt:85)
	... 41 more
java.lang.ExceptionInInitializerError
	at io.legado.app.ui.book.read.page.provider.ChapterProvider.getTypeface(ChapterProvider.kt:85)
	at io.legado.app.ui.book.read.page.PageView.upTipStyle(PageView.kt:130)
	at io.legado.app.ui.book.read.page.PageView.upStyle(PageView.kt:63)
	at io.legado.app.ui.book.read.page.PageView.<init>(PageView.kt:55)
	at io.legado.app.ui.book.read.page.ReadView$nextPage$2.invoke(ReadView.kt:50)
	at io.legado.app.ui.book.read.page.ReadView$nextPage$2.invoke(ReadView.kt:50)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.legado.app.ui.book.read.page.ReadView.getNextPage(ReadView.kt:50)
	at io.legado.app.ui.book.read.page.ReadView.<init>(ReadView.kt:98)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
	at android.view.LayoutInflater.createView(LayoutInflater.java:658)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at io.legado.app.databinding.ActivityBookReadBinding.inflate(ActivityBookReadBinding.java:73)
	at io.legado.app.databinding.ActivityBookReadBinding.inflate(ActivityBookReadBinding.java:67)
	at io.legado.app.ui.book.read.BaseReadBookActivity$special$$inlined$viewBindingActivity$default$1.invoke(ActivityViewBindings.kt:24)
	at io.legado.app.ui.book.read.BaseReadBookActivity$special$$inlined$viewBindingActivity$default$1.invoke(ActivityViewBindings.kt:16)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.legado.app.ui.book.read.BaseReadBookActivity.getBinding(BaseReadBookActivity.kt:45)
	at io.legado.app.ui.book.read.BaseReadBookActivity.upNavigationBar(BaseReadBookActivity.kt:166)
	at io.legado.app.ui.book.read.BaseReadBookActivity.upNavigationBarColor(BaseReadBookActivity.kt:155)
	at io.legado.app.base.BaseActivity.setupSystemBar(BaseActivity.kt:173)
	at io.legado.app.base.BaseActivity.onCreate(BaseActivity.kt:70)
	at io.legado.app.ui.book.read.BaseReadBookActivity.onCreate(BaseReadBookActivity.kt:60)
	at android.app.Activity.performCreate(Activity.java:7372)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
	at android.app.ActivityThread.-wrap12(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
Caused by: java.lang.NullPointerException: DEFAULT must not be null
	at io.legado.app.ui.book.read.page.provider.ChapterProvider.<clinit>(ChapterProvider.kt:85)
	... 41 more
java.lang.NullPointerException: DEFAULT must not be null
	at io.legado.app.ui.book.read.page.provider.ChapterProvider.<clinit>(ChapterProvider.kt:85)
	at io.legado.app.ui.book.read.page.provider.ChapterProvider.getTypeface(ChapterProvider.kt:85)
	at io.legado.app.ui.book.read.page.PageView.upTipStyle(PageView.kt:130)
	at io.legado.app.ui.book.read.page.PageView.upStyle(PageView.kt:63)
	at io.legado.app.ui.book.read.page.PageView.<init>(PageView.kt:55)
	at io.legado.app.ui.book.read.page.ReadView$nextPage$2.invoke(ReadView.kt:50)
	at io.legado.app.ui.book.read.page.ReadView$nextPage$2.invoke(ReadView.kt:50)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.legado.app.ui.book.read.page.ReadView.getNextPage(ReadView.kt:50)
	at io.legado.app.ui.book.read.page.ReadView.<init>(ReadView.kt:98)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
	at android.view.LayoutInflater.createView(LayoutInflater.java:658)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at io.legado.app.databinding.ActivityBookReadBinding.inflate(ActivityBookReadBinding.java:73)
	at io.legado.app.databinding.ActivityBookReadBinding.inflate(ActivityBookReadBinding.java:67)
	at io.legado.app.ui.book.read.BaseReadBookActivity$special$$inlined$viewBindingActivity$default$1.invoke(ActivityViewBindings.kt:24)
	at io.legado.app.ui.book.read.BaseReadBookActivity$special$$inlined$viewBindingActivity$default$1.invoke(ActivityViewBindings.kt:16)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.legado.app.ui.book.read.BaseReadBookActivity.getBinding(BaseReadBookActivity.kt:45)
	at io.legado.app.ui.book.read.BaseReadBookActivity.upNavigationBar(BaseReadBookActivity.kt:166)
	at io.legado.app.ui.book.read.BaseReadBookActivity.upNavigationBarColor(BaseReadBookActivity.kt:155)
	at io.legado.app.base.BaseActivity.setupSystemBar(BaseActivity.kt:173)
	at io.legado.app.base.BaseActivity.onCreate(BaseActivity.kt:70)
	at io.legado.app.ui.book.read.BaseReadBookActivity.onCreate(BaseReadBookActivity.kt:60)
	at android.app.Activity.performCreate(Activity.java:7372)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
	at android.app.ActivityThread.-wrap12(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

### 阅读版本 / Legado version

3.23.07162

### Android版本 / Android version

8.0.0

### 机型 / Model

Huawei Honor 7x

**Comment by 821938089** [comment]
试一下刚出的测试版

**Comment by KJZH001** [comment]
> 试一下刚出的测试版

感谢，确实不会闪退了

不过我有个问题想问一下，在tg中似乎有人提到了是字体的问题，请问这个确实是字体造成的问题吗？

目前我使用的是和之前相同的字体文件，区别是之前是用系统主题卡bug装上去的，现在bug卡不了了就用magisk刷模块刷上去的

**Comment by 821938089** [comment]
这个不太清楚，你可以试试换回默认的看看行不行，这报错是获取不到字体的默认字形导致的，可能你刷的模块字体的字形不全或比较特殊，没有默认字形

**Comment by KJZH001** [comment]
> 这个不太清楚，你可以试试换回默认的看看行不行，这报错是获取不到字体的默认字形导致的，可能你刷的模块字体的字形不全或比较特殊，没有默认字形

好的，那么我等会去下个老的版本的共存包在禁用模块的情况下尝试会不会闪退

另外，我注意到目前的这个测试版有个误伤大雅的小bug，你们可以酌情考虑一下要不要修，因为本质不会造成什么影响，我就不另外开个issue了

导入旧版数据后，如果旧版使用的是旧版的蓝色默认主题，导入后会发现主题还是棕色的默认主题，然后只有下面选颜色的地方变成了蓝色

这个时候如果去修改颜色会导致闪退，并且不会保存修改的颜色

解决方法是切换到夜间再切换回来，一切就能恢复正常

**Comment by 821938089** [comment]
发下日志看看
