### ISSUE TITLE
导入大体积文件时内存超限

### ISSUE THREAD

**Issue by liu-zhou-L** [gedoor/legado#3370]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

导入492.8MB大体积文件时报错失败

### 复现步骤 / How to reproduce

主页“添加本地”时选择一个大体积文件

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

java.lang.OutOfMemoryError: Failed to allocate a 4011520 byte allocation with 2256320 free bytes and 2203KB until OOM, target footprint 268435456, growth limit 268435456
	at java.lang.StringFactory.newStringFromUtf8Bytes(Native Method)
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:80)
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:54)
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:46)
	at com.google.android.material.internal.a0.a(SourceFile:261)
	at io.legado.app.model.localBook.a.f(SourceFile:78)
	at io.legado.app.model.localBook.a.<init>(SourceFile:24)
	at d7.f.k(SourceFile:44)
	at d7.f.w(SourceFile:23)
	at io.legado.app.model.localBook.h.g(SourceFile:452)
	at io.legado.app.ui.book.import.local.r.invokeSuspend(SourceFile:105)
	at io.legado.app.ui.book.import.local.r.invoke(SourceFile:2)
	at io.legado.app.ui.book.import.local.r.invoke(SourceFile:1)
	at io.legado.app.help.coroutine.h.invokeSuspend(SourceFile:61)
	at n4.a.resumeWith(SourceFile:9)
	at kotlinx.coroutines.i0.run(SourceFile:128)
	at com.bumptech.glide.load.engine.a.run(SourceFile:162)
	at g6.k.run(SourceFile:3)
	at g6.b.run(SourceFile:99)

### 阅读版本 / Legado version

3.23.073011

### Android版本 / Android version

Android 13

### 机型 / Model

Redmi Note 12 Turbo

**Comment by 821938089** [comment]
发一下文件

**Comment by liu-zhou-L** [comment]
> 发一下文件

[file](https://gateway.pinata.cloud/ipfs/bafykbzacednh24rn6mkedomqkrn3qealyqbm7bntq5oieycovlxdnud6defak?filename=编程随想的博客 -- 编程随想,非墨盟 -- 2021 -- 编程随想 -- 013442a110bce9ae2ccc8a060175b554 -- Anna’s Archive.epub)

**Comment by liu-zhou-L** [comment]
> 发一下文件

https://gateway.pinata.cloud/ipfs/bafykbzacednh24rn6mkedomqkrn3qealyqbm7bntq5oieycovlxdnud6defak?filename=编程随想的博客 -- 编程随想,非墨盟 -- 2021 -- 编程随想 -- 013442a110bce9ae2ccc8a060175b554 -- Anna’s Archive.epub

**Comment by 821938089** [comment]
最新测试版修好了

**Comment by pinoren** [comment]
> 最新测试版修好了

话说7月份到现在一直都没有发布新的正式版喔。。。

**Comment by liu-zhou-L** [comment]
> 最新测试版修好了

很多图片加载失败，还有章节打开不了

加载正文出错
Failed to allocate a 29081120 byte allocation with 24811608 free bytes and 23MB until OOM, target footprint 268435456, growth limit 268435456

**Comment by 821938089** [comment]
单章内容太多，加载不了，换别的软件看吧

**Comment by pinoren** [comment]
我想你可以把这玩意儿转换成txt，然后再导入可能就解决了。

**Comment by liu-zhou-L** [comment]
> 我想你可以把这玩意儿转换成txt，然后再导入可能就解决了。

但是这个电子书要的就是结构，它本身的目录分类做的很好，跳转很方便，而且它图片很多，转成txt不久只剩文字了么 😂
