### ISSUE TITLE
过多章节无法导出

### ISSUE THREAD

**Issue by Goojoe** [gedoor/legado#3411]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

导出过多章节提示opreation not permitted
![Screenshot_2023-10-09-23-29-41-908_io legado app release-edit](https://github.com/gedoor/legado/assets/78355492/9e77eede-d5e3-4f8d-985f-0f7c41cf93f1)
本地也无法导出

### 复现步骤 / How to reproduce

1

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

java.io.IOException: Operation not permitted
	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
	at java.io.File.createNewFile(File.java:1006)
	at com.google.common.collect.c4.y(SourceFile:21)
	at io.legado.app.service.ExportBookService.j(SourceFile:107)
	at io.legado.app.service.ExportBookService.d(SourceFile:69)
	at io.legado.app.service.h1.invokeSuspend(SourceFile:253)
	at m4.a.resumeWith(SourceFile:9)
	at kotlinx.coroutines.i0.run(SourceFile:128)
	at com.bumptech.glide.load.engine.a.run(SourceFile:162)
	at g6.k.run(SourceFile:3)
	at g6.b.run(SourceFile:99)

### 阅读版本 / Legado version

3.23.100718

### Android版本 / Android version

Android 13

### 机型 / Model

MotorolaEdgeX30

**Comment by 821938089** [comment]
重新设置导出文件夹
