### ISSUE TITLE
调试订阅源时崩溃

### ISSUE THREAD

**Issue by skybbk1998** [gedoor/legado#3513]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

编辑好订阅源，测试时崩溃

### 复现步骤 / How to reproduce

订阅源链接 https://shuyuan.mgz6.cn/shuyuan/3dd247d6a96c6051f10c84baa1fa671f.json

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

```
SDK_INT=33
WebViewUserAgent=Mozilla/5.0 (Linux; Android 13; 23049RAD8C Build/TKQ1.221114.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.66 Mobile Safari/537.36
MODEL=23049RAD8C
RELEASE=13
MANUFACTURER=Xiaomi
versionName=3.23.111312
versionCode=14888
BRAND=Redmi
java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 1
{{@@div.pbK_RyK}}
 ^
	at com.android.icu.util.regex.PatternNative.compileImpl(Native Method)
	at com.android.icu.util.regex.PatternNative.<init>(PatternNative.java:53)
	at com.android.icu.util.regex.PatternNative.create(PatternNative.java:49)
	at java.util.regex.Pattern.compile(Pattern.java:1446)
	at java.util.regex.Pattern.<init>(Pattern.java:1421)
	at java.util.regex.Pattern.compile(Pattern.java:972)
	at kotlin.text.o.<init>(SourceFile:3)
	at io.legado.app.ui.rss.read.c.shouldInterceptRequest(SourceFile:95)
	at WV.d6.a(chromium-TrichromeWebViewGoogle6432.aab-stable-604506633:86)
	at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(chromium-TrichromeWebViewGoogle6432.aab-stable-604506633:15)

```

### 阅读版本 / Legado version

3.23.111312

### Android版本 / Android version

Android 13

### 机型 / Model

Redmi note 12 Turbo

**Comment by 821938089** [comment]
黑白名单规则只能写正则

**Comment by skybbk1998** [comment]
> 黑白名单规则只能写正则

感谢
