### ISSUE TITLE
书源调试时崩溃

### ISSUE THREAD

**Issue by skybbk1998** [gedoor/legado#3520]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

* 在对 http://www.limkokwingchina.com/ 制作书源时，调试"系统"关键词，出来的结果有5万多个，此时进行某些操作会崩溃*

### 复现步骤 / How to reproduce

- 书源链接： 
http://sy.legado1.top/sy.php/c45c30588cf3cc66d1d21406255529d7.json
- 复现步骤：
调试搜索关键字"系统"，在未完全加载完毕时查看搜索源码、或者进行其他操作

　　第一次崩溃后再重复操作就不会崩溃了

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

```
SDK_INT=33
WebViewUserAgent=Mozilla/5.0 (Linux; Android 13; 23049RAD8C Build/TKQ1.221114.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.66 Mobile Safari/537.36
MODEL=23049RAD8C
RELEASE=13
MANUFACTURER=Xiaomi
versionName=3.23.112116
versionCode=14896
BRAND=Redmi
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 11612540 bytes
	at android.app.ActivityClient.activityStopped(ActivityClient.java:102)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8395)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: android.os.TransactionTooLargeException: data parcel size 11612540 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:646)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1266)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:99)
	... 9 more
android.os.TransactionTooLargeException: data parcel size 11612540 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:646)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1266)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:99)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8395)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

### 阅读版本 / Legado version

3.23.112116

### Android版本 / Android version

Android 13

### 机型 / Model

Redmi note 12 Turbo

**Comment by 821938089** [comment]
已修复

**Comment by skybbk1998** [comment]
> 已修复

感谢
