### ISSUE TITLE
RSS加载图片崩溃

### ISSUE THREAD

**Issue by old-yellow-ox** [gedoor/legado#3523]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://kunfei.lanzoui.com/b0f810h4b)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

SDK_INT=31
WebViewUserAgent=Mozilla/5.0 (Linux; Android 12; LIO-AL00 Build/HUAWEILIO-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.88 Mobile Safari/537.36
MODEL=LIO-AL00
RELEASE=12
MANUFACTURER=HUAWEI
versionName=3.23.112312
versionCode=14897
BRAND=HUAWEI
android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=1, totalRows=2
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1047)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:858)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:153)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:123)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:255)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:287)
	at io.legado.app.data.dao.RssArticleDao_Impl$6.call(SourceFile:4)
	at io.legado.app.data.dao.RssArticleDao_Impl$6.call(SourceFile:1)
	at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.invokeSuspend(SourceFile:90)
	at h7.a.resumeWith(SourceFile:9)
	at kotlinx.coroutines.l0.run(SourceFile:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:930)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [y1{Cancelling}@319bde1, Dispatchers.Main.immediate]

### 复现步骤 / How to reproduce

RSS图片是base64字符串，直接用url不加载图片。用java.ajax(url)加载出来了，但是会突然报错。普通jpg\png图片没问题。

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

最新正式

### Android版本 / Android version

12

### 机型 / Model

华为

**Comment by old-yellow-ox** [comment]
还有一个问题，为什么清理崩溃日志，会把我的备份目录删了？文件夹直接没了

**Comment by 821938089** [comment]
有规则获取到的数据太大了
应该不会吧，只会删除crash文件夹

**Comment by old-yellow-ox** [comment]
第一个能解决吗？他的图片是base64字符串，有点长。
第二个我专门测试了下，确实被删除了。第一个报错的日志点清除之后，备份的目录没了。

**Comment by old-yellow-ox** [comment]
第一个能解决吗？他的图片是base64字符串，有点长。
第二个我专门测试了下，确实被删除了。第一个报错的日志点清除之后，备份目录没了。

**Comment by 821938089** [comment]
用java.put来存
测试版已修复

**Comment by old-yellow-ox** [comment]
java.put来存？java.put(‘image’,result)
是这样吗？但是用的时候不是要java.get()吗？这样处理后和规则直接取值不一样吗？

**Comment by 821938089** [comment]
我想了想好像不太行，估计是没办法了

**Comment by old-yellow-ox** [comment]
那算了吧，不加载图片了。
