### ISSUE TITLE
最新测试版无法调用系统下载器创建下载

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3568]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

最近几个版本，在小米手机上无法创建下载。  另外上次反馈的无法调用外部浏览器打开url，在小米手机上依然存在，在我另一个品牌的平板上未出现。使用测试版12051956还正常，之后的版本这两个问题一起出现

### 复现步骤 / How to reproduce

订阅源找个蓝奏云下载文件，会报错

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

SDK_INT=34
WebViewUserAgent=Mozilla/5.0 (Linux; Android 14; 22127RK46C Build/UKQ1.230804.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36
MODEL=22127RK46C
RELEASE=14
MANUFACTURER=Xiaomi
versionName=3.23.120923
versionCode=14931
BRAND=Redmi
java.lang.RuntimeException: Unable to create service io.legado.app.service.DownloadService: java.lang.SecurityException: io.legado.app.release: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4887)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2406)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.SecurityException: io.legado.app.release: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6193)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1863)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1803)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1791)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:766)
	at io.legado.app.service.DownloadService.onCreate(SourceFile:13)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4874)
	... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14680)
	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:12174)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3173)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2856)
	at android.os.Binder.execTransactInternal(Binder.java:1346)

java.lang.SecurityException: io.legado.app.release: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6193)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1863)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1803)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1791)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:766)
	at io.legado.app.service.DownloadService.onCreate(SourceFile:13)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4874)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2406)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14680)
	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:12174)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3173)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2856)
	at android.os.Binder.execTransactInternal(Binder.java:1346)

android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14680)
	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:12174)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3173)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2856)
	at android.os.Binder.execTransactInternal(Binder.java:1346)

### 阅读版本 / Legado version

3.23.12080244

### Android版本 / Android version

Android 14

### 机型 / Model

Redmi k60 pro

**Comment by 821938089** [comment]
试一下最新测试版看看修好了没

**Comment by zousizhe** [comment]
> 试一下最新测试版看看修好了没

浏览器这下打不开了

![Screenshot_2023-12-10-11-04-26-431_io legado app release](https://github.com/gedoor/legado/assets/37259360/f9e24ba1-565e-4e3c-b572-ee60eadcd879)

**Comment by 821938089** [comment]
那下载呢

**Comment by zousizhe** [comment]
> 那下载呢

下载无问题

**Comment by 821938089** [comment]
再试一下最新测试版
