### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by superskysheep** [gedoor/legado#3665]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

闪退，或者有这个再闪退
![Screenshot_20240122_185747](https://github.com/gedoor/legado/assets/157366726/b67fb6a7-6d6c-4bf4-8e49-d9fc48d1924c)

### 复现步骤 / How to reproduce

点击图标大概率闪退，长按图标进入二级界面能直接进去

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

SDK_INT=34
WebViewUserAgent=Mozilla/5.0 (Linux; Android 14; V2307A Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36
MODEL=V2307A
RELEASE=14
MANUFACTURER=vivo
versionName=5.0.1
versionCode=501
BRAND=vivo
java.lang.SecurityException: To use the sampling rate of 0 microseconds, app needs to declare the normal permission HIGH_SAMPLING_RATE_SENSORS.
	at android.hardware.SystemSensorManager$BaseEventQueue.enableSensor(SystemSensorManager.java:1044)
	at android.hardware.SystemSensorManager$BaseEventQueue.addSensor(SystemSensorManager.java:964)
	at android.hardware.SystemSensorManager.registerListenerImpl(SystemSensorManager.java:382)
	at android.hardware.SensorManager.registerListener(SensorManager.java:860)
	at android.hardware.SensorManager.registerListener(SensorManager.java:767)
	at com.alliance.ssp.ad.g.c.a(NMSplashAdImpl.java:893)
	at com.alliance.ssp.ad.g.c.b(NMSplashAdImpl.java:258)
	at com.alliance.ssp.ad.g.c.a(NMSplashAdImpl.java:72)
	at com.alliance.ssp.ad.g.c$9.handleMessage(NMSplashAdImpl.java:1006)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:328)
	at android.app.ActivityThread.main(ActivityThread.java:9159)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)

### 阅读版本 / Legado version

5.0.1

### Android版本 / Android version

Android14

### 机型 / Model

iQOO12

**Comment by htc159243768** [comment]
可以换一个webvice，浏览器内核不稳定的原因
