### ISSUE TITLE
同时缓存多本书籍会崩溃，线程选择10或者10以下同样崩溃，后台下载有时候会下着下着莫名就停止了，或者不继续下载。

### ISSUE THREAD

**Issue by ssswww0004** [gedoor/legado#3698]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [x] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

我添加到书架了很多本书，书源都是一个源，书本的数量有大概上千本，在选择缓存的时候，如果一本一本的缓存没有什么大问题，但是选择所有书籍缓存的话过十几秒就会崩溃，线程选择的是10，或者10以下，同样都会崩溃。但是这个问题是在换手机后出现的，之前用的华为鸿蒙系统，好像没有这个问题，可以选择全部缓存，现在换了一个iqoo 12的手机，系统是橘子4，安卓14，就出现了这个现象。后台下载有时候会下着下着莫名就停止了，或者不继续下载。

### 复现步骤 / How to reproduce

只要选择数量较多的书籍同时缓存就会出现，崩溃，下载显示为0.

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

SDK_INT=34
MODEL=V2307A
RELEASE=14
MANUFACTURER=vivo
BRAND=vivo
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 407096 free bytes and 397KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at j$.util.concurrent.ConcurrentHashMap$EntryIterator.next(Unknown Source:13)
	at j$.util.concurrent.ConcurrentHashMap$EntryIterator.next(Unknown Source:0)
	at io.legado.app.model.u.d(SourceFile:18)
	at io.legado.app.ui.book.cache.w.invoke(SourceFile:2)
	at io.legado.app.ui.book.cache.w.invoke(SourceFile:1)
	at io.legado.app.utils.EventBusExtensionsKt$observeEvent$o$1.onChanged(SourceFile:3)
	at com.jeremyliao.liveeventbus.core.LiveEventBusCore$ObserverWrapper.onChanged(SourceFile:36)
	at androidx.lifecycle.LiveData.considerNotify(SourceFile:30)
	at androidx.lifecycle.LiveData.dispatchingValue(SourceFile:45)
	at androidx.lifecycle.LiveData.setValue(SourceFile:15)
	at androidx.lifecycle.MutableLiveData.setValue(SourceFile:1)
	at com.jeremyliao.liveeventbus.core.LiveEventBusCore$LiveEvent.postInternal(SourceFile:38)
	at com.jeremyliao.liveeventbus.core.LiveEventBusCore$LiveEvent.access$1500(SourceFile:1)
	at com.jeremyliao.liveeventbus.core.LiveEventBusCore$LiveEvent$PostValueTask.run(SourceFile:5)
	at android.os.Handler.handleCallback(Handler.java:983)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:328)
	at android.app.ActivityThread.main(ActivityThread.java:9159)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)

SDK_INT=34
WebViewUserAgent=Mozilla/5.0 (Linux; Android 14; V2307A Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.230 Mobile Safari/537.36
MODEL=V2307A
RELEASE=14
MANUFACTURER=vivo
versionName=3.23.110211
versionCode=14860
BRAND=vivo
java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 138936 free bytes and 135KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1610)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1071)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1131)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1042)

### 阅读版本 / Legado version

3.23.110211

### Android版本 / Android version

Android  14

### 机型 / Model

iqoo  12

**Comment by ssswww0004** [comment]
大佬好的，上传了。测试版点击全部缓存就直接崩溃！正式版还能持续个十几秒
[heap-dump-1707098285030 (2).zip](https://github.com/gedoor/legado/files/14159703/heap-dump-1707098285030.2.zip)

**Comment by 821938089** [comment]
试试最新测试版

**Comment by ssswww0004** [comment]
大佬，你更新的最新的测试版在哪里下载啊！

**Comment by 821938089** [comment]
https://github.com/gedoor/legado/actions/workflows/test.yml
第一个里面的Artifacts

**Comment by ssswww0004** [comment]
我去，大佬，这个最新版本真的不崩溃了，感觉就算选择所有书籍缓存都只是在循序渐进的下载，现在过去5分钟了还没有崩溃。我再试试后台下载看看！会不会自己断！

**Comment by ssswww0004** [comment]
大佬，试了一下，现在全部缓存也不会崩溃了，但是在手机上设置好免杀，白名单，允许自启动，后台允许高耗电后还是会出现后台缓存的时候，过了几分钟或者十几分钟后，屏幕上的正在缓存通知图标消失，后台停止缓存，但是打开软件，软件并没有被杀或者退出，仍然是打开的状态，并且崩溃日志里面也没有任何信息。大佬请问这个问题是阅读的问题还是手机系统设置的问题，但是手机几乎关系后台的设置我全部都放行了啊！

**Comment by 821938089** [comment]
系统问题

**Comment by ssswww0004** [comment]
大佬，反馈下，昨天晚上测试的时候我打开了后台关联启动，挂了一段时候后台后，缓存通知图标都还在，但是点开通知显示所有的缓存数量都为零，书肯定是没有缓存完的，其实也就没有在缓存了，只是缓存通知图标还在显示，但是也没有崩溃日志。还有这个问题解决后，大佬是不是要更新到正式版里面？
