### ISSUE TITLE
离线缓存无法上传导出书籍

### ISSUE THREAD

**Issue by Goojoe** [gedoor/legado#3701]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

导出报错
Attempt to invoke virtual method 'int java.lang.String.compareToIgnoreCase(java.lang.String)' on a null object reference
本地有书籍，没有上传到Webdav云端

### 复现步骤 / How to reproduce

1

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.compareToIgnoreCase(java.lang.String)' on a null object reference
	at androidx.media3.datasource.cache.c.compare(SourceFile:55)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:356)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1344)
	at java.util.ArrayList.sort(ArrayList.java:1738)
	at java.util.Collections.sort(Collections.java:210)
	at a9.g.T(SourceFile:98)
	at a9.d.a(SourceFile:327)
	at io.legado.app.service.ExportBookService.l(SourceFile:165)
	at io.legado.app.service.ExportBookService.d(SourceFile:70)
	at io.legado.app.service.s1.invokeSuspend(SourceFile:306)
	at d7.a.resumeWith(SourceFile:9)
	at kotlinx.coroutines.m0.run(SourceFile:127)
	at com.bumptech.glide.load.engine.a.run(SourceFile:21)
	at w8.k.run(SourceFile:3)
	at w8.b.run(SourceFile:96)
```

### 阅读版本 / Legado version

3.24.020713(15053)

### Android版本 / Android version

Android 14

### 机型 / Model

Realme GT neo5 se

**Comment by 821938089** [comment]
不能复现
