### ISSUE TITLE
最新测试版全文搜索结果选中就报错

### ISSUE THREAD

**Issue by zousizhe** [gedoor/legado#3743]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

全文搜索报错

### 复现步骤 / How to reproduce

全文搜索选中任意一个结果就报错

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at io.legado.app.ui.book.read.ReadBookActivity.o0(SourceFile:124)
	at io.legado.app.ui.book.read.n2.invoke(SourceFile:1)
	at io.legado.app.ui.book.read.n2.invoke(SourceFile:2)
	at io.legado.app.model.e1.invoke(SourceFile:2)
	at io.legado.app.model.e1.invoke(SourceFile:1)
	at io.legado.app.model.a1.invoke(SourceFile:2)
	at io.legado.app.model.a1.invoke(SourceFile:1)
	at io.legado.app.model.b1.invoke(SourceFile:2)
	at io.legado.app.model.b1.invoke(SourceFile:1)
	at io.legado.app.model.x0.invokeSuspend(SourceFile:14)
	at io.legado.app.model.x0.invoke(SourceFile:2)
	at io.legado.app.model.x0.invoke(SourceFile:1)
	at io.legado.app.help.coroutine.j.invokeSuspend(SourceFile:254)
	at g7.a.resumeWith(SourceFile:9)
	at kotlinx.coroutines.m0.run(SourceFile:127)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8759)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

### 阅读版本 / Legado version

3.24.022315

### Android版本 / Android version

Android 14

### 机型 / Model

Redmi K60 Pro

**Comment by 821938089** [comment]
试试最新测试版
