### ISSUE TITLE
崩溃报错

### ISSUE THREAD

**Issue by Gslw** [gedoor/legado#3846]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

白屏然后崩溃

### 复现步骤 / How to reproduce

换源或加载新章节时

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

SDK_INT=28
WebViewUserAgent=Mozilla/5.0 (Linux; Android 9; STF-AL10 Build/HUAWEISTF-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.105 Mobile Safari/537.36
MODEL=STF-AL10
RELEASE=9
MANUFACTURER=HUAWEI
versionName=3.24.032611
versionCode=15286
BRAND=HONOR
java.lang.NoSuchMethodError: No virtual method setWordSpacing(F)V in class Landroid/graphics/Paint; or its super classes (declaration of 'android.graphics.Paint' appears in /system/framework/framework.jar)
	at androidx.transition.a.q(SourceFile:3)
	at io.legado.app.ui.book.read.page.entities.e.invoke(SourceFile:4)
	at io.legado.app.ui.book.read.page.entities.e.invoke(SourceFile:1)
	at j7.m.getValue(SourceFile:21)
	at io.legado.app.ui.book.read.page.entities.TextLine.checkFastDraw(SourceFile:40)
	at io.legado.app.ui.book.read.page.entities.TextLine.drawTextLine(SourceFile:1)
	at io.legado.app.ui.book.read.page.entities.TextLine.draw(SourceFile:41)
	at io.legado.app.ui.book.read.page.entities.TextPage.drawPage(SourceFile:38)
	at io.legado.app.ui.book.read.page.entities.TextPage.render(SourceFile:36)
	at io.legado.app.ui.book.read.page.entities.TextPage.draw(SourceFile:11)
	at io.legado.app.ui.book.read.page.ContentTextView.onDraw(SourceFile:49)
	at android.view.View.draw(View.java:20635)
	at android.view.View.updateDisplayListIfDirty(View.java:19446)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4385)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4358)
	at android.view.View.updateDisplayListIfDirty(View.java:19406)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4385)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4358)
	at android.view.View.updateDisplayListIfDirty(View.java:19406)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4385)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4358)
	at android.view.View.updateDisplayListIfDirty(View.java:19406)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4385)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4358)
	at android.view.View.updateDisplayListIfDirty(View.java:19406)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4385)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4358)
	at android.view.View.updateDisplayListIfDirty(View.java:19406)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4385)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4358)
	at android.view.View.updateDisplayListIfDirty(View.java:19406)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4385)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4358)
	at android.view.View.updateDisplayListIfDirty(View.java:19406)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4385)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4358)
	at android.view.View.updateDisplayListIfDirty(View.java:19406)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4385)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4358)
	at android.view.View.updateDisplayListIfDirty(View.java:19406)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:740)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:746)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:861)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3627)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3423)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2755)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1677)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7987)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
	at android.view.Choreographer.doCallbacks(Choreographer.java:893)
	at android.view.Choreographer.doFrame(Choreographer.java:812)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7779)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:990)

### 阅读版本 / Legado version

3.24.032611

### Android版本 / Android version

鸿蒙 2.0.0

### 机型 / Model

Honor 9

**Comment by 821938089** [comment]
已修复，试试最新测试版

**Comment by Gslw** [comment]
> 已修复，试试最新测试版

感谢,用了几天应该是没问题了!
