### ISSUE TITLE
【api.md】跨进程调用ReaderProvider出现CursorIndexOutOfBoundsException问题

### ISSUE THREAD

**Issue by Lyon1994** [gedoor/legado#385]
## 场景：
使用[api.md]()的`ContentProvider`方式进行访问数据，出现`CursorIndexOutOfBoundsException`
## 测试代码：
```kotlin
        Handler(Looper.getMainLooper()).post {
            Toast.makeText(
                context,
                context.applicationContext.contentResolver.query(
                    Uri.parse("content://io.legado.app.debug.readerProvider/sources/query"),
                    null, null, null, null
                )!!.apply {
                    moveToFirst()
                }.getString(0),
                Toast.LENGTH_SHORT
            ).show()
        }
```
以上代码在`androidTest`下执行正常，但是如果在另一个app中使用则会出现
```log
    Process: top.fastdroid.yuedu4kindle, PID: 15851
    android.database.CursorIndexOutOfBoundsException: Index -1 requested, with a size of 1
        at android.database.AbstractCursor.checkPosition(AbstractCursor.java:521)
        at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:138)
        at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:52)
        at android.database.CursorWrapper.getString(CursorWrapper.java:141)
        at top.fastdroid.yuedu4kindle.YueduAPI$booksQuery$1.run(YueduAPI.kt:96)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```
## 分析：
在跨进程访问`ContentProvider`时，`Cursor`的传递是经过系统复制后，将复制后的内容转发给客户端进程，所以[`ReaderProvider.kt`](https://github.com/gedoor/legado/edit/master/app/src/main/java/io/legado/app/api/ReaderProvider.kt)中自定义的`SimpleCursor`中每个方法都要写完整才能正确通过系统的复制操作，这里建议继承`android.database.MatrixCursor`来实现自定义的`Cursor`,这样就不用写太多代码了，修改后代码如下：
```kotlin
    /**
     * Simple inner class to deliver json callback data.
     *
     * Only getString() makes sense.
     */
    private class SimpleCursor(data: ReturnData?) : MatrixCursor(arrayOf("result"), 1) {
        private val mData: String = Gson().toJson(data)

        init {
            addRow(arrayOf(mData))
        }

    }
```

**Comment by Lyon1994** [comment]
已提交PR

**Comment by gedoor** [comment]
ok,改了

**Comment by Lyon1994** [comment]
@gedoor 你好，在[`ReaderProvider.kt`](https://github.com/gedoor/legado/blob/master/app/src/main/java/io/legado/app/api/ReaderProvider.kt)中，最近一次提交似乎把[之前改的内容](https://github.com/gedoor/legado/commit/f607f0eb25b95c8cdc0f6e18b25f6541c6fd734c#diff-6c50d5042d18885c4b8777ea26f490570bdcf02cd11cfae9740b688cc2a4719c)还原了，当前问题仍会出现，原因不在于继承的是`Cursor`还是`MatrixCursor`,问题在于重新实现的方法中
```java
private class SimpleCursor(data: ReturnData?) : MatrixCursor(arrayOf("result"), 1) {

        private val mData: String = Gson().toJson(data)

        init {
            addRow(arrayOf(mData))
        }

        override fun getCount() = 1

        override fun getColumnCount() = 0

        override fun getString(i: Int) = mData

        //........省略.....
    }
```
android系统在转发Cursor时是先复制再转发的，
![image](https://user-images.githubusercontent.com/8456652/95809371-2e8d9c80-0d41-11eb-8a69-eb1148ba0d8a.png)
api文档中所提到的用`Cursor.getString(0) `,这里的`cursor`对象不是你在app中定义的`SimpleCursor`,是系统自己的，再加上`getColumnCount() = 0`会导致android系统认为你这个cursor就是一个只有一行的空数据，最终系统在复制你的`SimpleCursor`时，通过`getColumnCount`会认为你这没有列数据，也不会调用`override fun getString(i: Int) = mData`这个方法，第三方APP获取时也就不会得到预期的数据只有一个空行。

`rowCount=1, columnCount=0, getString(0)-> Error`
```log
    java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
        at android.database.CursorWindow.nativeGetString(Native Method)
        at android.database.CursorWindow.getString(CursorWindow.java:469)
        at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:53)
        at android.database.CursorWrapper.getString(CursorWrapper.java:141)
```


不需要重写太多方法，写的越多越容易出bug，`MatrixCursor`内已经写好了这些逻辑，可以直接用，简单些就是：
```java
    /**
     * Simple inner class to deliver json callback data.
     *
     * Only getString() makes sense.
     */
    private class SimpleCursor(data: ReturnData?) : MatrixCursor(arrayOf("result"), 1) {
        private val mData: String = Gson().toJson(data)

        init {
            addRow(arrayOf(mData))
        }

    }
```

**Comment by Lyon1994** [comment]
@gedoor 
```java
    /**
     * Constructs a new cursor with the given initial capacity.
     *
     * @param columnNames names of the columns, the ordering of which
     *  determines column ordering elsewhere in this cursor
     * @param initialCapacity in rows
     */
    public MatrixCursor(String[] columnNames, int initialCapacity)
```
`MatrixCursor(arrayOf("result"), 1)`这样创建的`cursor`本身的格式就是一个只有一行一列的表结构
|result|
|:--:|
|mData（json）|
不需要重写其他方法了

**Comment by gedoor** [comment]
好的,我改下只保留这个
```
/**
     * Simple inner class to deliver json callback data.
     *
     * Only getString() makes sense.
     */
    private class SimpleCursor(data: ReturnData?) : MatrixCursor(arrayOf("result"), 1) {
        private val mData: String = Gson().toJson(data)

        init {
            addRow(arrayOf(mData))
        }

    }
```
