### ISSUE TITLE
朗读失败

### ISSUE THREAD

**Issue by lceyking** [gedoor/legado#3881]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

朗读文章，朗读失败后拉取阅读进度失败。

### 复现步骤 / How to reproduce

朗读时概率出现

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

androidx.media3.exoplayer.ExoPlaybackException: Source error
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(SourceFile:17)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(SourceFile:340)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:236)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.exoplayer.source.UnrecognizedInputFormatException: None of the available extractors (Mp3Extractor, FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, AviExtractor, JpegExtractor) could read the stream.{contentIsMalformed=false, dataType=1}
	at androidx.media3.exoplayer.source.BundledExtractorsAdapter.init(SourceFile:149)
	at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(SourceFile:124)
	at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(SourceFile:41)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

io.legado.app.exception.NoStackTraceException: 没有进度

### 阅读版本 / Legado version

3.22.110211

### Android版本 / Android version

Android 11

### 机型 / Model

小米10S

**Comment by 821938089** [comment]
朗读源的问题，服务器有时抽风返回错误数据
可以试试升级阅读版本然后并发率填写3000

**Comment by lceyking** [comment]
> 朗读源的问题，服务器有时抽风返回错误数据 可以试试升级阅读版本然后并发率填写3000

更新后改了并发率，已经听了超过4h未出现还问题。感谢回复。
