### ISSUE TITLE
每次点返回退出阅读时，应用都会报错闪退

### ISSUE THREAD

**Issue by XY50** [gedoor/legado#3952]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

每次点返回退出阅读时，应用都会报错闪退

### 复现步骤 / How to reproduce

随便朗读一本小说，读完之后点返回退出，然后应用就会报错闪退

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

SDK_INT=33
WebViewUserAgent=Mozilla/5.0 (Linux; Android 13; M2012K10C Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.179 Mobile Safari/537.36
MODEL=M2012K10C
RELEASE=13
MANUFACTURER=Xiaomi
versionName=3.24.052512
versionCode=15403
BRAND=Redmi
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{c2b56bc u0 io.legado.app.release/io.legado.app.service.HttpReadAloudService}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2103)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2074)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2339)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8152)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1925)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1880)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:832)
	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(SourceFile:1)
	at androidx.core.content.ContextCompat.startForegroundService(SourceFile:7)
	at io.legado.app.model.r0.h(SourceFile:26)
	at io.legado.app.ui.book.read.ReadBookViewModel.onCleared(SourceFile:14)
	at androidx.lifecycle.ViewModel.clear(SourceFile:77)
	at androidx.lifecycle.ViewModelStore.clear(SourceFile:23)
	at androidx.activity.ComponentActivity$3.onStateChanged(SourceFile:26)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(SourceFile:25)
	at androidx.lifecycle.LifecycleRegistry.backwardPass(SourceFile:88)
	at androidx.lifecycle.LifecycleRegistry.sync(SourceFile:47)
	at androidx.lifecycle.LifecycleRegistry.moveToState(SourceFile:69)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(SourceFile:15)
	at androidx.lifecycle.ReportFragment$Companion.dispatch$lifecycle_runtime_release(SourceFile:41)
	at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPreDestroyed(SourceFile:10)
	at android.app.Activity.dispatchActivityPreDestroyed(Activity.java:1616)
	at android.app.Activity.performDestroy(Activity.java:8800)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1452)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5569)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5615)
	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2405)
	... 7 more
android.app.StackTrace: Last startServiceCommon() call for this service was made here
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1925)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1880)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:832)
	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(SourceFile:1)
	at androidx.core.content.ContextCompat.startForegroundService(SourceFile:7)
	at io.legado.app.model.r0.h(SourceFile:26)
	at io.legado.app.ui.book.read.ReadBookViewModel.onCleared(SourceFile:14)
	at androidx.lifecycle.ViewModel.clear(SourceFile:77)
	at androidx.lifecycle.ViewModelStore.clear(SourceFile:23)
	at androidx.activity.ComponentActivity$3.onStateChanged(SourceFile:26)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(SourceFile:25)
	at androidx.lifecycle.LifecycleRegistry.backwardPass(SourceFile:88)
	at androidx.lifecycle.LifecycleRegistry.sync(SourceFile:47)
	at androidx.lifecycle.LifecycleRegistry.moveToState(SourceFile:69)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(SourceFile:15)
	at androidx.lifecycle.ReportFragment$Companion.dispatch$lifecycle_runtime_release(SourceFile:41)
	at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPreDestroyed(SourceFile:10)
	at android.app.Activity.dispatchActivityPreDestroyed(Activity.java:1616)
	at android.app.Activity.performDestroy(Activity.java:8800)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1452)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5569)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5615)
	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2405)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8152)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

### 阅读版本 / Legado version

3.24.052512

### Android版本 / Android version

13

### 机型 / Model

红米K40G

**Comment by 821938089** [comment]
去关于页面点保存日志，然后去备份文件夹把logs文件夹里的日志压缩上传
