### ISSUE TITLE
程序在后台运行时，通过系统快捷开关关闭web服务，应用崩溃

### ISSUE THREAD

**Issue by windy-821** [gedoor/legado#3971]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [ ] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [ ] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件等无关 / Make sure your machine is not touched by hook frameworks, plugins etc

### 问题描述 / Describe Bugs

开启web服务后，系统长时间在后台运行，此时通过系统快捷开关关闭web服务，应用崩溃报错。或者在应用未打开情况下开启web服务也会报一样的错。

### 复现步骤 / How to reproduce

1.打开应用开启web服务。
2.应用后台长时间运行
3.再通过系统快捷开关关闭web服务，此时会报错。
4.再打开应用也会提示崩溃。再重新打开正常。

### 确认 / Assignment

- [ ] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

```
android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=io.legado.app.release/io.legado.app.service.WebService }: app is in background uid UidRecord{11be5d6 u0a387 CEM  idle change:procadj procs:0 seq(7677017,7677003)} caps=------
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1956)
	at android.app.ContextImpl.startService(ContextImpl.java:1911)
	at android.content.ContextWrapper.startService(ContextWrapper.java:836)
	at io.legado.app.service.WebTileService.onClick(SourceFile:28)
	at android.service.quicksettings.TileService$H.handleMessage(TileService.java:494)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8772)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

### 阅读版本 / Legado version

3.22.110211

### Android版本 / Android version

Android 14

### 机型 / Model

Redmi k40 pro

**Comment by windy-821** [comment]
问题和这个有点像 issure: #1489

**Comment by 821938089** [comment]
确定最新测试版可以复现吗，这个已经修过了，最新测试版不太可能还会出现

**Comment by windy-821** [comment]
我用的是最新的发布版，你说的测试版是指最新流水线生成的版本，我没有使用最新的测试过
