### ISSUE TITLE
在后台朗读时，有概率换章时程序崩溃。

### ISSUE THREAD

**Issue by plwd2022** [gedoor/legado#3976]
SDK_INT=34
WebViewUserAgent=Mozilla/5.0 (Linux; Android 14; 23049RAD8C Build/UKQ1.230804.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.179 Mobile Safari/537.36
MODEL=23049RAD8C
RELEASE=14
MANUFACTURER=Xiaomi
versionName=3.24.052719
versionCode=15408
BRAND=Redmi
java.util.NoSuchElementException: List is empty.
	at kotlin.collections.w.m2(SourceFile:22)
	at io.legado.app.ui.book.read.page.entities.TextChapter.getPageIndexByCharIndex(SourceFile:51)
	at io.legado.app.model.j1.g(SourceFile:7)
	at io.legado.app.ui.book.read.page.ReadView.getPageIndex(SourceFile:6)
	at io.legado.app.ui.book.read.page.provider.n.a(SourceFile:39)
	at io.legado.app.ui.book.read.page.ReadView.h(SourceFile:59)
	at io.legado.app.ui.book.read.s2.invokeSuspend(SourceFile:22)
	at m7.a.resumeWith(SourceFile:9)
	at kotlinx.coroutines.m0.run(SourceFile:127)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8767)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [z1{Cancelling}@717e95a, Dispatchers.Main.immediate]

SDK_INT=34
WebViewUserAgent=Mozilla/5.0 (Linux; Android 14; 23049RAD8C Build/UKQ1.230804.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.179 Mobile Safari/537.36
MODEL=23049RAD8C
RELEASE=14
MANUFACTURER=Xiaomi
versionName=3.24.052719
versionCode=15408
BRAND=Redmi
java.lang.RuntimeException: Unable to start receiver io.legado.app.receiver.MediaButtonReceiver: java.util.NoSuchElementException: List is empty.
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4685)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8767)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.util.NoSuchElementException: List is empty.
	at kotlin.collections.w.m2(SourceFile:22)
	at io.legado.app.ui.book.read.page.entities.TextChapter.getPageIndexByCharIndex(SourceFile:51)
	at io.legado.app.model.j1.g(SourceFile:7)
	at io.legado.app.model.j1.n(SourceFile:41)
	at com.google.android.material.internal.a0.s(SourceFile:140)
	at com.google.android.material.internal.a0.q(SourceFile:56)
	at io.legado.app.receiver.MediaButtonReceiver.onReceive(SourceFile:11)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4673)
	... 9 more
java.util.NoSuchElementException: List is empty.
	at kotlin.collections.w.m2(SourceFile:22)
	at io.legado.app.ui.book.read.page.entities.TextChapter.getPageIndexByCharIndex(SourceFile:51)
	at io.legado.app.model.j1.g(SourceFile:7)
	at io.legado.app.model.j1.n(SourceFile:41)
	at com.google.android.material.internal.a0.s(SourceFile:140)
	at com.google.android.material.internal.a0.q(SourceFile:56)
	at io.legado.app.receiver.MediaButtonReceiver.onReceive(SourceFile:11)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4673)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8767)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by 821938089** [comment]
发一下触发崩溃的书源、书名、章节名
