### ISSUE TITLE
加载目录失败

### ISSUE THREAD

**Issue by gyz1023** [gedoor/legado#4020]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

源突然失效了 校验能通过的，搜索就加载目录失败，已经添加的刷新也失败，同一个源正式版能用

### 复现步骤 / How to reproduce

不知道咋了

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

"com.script.ScriptException: org.mozilla.javascript.WrappedException: Wrapped com.script.ScriptException: org.mozilla.javascript.WrappedException: Wrapped java.lang.IllegalStateException: Rhino recursive call detected. (<Unknown source>#10) in <Unknown source> at line number 10 (<Unknown source>#25) in <Unknown source> at line number 25
	at com.script.rhino.RhinoScriptEngine.eval(SourceFile:34)
	at com.script.AbstractScriptEngine.eval(SourceFile:3)
	at io.legado.app.model.analyzeRule.AnalyzeRule.evalJS(SourceFile:119)
	at io.legado.app.model.analyzeRule.AnalyzeRule.evalJS$default(SourceFile:6)
	at io.legado.app.model.webBook.x0.n(SourceFile:41)
	at io.legado.app.model.webBook.x0.h(SourceFile:171)
	at io.legado.app.model.webBook.p0.invokeSuspend(SourceFile:41)
	at io.legado.app.model.webBook.p0.invoke(SourceFile:2)
	at io.legado.app.model.webBook.p0.invoke(SourceFile:1)
	at io.legado.app.help.coroutine.i.invokeSuspend(SourceFile:61)
	at m7.a.resumeWith(SourceFile:9)
	at kotlinx.coroutines.m0.run(SourceFile:127)
	at com.bumptech.glide.load.engine.a.run(SourceFile:15)
	at f9.k.run(SourceFile:3)
	at f9.b.run(SourceFile:96)
Caused by: org.mozilla.javascript.WrappedException: Wrapped com.script.ScriptException: org.mozilla.javascript.WrappedException: Wrapped java.lang.IllegalStateException: Rhino recursive call detected. (<Unknown source>#10) in <Unknown source> at line number 10 (<Unknown source>#25)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(SourceFile:43)
	at org.mozilla.javascript.MemberBox.invoke(SourceFile:98)
	at org.mozilla.javascript.NativeJavaMethod.call(SourceFile:186)
	at org.mozilla.javascript.Interpreter.interpretLoop(SourceFile:365)
	at org.mozilla.javascript.Interpreter.interpret(SourceFile:57)
	at org.mozilla.javascript.InterpretedFunction.call(SourceFile:21)
	at org.mozilla.javascript.ContextFactory.doTopCall(SourceFile:1)
	at com.script.rhino.RhinoScriptEngine$1.superDoTopCall(SourceFile:12)
	at com.script.rhino.RhinoScriptEngine$1.doTopCall(SourceFile:60)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(SourceFile:8)
	at org.mozilla.javascript.InterpretedFunction.exec(SourceFile:23)
	at org.mozilla.javascript.Context.evaluateReader(SourceFile:7)
	at com.script.rhino.RhinoScriptEngine.eval(SourceFile:25)
	... 14 more
Caused by: com.script.ScriptException: org.mozilla.javascript.WrappedException: Wrapped java.lang.IllegalStateException: Rhino recursive call detected. (<Unknown source>#10) in <Unknown source> at line number 10
	at com.script.rhino.RhinoScriptEngine.eval(SourceFile:34)
	at com.script.AbstractScriptEngine.eval(SourceFile:3)
	at io.legado.app.model.analyzeRule.AnalyzeRule.evalJS(SourceFile:119)
	at io.legado.app.model.analyzeRule.AnalyzeRule.getElement(SourceFile:157)
	at org.chromium.net.impl.l.a(SourceFile:7)
	at org.chromium.net.impl.l.b(SourceFile:70)
	at io.legado.app.model.webBook.x0.e(SourceFile:380)
	at io.legado.app.model.webBook.o0.invokeSuspend(Unknown Source:13)
	at m7.a.resumeWith(SourceFile:9)
	at kotlinx.coroutines.m0.run(SourceFile:127)
	at kotlinx.coroutines.w0.i(SourceFile:139)
	at kotlinx.coroutines.e0.y(SourceFile:107)
	at io.legado.app.model.analyzeRule.AnalyzeRule.refreshTocUrl(SourceFile:36)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.mozilla.javascript.MemberBox.invoke(SourceFile:36)
	... 25 more
Caused by: org.mozilla.javascript.WrappedException: Wrapped java.lang.IllegalStateException: Rhino recursive call detected. (<Unknown source>#10)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(SourceFile:43)
	at org.mozilla.javascript.MemberBox.invoke(SourceFile:98)
	at org.mozilla.javascript.NativeJavaMethod.call(SourceFile:186)
	at org.mozilla.javascript.Interpreter.interpretLoop(SourceFile:365)
	at org.mozilla.javascript.Interpreter.interpret(SourceFile:57)
	at org.mozilla.javascript.InterpretedFunction.exec(SourceFile:30)
	at org.mozilla.javascript.Context.evaluateReader(SourceFile:7)
	at com.script.rhino.RhinoScriptEngine.eval(SourceFile:25)
	... 39 more
Caused by: java.lang.IllegalStateException: Rhino recursive call detected.
	at io.legado.app.data.entities.BaseSource$DefaultImpls.getHeaderMap(SourceFile:230)
	at io.legado.app.data.entities.BookSource.getHeaderMap(SourceFile:1)
	at io.legado.app.model.analyzeRule.AnalyzeUrl.<init>(SourceFile:23)
	at io.legado.app.model.analyzeRule.AnalyzeUrl.<init>(SourceFile:32)
	at io.legado.app.model.analyzeRule.AnalyzeRule.ajax(SourceFile:59)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.mozilla.javascript.MemberBox.invoke(SourceFile:36)
	... 45 more
"

### 阅读版本 / Legado version

3.24.07081754

### Android版本 / Android version

Android 14

### 机型 / Model

redmi k40

**Comment by 821938089** [comment]
发书源看看

**Comment by h11128** [comment]
@821938089 已经很久没有release了，是以后都不release了，只能用测试版吗？

**Comment by 821938089** [comment]
@h11128 作者已经很久没commit过了，应该是不更新了，所以没有release了，只能用测试版了
