### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by skybbk1998** [gedoor/legado#4022]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

最新测试版频繁崩溃

### 复现步骤 / How to reproduce

书源管理-任意单个书源搜索随意书籍-进入正文-返回-是否添加到书架？否-返回-崩溃

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

```
SDK_INT=34
WebViewUserAgent=Mozilla/5.0 (Linux; Android 14; 23049RAD8C Build/UKQ1.230804.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.133 Mobile Safari/537.36
MODEL=23049RAD8C
RELEASE=14
MANUFACTURER=Xiaomi
versionName=3.24.070916
versionCode=15454
BRAND=Redmi
java.lang.ClassCastException: java.lang.String cannot be cast to android.os.Bundle
	at io.legado.app.ui.book.search.SearchAdapter.c(SourceFile:184)
	at io.legado.app.base.adapter.DiffRecyclerAdapter.onBindViewHolder(SourceFile:6)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(SourceFile:30)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(SourceFile:40)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(SourceFile:457)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:2)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:1)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(SourceFile:12)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(SourceFile:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(SourceFile:39)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(SourceFile:358)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(SourceFile:39)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(SourceFile:29)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:6)
	at android.view.View.layout(View.java:25223)
	at android.view.ViewGroup.layout(ViewGroup.java:6515)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25223)
	at android.view.ViewGroup.layout(ViewGroup.java:6515)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(SourceFile:71)
	at android.view.View.layout(View.java:25223)
	at android.view.ViewGroup.layout(ViewGroup.java:6515)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25223)
	at android.view.ViewGroup.layout(ViewGroup.java:6515)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25223)
	at android.view.ViewGroup.layout(ViewGroup.java:6515)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25223)
	at android.view.ViewGroup.layout(ViewGroup.java:6515)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25223)
	at android.view.ViewGroup.layout(ViewGroup.java:6515)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:865)
	at android.view.View.layout(View.java:25223)
	at android.view.ViewGroup.layout(ViewGroup.java:6515)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4796)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4103)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2933)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10224)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1626)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1635)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1170)
	at android.view.Choreographer.doFrame(Choreographer.java:1074)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1599)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8759)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

```

### 阅读版本 / Legado version

3.24.070916

### Android版本 / Android version

Android 14

### 机型 / Model

Redmi note 12 Turbo

**Comment by 821938089** [comment]
试试最新测试版

**Comment by skybbk1998** [comment]
最新版已修复
