### ISSUE TITLE
音频听不了

### ISSUE THREAD

**Issue by forme1750** [gedoor/legado#4047]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

音频用不了

### 复现步骤 / How to reproduce

androidx.media3.exoplayer.ExoPlaybackException: Source error
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(SourceFile:17)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(SourceFile:300)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.datasource.HttpDataSource$HttpDataSourceException: Malformed URL
	at androidx.media3.datasource.okhttp.OkHttpDataSource.makeRequest(SourceFile:172)
	at androidx.media3.datasource.okhttp.OkHttpDataSource.open(SourceFile:12)
	at androidx.media3.datasource.TeeDataSource.open(SourceFile:3)
	at androidx.media3.datasource.cache.CacheDataSource.openNextSource(SourceFile:279)
	at androidx.media3.datasource.cache.CacheDataSource.open(SourceFile:127)
	at androidx.media3.datasource.ResolvingDataSource.open(SourceFile:12)
	at androidx.media3.datasource.StatsDataSource.open(SourceFile:13)
	at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(SourceFile:26)
	at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(SourceFile:41)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

机型真我gt neo5

### 日志提交 / Relevant log output

androidx.media3.exoplayer.ExoPlaybackException: Source error
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(SourceFile:17)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(SourceFile:300)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.datasource.HttpDataSource$HttpDataSourceException: Malformed URL
	at androidx.media3.datasource.okhttp.OkHttpDataSource.makeRequest(SourceFile:172)
	at androidx.media3.datasource.okhttp.OkHttpDataSource.open(SourceFile:12)
	at androidx.media3.datasource.TeeDataSource.open(SourceFile:3)
	at androidx.media3.datasource.cache.CacheDataSource.openNextSource(SourceFile:279)
	at androidx.media3.datasource.cache.CacheDataSource.open(SourceFile:127)
	at androidx.media3.datasource.ResolvingDataSource.open(SourceFile:12)
	at androidx.media3.datasource.StatsDataSource.open(SourceFile:13)
	at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(SourceFile:26)
	at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(SourceFile:41)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

### 阅读版本 / Legado version

3.23.110211

### Android版本 / Android version

Android 13

### 机型 / Model

真我gt neo5

**Comment by 821938089** [comment]
源失效了

**Comment by forme1750** [comment]
> 源失效了

如何更新🤔

**Comment by forme1750** [comment]
> 你可以找人修，或者换别的源

谢了，昨晚自己修了一下好了

**Comment by lhjgege** [comment]
音频播放会出现音频播放不了的情况，无论点击下一个还是上一个音频都会出现播放不了。把应用退出后重新打开又可以了。

**Comment by lhjgege** [comment]
还有音频播放界面点击播放按钮后能不能加入一个loading加载框，不然点击播放了都不知道有没有点击到。

**Comment by forme1750** [comment]
听书错误2001是什么问题😭

**Comment by forme1750** [comment]
error_code_i9_network_connection_failed_2001
