### ISSUE TITLE
闪退bug

### ISSUE THREAD

**Issue by sky-bbk** [gedoor/legado#4072]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

在调试书源时，阅读app突然闪退，之后再打开软件会立即闪退，持续了几分钟后可以打开了。
下图是用日志查看软件获取的阅读日志，不知道是不是闪退时的报错

### 复现步骤 / How to reproduce

![Screenshot_2024-08-08-02-36-01-889_com conena logcat reader-edit](https://github.com/user-attachments/assets/774376a4-e53b-43ae-bc50-25a2fb150238)

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.24.080310

### Android版本 / Android version

Android 14

### 机型 / Model

Redmi note 12 Turbo

**Comment by 821938089** [comment]
图片里没有引发阅读崩溃的相关日志
阅读的崩溃日志里没有东西吗？

**Comment by sky-bbk** [comment]
闪退时的崩溃日志没有被记录。只有闪退一小时前有过崩溃记录

`SDK_INT=34
WebViewUserAgent=Mozilla/5.0 (Linux; Android 14; 23049RAD8C Build/UKQ1.230804.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/127.0.6533.64 Mobile Safari/537.36
MODEL=23049RAD8C
RELEASE=14
MANUFACTURER=Xiaomi
versionName=3.24.080310
versionCode=15559
BRAND=Redmi
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
	at android.view.ViewRootImpl.handleWindowFocusChanged(ViewRootImpl.java:4509)
	at android.view.ViewRootImpl.-$$Nest$mhandleWindowFocusChanged(Unknown Source:0)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl(ViewRootImpl.java:6675)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:6566)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8759)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
`

**Comment by 821938089** [comment]
你有没有打开Cronet，如果这东西崩溃了，崩溃日志里可能是没记录的，如果经常出现这样的闪退你可以关掉它试试

**Comment by sky-bbk** [comment]
没有打开Cronet
