### ISSUE TITLE
离线缓存导出卡死！

### ISSUE THREAD

**Issue by xusos** [gedoor/legado#4085]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

离线缓存导出小说卡死，然后闪退！日志如下：SDK_INT=34
WebViewUserAgent=Mozilla/5.0 (Linux; Android 14; M2102K1G Build/UKQ1.231207.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/127.0.6533.103 Mobile Safari/537.36
MODEL=M2102K1G
RELEASE=14
MANUFACTURER=Xiaomi
versionName=3.23.110211
versionCode=14860
BRAND=Xiaomi
java.lang.OutOfMemoryError: Failed to allocate a 126488 byte allocation with 141296 free bytes and 137KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at java.util.Arrays.copyOf(Arrays.java:3553)
	at java.util.Arrays.copyOf(Arrays.java:3522)
	at java.util.ArrayList.grow(ArrayList.java:244)
	at java.util.ArrayList.grow(ArrayList.java:251)
	at java.util.ArrayList.add(ArrayList.java:461)
	at java.util.ArrayList.add(ArrayList.java:474)
	at android.app.ActivityThreadImpl.getDelayedMessages(Unknown Source:58)
	at android.app.ActivityThreadImpl.reportAnrIssue(Unknown Source:70)
	at android.app.ActivityThreadImpl.dumpPeriodHistoryMessage(Unknown Source:60)
	at android.app.ActivityThread$ApplicationThread.dumpPeriodHistoryMessage(Unknown Source:4)
	at android.app.IApplicationThread$Stub.onTransact(Unknown Source:51)
	at android.os.Binder.execTransactInternal(Unknown Source:109)
	at android.os.Binder.execTransact(Unknown Source:39)

### 复现步骤 / How to reproduce

更新最新版本也是一样

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 阅读版本 / Legado version

3.23.110211

### Android版本 / Android version

Android 14

### 机型 / Model

小米11U

**Comment by 821938089** [comment]
安装最新测试版，在其他设置里打开记录堆转储，复现崩溃后去关于那里点保存日志，然后去备份目录里将heapDump文件夹里的文件打包压缩一下上传上来

**Comment by xusos** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
