### ISSUE TITLE
调试发现规则时闪退

### ISSUE THREAD

**Issue by sky-bbk** [gedoor/legado#4108]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

调试发现规则时，长按发现闪退

### 复现步骤 / How to reproduce

![Screenshot_2024-08-19-18-18-35-475_io legado app release_1](https://github.com/user-attachments/assets/e95371b9-e43d-4e92-aa32-fb5e5b8f34ce)
我想长按发现测试其他发现规则，但是每一次都闪退

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

https://dns.jingluo.love/2024/66c31cbc9721f.json
这是我用来测试的书源

### 日志提交 / Relevant log output

```
SDK_INT=34
WebViewUserAgent=Mozilla/5.0 (Linux; Android 14; 23049RAD8C Build/UKQ1.230804.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/127.0.6533.103 Mobile Safari/537.36
MODEL=23049RAD8C
RELEASE=14
MANUFACTURER=Xiaomi
versionName=3.25
versionCode=15604
BRAND=Redmi
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at x1.d.V(SourceFile:37)
	at io.legado.app.ui.book.search.c.onLongClick(SourceFile:161)
	at android.view.View.performLongClickInternal(View.java:7881)
	at android.view.View.performLongClick(View.java:7837)
	at android.widget.TextView.performLongClick(TextView.java:14689)
	at android.view.View.performLongClick(View.java:7855)
	at android.view.View$CheckForLongPress.run(View.java:31093)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8759)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

```

### 阅读版本 / Legado version

3.25

### Android版本 / Android version

Android 14

### 机型 / Model

Redmi note 12 Turbo

**Comment by 821938089** [comment]
有些发现的title为null

**Comment by sky-bbk** [comment]
最新版本已正常，感谢
