### ISSUE TITLE
FOREIGN KEY constraint failed (Sqlite code 787), (OS error - 11:Try again)

### ISSUE THREAD

**Issue by ghost** [gedoor/legado#4234]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

阅读小说后台一段时间返回后低概率出现bug，数据库读取失败或者没有书籍。好像是修改后台开始bug？

### 复现步骤 / How to reproduce

后台返回

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (Sqlite code 787), (OS error - 11:Try again)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:818)
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:803)
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
	at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(SourceFile:3)
	at androidx.room.EntityInsertionAdapter.insert(SourceFile:8)
	at io.legado.app.data.dao.BookChapterDao_Impl.insert(SourceFile:13)
	at io.legado.app.ui.book.read.ReadBookViewModel.e(SourceFile:472)
	at io.legado.app.ui.book.read.r1.invokeSuspend(SourceFile:13)
	at d9.a.resumeWith(SourceFile:9)
	at kotlinx.coroutines.i0.run(SourceFile:125)
	at com.google.common.util.concurrent.w.n(SourceFile:6)
	at com.google.common.util.concurrent.w.run(SourceFile:9)
	at yb.k.run(SourceFile:3)
	at yb.b.run(SourceFile:96)

### 阅读版本 / Legado version

3.24.092019

### Android版本 / Android version

安卓8

### 机型 / Model

荣耀8

**Comment by 821938089** [comment]
书籍加入书架了吗？

**Comment by 821938089** [comment]
没加书架的书籍会在应用重启后被删掉
