### ISSUE TITLE
订阅的收藏夹页面闪退

### ISSUE THREAD

**Issue by sky-bbk** [gedoor/legado#4253]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

打开订阅的收藏夹，点了几下就闪退了

### 复现步骤 / How to reproduce

无法复现

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

```
SDK_INT=34
WebViewUserAgent=Mozilla/5.0 (Linux; Android 14; 23049RAD8C Build/UKQ1.230804.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/128.0.6613.146 Mobile Safari/537.36
MODEL=23049RAD8C
RELEASE=14
packageName=io.legado.app.release
MANUFACTURER=Xiaomi
versionName=3.24.092719
versionCode=15719
BRAND=Redmi
java.lang.IllegalArgumentException: invalid pointerIndex -1 for MotionEvent { action=MOVE, id[0]=1, x[0]=828.22, y[0]=542.506, historySize=5, eventTime=2734913070677679, downTime=2734911801144000, deviceId=8, source=TOUCHSCREEN, displayId=0, eventId=262678112}
	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
	at android.view.MotionEvent.getX(MotionEvent.java:2677)
	at androidx.viewpager.widget.ViewPager.onInterceptTouchEvent(SourceFile:57)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2674)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3160)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2828)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:566)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1908)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4584)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(SourceFile:3)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:524)
	at android.view.View.dispatchPointerEvent(View.java:16145)
	at com.xiaomi.mirror.MiuiMirrorImpl.isHandled(MiuiMirrorImpl.java:152)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7815)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7581)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6953)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7010)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6976)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7141)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6984)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7198)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6957)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7010)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6976)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6984)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6957)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10124)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10075)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10039)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10285)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:304)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:275)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:10210)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:10379)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1626)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1635)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1170)
	at android.view.Choreographer.doFrame(Choreographer.java:1067)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1599)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8759)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

```

### 阅读版本 / Legado version

3.24.092719

### Android版本 / Android version

Android 14

### 机型 / Model

23049RAD8C

**Comment by youke2580c** [comment]
点击的索引位置无效，点错位置了

**Comment by 821938089** [comment]
已修复，试试最新测试版

**Comment by sky-bbk** [comment]
> 已修复，试试最新测试版

感谢
