### ISSUE TITLE
手势返回会导致软件崩溃，百分百复现

### ISSUE THREAD

**Issue by zgerbin** [gedoor/legado#4263]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

在书架、阅读界面等，使用返回手势会出现 app 崩溃
![Uploading Screenshot_2024-10-09-00-57-28-098_io.legado.app.release.jpg…]()

### 复现步骤 / How to reproduce

在书架、阅读界面等，使用返回手势

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

SDK_INT=34
WebViewUserAgent=Mozilla/5.0 (Linux; Android 14; 22041211AC Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/127.0.6533.103 Mobile Safari/537.36
MODEL=22041211AC
RELEASE=14
packageName=io.legado.app.release
MANUFACTURER=Xiaomi
versionName=3.24.100508
versionCode=15758
BRAND=Redmi
java.lang.NullPointerException: Attempt to invoke virtual method 'float android.window.BackMotionEvent.getTouchX()' on a null object reference
	at android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper.lambda$onBackStarted$1(WindowOnBackInvokedDispatcher.java:353)
	at android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper.$r8$lambda$jWVwe-YeLRxW3tAMLuWZynG6e1k(Unknown Source:0)
	at android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper$$ExternalSyntheticLambda4.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.app.ActivityThread.main(ActivityThread.java:8716)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1042)

### 阅读版本 / Legado version

3.24.100508

### Android版本 / Android version

14

### 机型 / Model

红米K50

**Comment by 821938089** [comment]
卸载系统桌面更新

**Comment by zgerbin** [comment]
> 卸载系统桌面更新

pro 版本不会有问题
