### ISSUE TITLE
web浏览书架,无法加载书籍封面

### ISSUE THREAD

**Issue by zeng-zijie** [gedoor/legado#4289]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

3.23.110211 更新到 3.25 后出现此问题
在进入web书架时,因无法获取书籍封面而导致无法点击书籍阅读
停止刷新后单击书架可以进行阅读

### 复现步骤 / How to reproduce

开启web服务
1. 在使用浏览器访问书架时,点击书籍书籍无反应,无法进入阅读页面(页面未加载完成)

![1](https://github.com/user-attachments/assets/1f4c6d41-c83b-4d9e-bc7d-45d2486cba11)

2. 在终止书架页面刷新后,可点击对应的书,进入阅读页面(书籍封面未获取到)
![2](https://github.com/user-attachments/assets/b473b65d-f332-491e-8cbb-07fb92da1c69)

3. 在阅读页面返回书架时,重复出现步骤1

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 其他信息 / Additions

Chrome 版本 130.0.6723.59（正式版本） （64 位）

### 日志提交 / Relevant log output

控制台报错
```{
    "message": "Request aborted",
    "name": "AxiosError",
    "stack": "AxiosError: Request aborted\n    at c.onabort (http://192.168.100.100:1122/vue/assets/vendor-B4RITwN5.js:42:6131)\n    at Vr.request (http://192.168.100.100:1122/vue/assets/vendor-B4RITwN5.js:44:1961)\n    at async ee (http://192.168.100.100:1122/vue/assets/BookShelf-DmN0EcU9.js:1:5079)",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http",
            "fetch"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 120000,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json"
        },
        "method": "post",
        "url": "http://192.168.100.100:1122/saveBook",
        "data": "{\"author\":\"耳根\",\"bookUrl\":\"https://api-bc.wtzw.com/api/v4/book/detail?&id=1784957&imei_ip=2937357107&teeny_mode=0&sign=983ca1be6607dc01646bfb690e0c25a9,{\\\"headers\\\":{\\\"app-version\\\":\\\"51110\\\",\\\"platform\\\":\\\"android\\\",\\\"reg\\\":\\\"0\\\",\\\"AUTHORIZATION\\\":\\\"\\\",\\\"application-id\\\":\\\"com.****.reader\\\",\\\"net-env\\\":\\\"1\\\",\\\"channel\\\":\\\"unknown\\\",\\\"qm-params\\\":\\\"\\\",\\\"sign\\\":\\\"fc697243ab534ebaf51d2fa80f251cb4\\\"}}\",\"canUpdate\":true,\"coverUrl\":\"https://cdn.wtzw.com/bookimg/public/images/cover/f0e5/54cd288fdd26833589383001eed74c1c_360x480.jpg\",\"customIntro\":\"　　👥 核心角色：王宝乐、学首、法兵系、柳道斌、战武\\n　　​\\n　　🔖 简介：举头三尺无神明，掌心三寸是人间。\\n　　这是耳根继《仙逆》《求魔》《我欲封天》《一念永恒》后，创作的第五部长篇小说《三寸人间》。\",\"durChapterIndex\":229,\"durChapterPos\":0,\"durChapterTime\":1729257663023,\"durChapterTitle\":\"第226章 格物筑基法\",\"group\":1,\"intro\":\"　　🏷️   杀伐果断,逆袭,仙侠,修仙,热血\\n　　​\\n　　举头三尺无神明，掌心三寸是人间。\\n　　这是耳根继《仙逆》《求魔》《我欲封天》《一念永恒》后，创作的第五部长篇小说《三寸人间》。\",\"kind\":\"2024/01/24\",\"lastCheckCount\":0,\"lastCheckTime\":1729256847336,\"latestChapterTime\":1725356091215,\"latestChapterTitle\":\"新书《光阴之外》发布，兄弟姐妹可以一看啦\",\"name\":\"三寸人间\",\"order\":-325,\"origin\":\"https://api-bc.wtzw.com\",\"originName\":\"⭐ 七猫小说\",\"originOrder\":9,\"readConfig\":{\"dailyChapters\":3,\"delTag\":0,\"reSegment\":false,\"readSimulating\":false,\"reverseToc\":false,\"splitLongChapter\":true},\"syncTime\":1729257884328,\"tocUrl\":\"https://api-ks.wtzw.com/api/v1/chapter/chapter-list?&id=1784957&sign=b0e0e9c357d9d3712868587c3002d51d,{\\\"headers\\\":{\\\"app-version\\\":\\\"51110\\\",\\\"platform\\\":\\\"android\\\",\\\"reg\\\":\\\"0\\\",\\\"AUTHORIZATION\\\":\\\"\\\",\\\"application-id\\\":\\\"com.****.reader\\\",\\\"net-env\\\":\\\"1\\\",\\\"channel\\\":\\\"unknown\\\",\\\"qm-params\\\":\\\"\\\",\\\"sign\\\":\\\"fc697243ab534ebaf51d2fa80f251cb4\\\"}}\",\"totalChapterNum\":1488,\"type\":8,\"variable\":\"{\\n  \\\"headers\\\": \\\"{\\\\\\\"headers\\\\\\\":{\\\\\\\"app-version\\\\\\\":\\\\\\\"51110\\\\\\\",\\\\\\\"platform\\\\\\\":\\\\\\\"android\\\\\\\",\\\\\\\"reg\\\\\\\":\\\\\\\"0\\\\\\\",\\\\\\\"AUTHORIZATION\\\\\\\":\\\\\\\"\\\\\\\",\\\\\\\"application-id\\\\\\\":\\\\\\\"com.****.reader\\\\\\\",\\\\\\\"net-env\\\\\\\":\\\\\\\"1\\\\\\\",\\\\\\\"channel\\\\\\\":\\\\\\\"unknown\\\\\\\",\\\\\\\"qm-params\\\\\\\":\\\\\\\"\\\\\\\",\\\\\\\"sign\\\\\\\":\\\\\\\"fc697243ab534ebaf51d2fa80f251cb4\\\\\\\"}}\\\",\\n  \\\"bid\\\": \\\"1784957\\\"\\n}\",\"wordCount\":\"380万字\"}",
        "baseURL": "http://192.168.100.100:1122"
    },
    "code": "ECONNABORTED",
    "status": null
}
```
![3](https://github.com/user-attachments/assets/2ab97c38-9725-4c6e-a3da-66f06621b72c)

在重新刷新书架页面时,关于访问书籍封面的链接出现状态: 待处理
![4](https://github.com/user-attachments/assets/1b719db4-5ef4-4526-abd2-5a48e18cca1c)

```
curl 'http://192.168.100.100:1122/cover?path=https%3A%2F%2Fimg.shugege.net%2F14%2F14662%2F14662s.jpg' \
  -H 'Accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Connection: keep-alive' \
  -H 'Referer: http://192.168.100.100:1122/vue/index.html' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36'
```

### 阅读版本 / Legado version

3.25

### Android版本 / Android version

Android10

### 机型 / Model

meizhu16thplus

**Comment by Xwite** [comment]
Update to beta version.
Prefer to load image from original URL instead of legado one.
Close #4289
