### ISSUE TITLE
[bug]书源规则解析Jsoup时排除位置报错

### ISSUE THREAD

**Issue by Syt100** [gedoor/legado#432]
# 规则

目录列表规则'class.read@tag.dl.!0@tag.dd'报错

经排查是‘tag.dl.!0’中的’!0'有问题，改为‘tag.dl’后正常

![Screenshot_2020-10-20-14-13-33-087_io legado app](https://user-images.githubusercontent.com/54739795/96547329-80549a80-12de-11eb-9b15-8391bf2ca153.jpg)

# 报错截图

![Screenshot_2020-10-20-14-16-29-510_io legado app](https://user-images.githubusercontent.com/54739795/96547628-040e8700-12df-11eb-9309-316b82cb0241.jpg)

# 错误信息

> java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.last(_Collections.kt:380)
	at io.legado.app.model.webBook.BookChapterList.finish(BookChapterList.kt:191)
	at io.legado.app.model.webBook.BookChapterList.access$finish(BookChapterList.kt:19)
	at io.legado.app.model.webBook.BookChapterList.analyzeChapterList(BookChapterList.kt:55)
	at io.legado.app.model.webBook.WebBook$getChapterList$1.invokeSuspend(WebBook.kt:142)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

# 环境信息

阅读版本 3.20.101908

Android 版本 9

目标网站[九桃小说](http://www.9txs.com/)

**Comment by gedoor** [comment]
class.read@tag.dl!0@tag.dd这样就好了,多写了一个.

**Comment by gedoor** [comment]
获取全部不要第三端

**Comment by Syt100** [comment]
> [class.read@tag.dl](mailto:class.read@tag.dl)![0@tag.dd](mailto:0@tag.dd)这样就好了,多写了一个.

好的，之前这样写没问题的，最近更新后就不行了
