### ISSUE TITLE
在小说阅读界面右滑稳定触发的bug

### ISSUE THREAD

**Issue by yuangqian108** [gedoor/legado#4432]
### 确认 / Assignments

- [X] 搜索现有issues，不存在相似或相关的issue / No similar or related issues
- [X] 最新[测试版](https://github.com/gedoor/legado/actions/workflows/test.yml)依然存在此问题 / Latest beta app does not work
- [X] 此问题和Xposed、Lsposed、Magisk、手机主题、浏览器插件、无障碍服务等无关 / Make sure your machine is not touched by hook frameworks, plugins, accessibility etc

### 问题描述 / Describe Bugs

在3.25版本中，阅读小说界面左滑软件崩溃。在最新测试版中，同样左滑操作则软件不崩溃但也不会返回阅读书架。因此提供3.25版本的崩溃日志。

### 复现步骤 / How to reproduce

在小说阅读界面左滑

### 确认 / Assignment

- [X] 已经提交复现所需要的附加资料 / Submit additions related with bugs

### 日志提交 / Relevant log output

```SDK_INT=34
WebViewUserAgent=Mozilla/5.0 (Linux; Android 14; 24115RA8EC Build/UKQ1.240523.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.71 Mobile Safari/537.36
MODEL=24115RA8EC
RELEASE=14
MANUFACTURER=Xiaomi
versionName=3.25
versionCode=15604
BRAND=Redmi
java.lang.NullPointerException: Attempt to invoke virtual method 'float android.window.BackMotionEvent.getTouchX()' on a null object reference
	at android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper.lambda$onBackStarted$1(WindowOnBackInvokedDispatcher.java:353)
	at android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper.$r8$lambda$jWVwe-YeLRxW3tAMLuWZynG6e1k(Unknown Source:0)
	at android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper$$ExternalSyntheticLambda4.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.app.ActivityThread.main(ActivityThread.java:8891)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)```

### 阅读版本 / Legado version

3.25，3.24.121015

### Android版本 / Android version

Android14

### 机型 / Model

REDMI note14 pro +

**Comment by 821938089** [comment]
卸载系统桌面更新

**Comment by yuangqian108** [comment]
https://github.com/user-attachments/assets/b3590d93-4175-4d3c-8e06-91ae7ef75909

bug依旧啊

**Comment by yuangqian108** [comment]
不过不崩溃了

**Comment by 821938089** [comment]
设置里的禁止返回键看看是不是开了

**Comment by yuangqian108** [comment]
非常抱歉，确实关了。我关掉这个issue吧
