### ISSUE TITLE
[BUG] 听书闪退

### ISSUE THREAD

**Issue by sartonsh** [gedoor/legado#536]
### 机型（如Redmi K30 Pro）
>

### 安卓版本（如Android 7.1.1）
>
6.0.2

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>最近所有版本
### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>所有网络

### 问题描述（简要描述发生的问题）
>
使用听书源无法听书
刚更新的3.20.121020版本在书籍详情页点击阅读按键时会闪退到发现页面，之前版本会在阅读界面点击播放及定时按键时闪退。

### 使用书源（填写URL或者JSON）
>所有听书源

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
>

**Comment by EWF54Y6U7I** [comment]
MIUI9安卓8同闪退，阅读是最新1209版，闪退日志如下

````Java
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1448)
	at com.android.org.conscrypt.Platform.blockGuardOnNetwork(Platform.java:325)
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:724)
	at okio.Okio$2.read(Okio.java:140)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at okio.RealBufferedSource.exhausted(RealBufferedSource.java:61)
	at okhttp3.internal.connection.RealConnection.isHealthy(RealConnection.java:591)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:120)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at io.legado.app.help.http.HttpHelper$getHeaderInterceptor$1.intercept(HttpHelper.kt:160)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at io.legado.app.lib.webdav.WebDav.execRequest(WebDav.kt:245)
	at io.legado.app.lib.webdav.WebDav.makeAsDir(WebDav.kt:174)
	at io.legado.app.help.storage.BookWebDav.initWebDav(BookWebDav.kt:47)
	at io.legado.app.ui.book.read.ReadBookActivity.upMenu(ReadBookActivity.kt:176)
	at io.legado.app.ui.book.read.ReadBookActivity.access$upMenu(ReadBookActivity.kt:61)
	at io.legado.app.ui.book.read.ReadBookActivity$onActivityCreated$1.onChanged(ReadBookActivity.kt:108)
	at io.legado.app.ui.book.read.ReadBookActivity$onActivityCreated$1.onChanged(ReadBookActivity.kt:61)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6649)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:780)
````

**Comment by gedoor** [comment]
最新版本,已经解决

**Comment by sartonsh** [comment]
我用的是最新版，还是同样的问题

**Comment by gedoor** [comment]
最新版本是1211

**Comment by gedoor** [comment]
在书籍详情页点击阅读按键时会闪退到发现页面，之前版本会在阅读界面点击播放及定时按键时闪退。发下崩溃日志

**Comment by sartonsh** [comment]
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@ddf1388
versionCode=1
BOARD=msm8996
BOOTLOADER=unknown
TYPE=user
ID=MXB48T
TIME=1566541955000
BRAND=SMARTISAN
TAG=Build
SERIAL=62d114ac
HARDWARE=qcom
SUPPORTED_ABIS=[Ljava.lang.String;@31ef121
CPU_ABI=arm64-v8a
RADIO=unknown
IS_DEBUGGABLE=false
MANUFACTURER=smartisan
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@9b0332b
TAGS=release-keys
CPU_ABI2=
UNKNOWN=unknown
USER=smartcm
FINGERPRINT=SMARTISAN/colombo/colombo:6.0.1/MXB48T/1:user/release-keys
HOST=hardcomp2
PRODUCT=colombo
versionName=3.20.121212
DISPLAY=MXB48T release-keys
MODEL=SM919
DEVICE=colombo
java.lang.NoClassDefFoundError: j$.$r8$wrapper$java$util$function$Supplier$-WRP
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
	at org.apache.commons.lang3.time.FormatCache.getInstance(FormatCache.java:72)
	at org.apache.commons.lang3.time.FastDateFormat.getInstance(FastDateFormat.java:133)
	at org.apache.commons.lang3.time.DateFormatUtils.<clinit>(DateFormatUtils.java:54)
	at io.legado.app.ui.audio.AudioPlayActivity$initView$5.onProgressChanged(AudioPlayActivity.kt:88)
	at android.widget.SeekBar.onProgressRefresh(SeekBar.java:93)
	at android.widget.ProgressBar.doRefreshProgress(ProgressBar.java:1303)
	at android.widget.ProgressBar.refreshProgress(ProgressBar.java:1315)
	at android.widget.ProgressBar.setMax(ProgressBar.java:1466)
	at android.widget.AbsSeekBar.setMax(AbsSeekBar.java:339)
	at io.legado.app.ui.audio.AudioPlayActivity$observeLiveBus$4.invoke(AudioPlayActivity.kt:210)
	at io.legado.app.ui.audio.AudioPlayActivity$observeLiveBus$4.invoke(AudioPlayActivity.kt:36)
	at io.legado.app.utils.EventBusExtensionsKt$observeEventSticky$o$1.onChanged(EventBusExtensions.kt:41)
	at com.jeremyliao.liveeventbus.core.LiveEventBusCore$ObserverWrapper.onChanged(LiveEventBusCore.java:399)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at com.jeremyliao.liveeventbus.core.LiveEventBusCore$LiveEvent.postInternal(LiveEventBusCore.java:265)
	at com.jeremyliao.liveeventbus.core.LiveEventBusCore$LiveEvent.access$1800(LiveEventBusCore.java:132)
	at com.jeremyliao.liveeventbus.core.LiveEventBusCore$LiveEvent$PostValueTask.run(LiveEventBusCore.java:357)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5554)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:935)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)
是这个么

**Comment by gedoor** [comment]
嗯,等下版本再试试吧,感觉是手机问题,我换个方法

**Comment by sartonsh** [comment]
刚下了最新版，好了。谢谢大佬。
