### ISSUE TITLE
[BUG] io.legado.app.help.MediaHelp.getFocusRequest 会导致系统版本小于Android O的设备闪退

### ISSUE THREAD

**Issue by ag2s20150909** [gedoor/legado#975]
### 机型（如Redmi K30 Pro）
>vivo x9

### 安卓版本（如Android 7.1.1）
>7.1.2

### 阅读Legdao版本（我的-关于-版本,如3.20.112220）
>3.21.050610

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>io.legado.app.help.MediaHelp.getFocusRequest 会导致系统版本小于Android O的设备闪退

### 使用书源（填写URL或者JSON）
>

```json






```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志）
`        E/AndroidRuntime: FATAL EXCEPTION: main

        Process: io.legado.app.debug, PID: 27300
        java.lang.NoClassDefFoundError: Failed resolution of: Landroid/media/AudioFocusRequest;
            at io.legado.app.help.MediaHelp.getFocusRequest(MediaHelp.kt:47)
            at io.legado.app.service.BaseReadAloudService.onCreate(BaseReadAloudService.kt:62)
            at io.legado.app.service.TTSReadAloudService.onCreate(TTSReadAloudService.kt:27)
            at android.app.ActivityThread.handleCreateService(ActivityThread.java:3254)
            at android.app.ActivityThread.-wrap5(ActivityThread.java)
            at andoid.app.ActivityThread$H.handleMessage(ActivityThread.java:1610)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:154)
            at android.app.ActivityThread.main(ActivityThread.java:6211)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)
         Caused by: java.lang.ClassNotFoundException: Didn't find class "android.media.AudioFocusRequest" on path: DexPathList[[zip file "/data/app/io.legado.app.debug-1/base.apk"],nativeLibraryDirectories=[/data/app/io.legado.app.debug-1/lib/arm64, /data/app/io.legado.app.debug-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
            at io.legado.app.help.MediaHelp.getFocusRequest(MediaHelp.kt:47) 
            at io.legado.app.service.BaseReadAloudService.onCreate(BaseReadAloudService.kt:62) 
            at io.legado.app.service.TTSReadAloudService.onCreate(TTSReadAloudService.kt:27) 
            at android.app.ActivityThread.handleCreateService(ActivityThread.java:3254) 
            at android.app.ActivityThread.-wrap5(ActivityThread.java) 
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1610) 
            at android.os.Handler.dispatchMessage(Handler.java:102) 
            at android.os.Looper.loop(Looper.java:154) 
            at android.app.ActivityThread.main(ActivityThread.java:6211) 
            at java.lang.reflect.Method.invoke(Native Method) 
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793) `

**Comment by ag2s20150909** [comment]
建议使用 androidx.media
